// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module LoopMatmulExecute(
  input         clock,
                reset,
                io_req_valid,
  input  [15:0] io_req_bits_max_j,
                io_req_bits_max_k,
                io_req_bits_max_i,
  input  [3:0]  io_req_bits_pad_j,
                io_req_bits_pad_k,
                io_req_bits_pad_i,
  input         io_req_bits_a_tranpose,
                io_req_bits_b_tranpose,
                io_req_bits_accumulate,
  input  [11:0] io_req_bits_a_addr_start,
  input  [12:0] io_req_bits_b_addr_end,
  input  [8:0]  io_req_bits_c_addr_start,
  input         io_req_bits_loop_id,
                io_req_bits_skip,
                io_cmd_ready,
  input  [15:0] io_ld_ka,
                io_ld_kb,
                io_ld_j,
                io_ld_i,
  input         io_lda_completed,
                io_ldb_completed,
                io_ldd_completed,
                io_rob_overloaded,
  output        io_req_ready,
                io_cmd_valid,
  output [6:0]  io_cmd_bits_inst_funct,
  output [63:0] io_cmd_bits_rs1,
                io_cmd_bits_rs2,
  output [15:0] io_k,
                io_j,
                io_i,
  output        io_idle,
                io_loop_id
);

  reg  [1:0]  state;	// @[LoopMatmul.scala:382:22]
  reg  [15:0] req_max_j;	// @[LoopMatmul.scala:384:16]
  reg  [15:0] req_max_k;	// @[LoopMatmul.scala:384:16]
  reg  [15:0] req_max_i;	// @[LoopMatmul.scala:384:16]
  reg  [3:0]  req_pad_j;	// @[LoopMatmul.scala:384:16]
  reg  [3:0]  req_pad_k;	// @[LoopMatmul.scala:384:16]
  reg  [3:0]  req_pad_i;	// @[LoopMatmul.scala:384:16]
  reg         req_a_tranpose;	// @[LoopMatmul.scala:384:16]
  reg         req_b_tranpose;	// @[LoopMatmul.scala:384:16]
  reg         req_accumulate;	// @[LoopMatmul.scala:384:16]
  reg  [11:0] req_a_addr_start;	// @[LoopMatmul.scala:384:16]
  reg  [12:0] req_b_addr_end;	// @[LoopMatmul.scala:384:16]
  reg  [8:0]  req_c_addr_start;	// @[LoopMatmul.scala:384:16]
  reg         req_loop_id;	// @[LoopMatmul.scala:384:16]
  reg         req_skip;	// @[LoopMatmul.scala:384:16]
  wire [24:0] _GEN = {9'h0, req_max_j};	// @[LoopMatmul.scala:384:16, :387:49, :401:54]
  reg  [15:0] k;	// @[LoopMatmul.scala:389:14]
  reg  [15:0] j;	// @[LoopMatmul.scala:390:14]
  reg  [15:0] i;	// @[LoopMatmul.scala:391:14]
  wire [28:0] _GEN_0 = {17'h0, req_a_addr_start} + {{9'h0, req_a_tranpose ? k : i} * {9'h0, req_a_tranpose ? req_max_i : req_max_k} + {9'h0, req_a_tranpose ? i : k}, 4'h0};	// @[LoopMatmul.scala:384:16, :389:14, :391:14, :393:18, :394:18, :398:22, :401:{33,42,54}, :405:34]
  wire [28:0] _GEN_1 = {16'h0, req_b_addr_end} - {{9'h0, req_max_k} * _GEN, 4'h0} + {{9'h0, req_b_tranpose ? j : k} * {9'h0, req_b_tranpose ? req_max_k : req_max_j} + {9'h0, req_b_tranpose ? k : j}, 4'h0};	// @[LoopMatmul.scala:384:16, :387:{37,49}, :389:14, :390:14, :395:18, :396:18, :399:22, :401:54, :402:{29,38,50}, :405:34, Mux.scala:101:16]
  wire [28:0] _GEN_2 = {20'h0, req_c_addr_start} + {{9'h0, i} * _GEN + {9'h0, j}, 4'h0};	// @[LoopMatmul.scala:384:16, :387:49, :390:14, :391:14, :401:{33,54}, :403:{29,34,46}, :405:34]
  wire [15:0] _a_cols_T_1 = req_max_k - 16'h1;	// @[LoopMatmul.scala:384:16, :405:51]
  wire [15:0] _a_rows_T_1 = req_max_i - 16'h1;	// @[LoopMatmul.scala:384:16, :406:51]
  wire [15:0] _b_cols_T_1 = req_max_j - 16'h1;	// @[LoopMatmul.scala:384:16, :407:51]
  wire        _comp_cmd_inst_funct_T = i == 16'h0;	// @[LoopMatmul.scala:391:14, :420:35, Mux.scala:101:16]
  wire        _io_req_ready_output = state == 2'h0;	// @[LoopMatmul.scala:382:22, :413:11, :451:25]
  wire        _ldb_ahead_T_2 = io_ld_ka == k;	// @[LoopMatmul.scala:389:14, :458:65]
  wire        _io_cmd_valid_output = (|state) & ~io_rob_overloaded & (io_lda_completed | io_ld_ka > k | _ldb_ahead_T_2 & io_ld_i > i) & (io_ldb_completed | io_ld_kb > k | _ldb_ahead_T_2 & io_ld_j > j) & io_ldd_completed & ~req_skip;	// @[LoopMatmul.scala:382:22, :384:16, :389:14, :390:14, :391:14, :458:{48,52,65,71,82}, :459:{48,52,71,82}, :463:{25,37,68,71}]
  wire        _T_1 = state == 2'h1;	// @[LoopMatmul.scala:382:22, :464:28, :488:11]
  wire        _T = io_cmd_ready & _io_cmd_valid_output;	// @[Decoupled.scala:51:35, LoopMatmul.scala:463:68]
  wire [16:0] _next_i_T_3 = {1'h0, i} + 17'h1;	// @[LoopMatmul.scala:382:22, :391:14, :405:51, Util.scala:41:15]
  wire        _next_i_T_4 = _next_i_T_3 > {1'h0, _a_rows_T_1};	// @[LoopMatmul.scala:382:22, :406:51, Util.scala:41:15, :43:17]
  wire [15:0] next_i = _next_i_T_4 ? 16'h0 : _next_i_T_3[15:0];	// @[Mux.scala:101:16, Util.scala:41:15, :43:17]
  wire [16:0] _next_j_T_4 = {1'h0, j} + 17'h1;	// @[LoopMatmul.scala:382:22, :390:14, :405:51, Util.scala:41:15]
  wire        _next_j_T_5 = _next_j_T_4 > {1'h0, _b_cols_T_1};	// @[LoopMatmul.scala:382:22, :407:51, Util.scala:41:15, :43:17]
  wire        _state_T_1 = ((|next_i) ? j : _next_j_T_5 ? 16'h0 : _next_j_T_4[15:0]) == 16'h0;	// @[LoopMatmul.scala:390:14, :475:55, :476:55, Mux.scala:101:16, Util.scala:41:15, :43:17]
  wire        _next_k_T_2 = _state_T_1 & ~(|next_i);	// @[LoopMatmul.scala:475:55, :476:{55,63}, Mux.scala:101:16]
  wire [16:0] _next_k_T_6 = {1'h0, k} + 17'h1;	// @[LoopMatmul.scala:382:22, :389:14, :405:51, Util.scala:41:15]
  wire        _next_k_T_7 = _next_k_T_6 > {1'h0, _a_cols_T_1};	// @[LoopMatmul.scala:382:22, :405:51, Util.scala:41:15, :43:17]
  wire        _T_2 = _io_req_ready_output & io_req_valid;	// @[Decoupled.scala:51:35, LoopMatmul.scala:451:25]
  always @(posedge clock) begin
    if (reset)
      state <= 2'h0;	// @[LoopMatmul.scala:382:22, :413:11]
    else if (_T_2)	// @[Decoupled.scala:51:35]
      state <= 2'h1;	// @[LoopMatmul.scala:382:22, :488:11]
    else if (req_skip)	// @[LoopMatmul.scala:384:16]
      state <= 2'h0;	// @[LoopMatmul.scala:382:22, :413:11]
    else if (_T) begin	// @[Decoupled.scala:51:35]
      if (_T_1)	// @[LoopMatmul.scala:464:28]
        state <= 2'h2;	// @[LoopMatmul.scala:382:22, :472:13]
      else	// @[LoopMatmul.scala:464:28]
        state <= {1'h0, ~((_next_k_T_2 ? (_next_k_T_7 ? 16'h0 : _next_k_T_6[15:0]) : k) == 16'h0 & _state_T_1 & ~(|next_i))};	// @[LoopMatmul.scala:382:22, :389:14, :475:55, :476:{55,63}, :482:{13,19,27,53}, Mux.scala:101:16, Util.scala:41:15, :43:17]
    end
    if (_T_2) begin	// @[Decoupled.scala:51:35]
      req_max_j <= io_req_bits_max_j;	// @[LoopMatmul.scala:384:16]
      req_max_k <= io_req_bits_max_k;	// @[LoopMatmul.scala:384:16]
      req_max_i <= io_req_bits_max_i;	// @[LoopMatmul.scala:384:16]
      req_pad_j <= io_req_bits_pad_j;	// @[LoopMatmul.scala:384:16]
      req_pad_k <= io_req_bits_pad_k;	// @[LoopMatmul.scala:384:16]
      req_pad_i <= io_req_bits_pad_i;	// @[LoopMatmul.scala:384:16]
      req_a_tranpose <= io_req_bits_a_tranpose;	// @[LoopMatmul.scala:384:16]
      req_b_tranpose <= io_req_bits_b_tranpose;	// @[LoopMatmul.scala:384:16]
      req_accumulate <= io_req_bits_accumulate;	// @[LoopMatmul.scala:384:16]
      req_a_addr_start <= io_req_bits_a_addr_start;	// @[LoopMatmul.scala:384:16]
      req_b_addr_end <= io_req_bits_b_addr_end;	// @[LoopMatmul.scala:384:16]
      req_c_addr_start <= io_req_bits_c_addr_start;	// @[LoopMatmul.scala:384:16]
      req_loop_id <= io_req_bits_loop_id;	// @[LoopMatmul.scala:384:16]
      req_skip <= io_req_bits_skip;	// @[LoopMatmul.scala:384:16]
      k <= 16'h0;	// @[LoopMatmul.scala:389:14, Mux.scala:101:16]
      j <= 16'h0;	// @[LoopMatmul.scala:390:14, Mux.scala:101:16]
      i <= 16'h0;	// @[LoopMatmul.scala:391:14, Mux.scala:101:16]
    end
    else begin	// @[Decoupled.scala:51:35]
      if (req_skip | ~_T | _T_1 | ~_next_k_T_2) begin	// @[Decoupled.scala:51:35, LoopMatmul.scala:384:16, :389:14, :464:28, :468:18, :470:28, :471:26, :476:63, Util.scala:42:8]
      end
      else if (_next_k_T_7)	// @[Util.scala:43:17]
        k <= 16'h0;	// @[LoopMatmul.scala:389:14, Mux.scala:101:16]
      else	// @[Util.scala:43:17]
        k <= _next_k_T_6[15:0];	// @[LoopMatmul.scala:389:14, Util.scala:41:15]
      if (req_skip | ~_T | _T_1 | (|next_i)) begin	// @[Decoupled.scala:51:35, LoopMatmul.scala:384:16, :389:14, :390:14, :464:28, :468:18, :470:28, :471:26, :475:55, Mux.scala:101:16]
      end
      else if (_next_j_T_5)	// @[Util.scala:43:17]
        j <= 16'h0;	// @[LoopMatmul.scala:390:14, Mux.scala:101:16]
      else	// @[Util.scala:43:17]
        j <= _next_j_T_4[15:0];	// @[LoopMatmul.scala:390:14, Util.scala:41:15]
      if (req_skip | ~_T | _T_1) begin	// @[Decoupled.scala:51:35, LoopMatmul.scala:384:16, :389:14, :391:14, :464:28, :468:18, :470:28, :471:26]
      end
      else if (_next_i_T_4)	// @[Util.scala:43:17]
        i <= 16'h0;	// @[LoopMatmul.scala:391:14, Mux.scala:101:16]
      else	// @[Util.scala:43:17]
        i <= _next_i_T_3[15:0];	// @[LoopMatmul.scala:391:14, Util.scala:41:15]
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin	// @[LoopMatmul.scala:494:9]
      if (~reset & (|state) & req_a_tranpose & req_b_tranpose) begin	// @[LoopMatmul.scala:382:22, :384:16, :463:25, :494:9]
        if (`ASSERT_VERBOSE_COND_)	// @[LoopMatmul.scala:494:9]
          $error("Assertion failed\n    at LoopMatmul.scala:494 assert(!(state =/= idle && req.a_tranpose && req.b_tranpose))\n");	// @[LoopMatmul.scala:494:9]
        if (`STOP_COND_)	// @[LoopMatmul.scala:494:9]
          $fatal;	// @[LoopMatmul.scala:494:9]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        state = _RANDOM_0[1:0];	// @[LoopMatmul.scala:382:22]
        req_max_j = _RANDOM_0[17:2];	// @[LoopMatmul.scala:382:22, :384:16]
        req_max_k = {_RANDOM_0[31:18], _RANDOM_1[1:0]};	// @[LoopMatmul.scala:382:22, :384:16]
        req_max_i = _RANDOM_1[17:2];	// @[LoopMatmul.scala:384:16]
        req_pad_j = _RANDOM_1[21:18];	// @[LoopMatmul.scala:384:16]
        req_pad_k = _RANDOM_1[25:22];	// @[LoopMatmul.scala:384:16]
        req_pad_i = _RANDOM_1[29:26];	// @[LoopMatmul.scala:384:16]
        req_a_tranpose = _RANDOM_1[30];	// @[LoopMatmul.scala:384:16]
        req_b_tranpose = _RANDOM_1[31];	// @[LoopMatmul.scala:384:16]
        req_accumulate = _RANDOM_2[0];	// @[LoopMatmul.scala:384:16]
        req_a_addr_start = _RANDOM_2[12:1];	// @[LoopMatmul.scala:384:16]
        req_b_addr_end = _RANDOM_2[25:13];	// @[LoopMatmul.scala:384:16]
        req_c_addr_start = {_RANDOM_2[31:26], _RANDOM_3[2:0]};	// @[LoopMatmul.scala:384:16]
        req_loop_id = _RANDOM_3[3];	// @[LoopMatmul.scala:384:16]
        req_skip = _RANDOM_3[4];	// @[LoopMatmul.scala:384:16]
        k = _RANDOM_3[20:5];	// @[LoopMatmul.scala:384:16, :389:14]
        j = {_RANDOM_3[31:21], _RANDOM_4[4:0]};	// @[LoopMatmul.scala:384:16, :390:14]
        i = _RANDOM_4[20:5];	// @[LoopMatmul.scala:390:14, :391:14]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  assign io_req_ready = _io_req_ready_output;	// @[LoopMatmul.scala:451:25]
  assign io_cmd_valid = _io_cmd_valid_output;	// @[LoopMatmul.scala:463:68]
  assign io_cmd_bits_inst_funct = _T_1 ? 7'h6 : {6'h2, ~_comp_cmd_inst_funct_T};	// @[LoopMatmul.scala:414:22, :420:{32,35}, :434:23, :464:{21,28}]
  assign io_cmd_bits_rs1 = {11'h0, _T_1 ? {5'h10 - {1'h0, k == _a_cols_T_1 ? req_pad_k : 4'h0}, 11'h0, 5'h10 - {1'h0, j == _b_cols_T_1 ? req_pad_j : 4'h0}, {3{~_comp_cmd_inst_funct_T}}, _comp_cmd_inst_funct_T ? _GEN_1[28:26] : 3'h0, 13'h0, ~_comp_cmd_inst_funct_T | _GEN_1[12], _comp_cmd_inst_funct_T ? _GEN_1[11:0] : 12'hFFF} : {5'h10 - {1'h0, i == _a_rows_T_1 ? req_pad_i : 4'h0}, 11'h0, 5'h10 - {1'h0, k == _a_cols_T_1 ? req_pad_k : 4'h0}, 3'h0, _GEN_0[28:26], 13'h0, _GEN_0[12:0]}};	// @[LocalAddr.scala:99:13, :108:37, :141:12, LoopMatmul.scala:382:22, :384:16, :389:14, :390:14, :391:14, :401:33, :402:29, :405:{29,34,37,51}, :406:{29,34,37,51}, :407:{29,34,37,51}, :408:{29,34,37}, :417:15, :420:{32,35}, :429:30, :448:32, :464:{21,28}]
  assign io_cmd_bits_rs2 = _T_1 ? {11'h0, 5'h10 - {1'h0, i == _a_rows_T_1 ? req_pad_i : 4'h0}, 11'h0, 5'h10 - {1'h0, j == _b_cols_T_1 ? req_pad_j : 4'h0}, 1'h1, req_accumulate | (|k), 1'h0, _GEN_2[28:26], 13'h0, _GEN_2[12:0]} : 64'h100010E0001FFF;	// @[LocalAddr.scala:108:37, :141:12, LoopMatmul.scala:382:22, :384:16, :389:14, :390:14, :391:14, :403:29, :405:{29,34,51}, :406:51, :407:51, :409:{29,34,37}, :410:{29,34,37}, :417:15, :427:{106,111}, :430:30, :449:32, :464:{21,28}]
  assign io_k = k;	// @[LoopMatmul.scala:389:14]
  assign io_j = j;	// @[LoopMatmul.scala:390:14]
  assign io_i = i;	// @[LoopMatmul.scala:391:14]
  assign io_idle = _io_req_ready_output;	// @[LoopMatmul.scala:451:25]
  assign io_loop_id = req_loop_id;	// @[LoopMatmul.scala:384:16]
endmodule

