// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module LoopMatmul(
  input         clock,
                reset,
                io_in_valid,
  input  [6:0]  io_in_bits_cmd_inst_funct,
  input  [4:0]  io_in_bits_cmd_inst_rs2,
                io_in_bits_cmd_inst_rs1,
  input         io_in_bits_cmd_inst_xd,
                io_in_bits_cmd_inst_xs1,
                io_in_bits_cmd_inst_xs2,
  input  [4:0]  io_in_bits_cmd_inst_rd,
  input  [6:0]  io_in_bits_cmd_inst_opcode,
  input  [63:0] io_in_bits_cmd_rs1,
                io_in_bits_cmd_rs2,
  input         io_in_bits_cmd_status_debug,
                io_in_bits_cmd_status_cease,
                io_in_bits_cmd_status_wfi,
  input  [31:0] io_in_bits_cmd_status_isa,
  input  [1:0]  io_in_bits_cmd_status_dprv,
  input         io_in_bits_cmd_status_dv,
  input  [1:0]  io_in_bits_cmd_status_prv,
  input         io_in_bits_cmd_status_v,
                io_in_bits_cmd_status_sd,
  input  [22:0] io_in_bits_cmd_status_zero2,
  input         io_in_bits_cmd_status_mpv,
                io_in_bits_cmd_status_gva,
                io_in_bits_cmd_status_mbe,
                io_in_bits_cmd_status_sbe,
  input  [1:0]  io_in_bits_cmd_status_sxl,
                io_in_bits_cmd_status_uxl,
  input         io_in_bits_cmd_status_sd_rv32,
  input  [7:0]  io_in_bits_cmd_status_zero1,
  input         io_in_bits_cmd_status_tsr,
                io_in_bits_cmd_status_tw,
                io_in_bits_cmd_status_tvm,
                io_in_bits_cmd_status_mxr,
                io_in_bits_cmd_status_sum,
                io_in_bits_cmd_status_mprv,
  input  [1:0]  io_in_bits_cmd_status_xs,
                io_in_bits_cmd_status_fs,
                io_in_bits_cmd_status_mpp,
                io_in_bits_cmd_status_vs,
  input         io_in_bits_cmd_status_spp,
                io_in_bits_cmd_status_mpie,
                io_in_bits_cmd_status_ube,
                io_in_bits_cmd_status_spie,
                io_in_bits_cmd_status_upie,
                io_in_bits_cmd_status_mie,
                io_in_bits_cmd_status_hie,
                io_in_bits_cmd_status_sie,
                io_in_bits_cmd_status_uie,
                io_in_bits_from_matmul_fsm,
                io_in_bits_from_conv_fsm,
                io_out_ready,
  input  [5:0]  io_ld_completed,
                io_st_completed,
                io_ex_completed,
  output        io_in_ready,
                io_out_valid,
  output [6:0]  io_out_bits_cmd_inst_funct,
  output [4:0]  io_out_bits_cmd_inst_rs2,
                io_out_bits_cmd_inst_rs1,
  output        io_out_bits_cmd_inst_xd,
                io_out_bits_cmd_inst_xs1,
                io_out_bits_cmd_inst_xs2,
  output [4:0]  io_out_bits_cmd_inst_rd,
  output [6:0]  io_out_bits_cmd_inst_opcode,
  output [63:0] io_out_bits_cmd_rs1,
                io_out_bits_cmd_rs2,
  output        io_out_bits_cmd_status_debug,
                io_out_bits_cmd_status_cease,
                io_out_bits_cmd_status_wfi,
  output [31:0] io_out_bits_cmd_status_isa,
  output [1:0]  io_out_bits_cmd_status_dprv,
  output        io_out_bits_cmd_status_dv,
  output [1:0]  io_out_bits_cmd_status_prv,
  output        io_out_bits_cmd_status_v,
                io_out_bits_cmd_status_sd,
  output [22:0] io_out_bits_cmd_status_zero2,
  output        io_out_bits_cmd_status_mpv,
                io_out_bits_cmd_status_gva,
                io_out_bits_cmd_status_mbe,
                io_out_bits_cmd_status_sbe,
  output [1:0]  io_out_bits_cmd_status_sxl,
                io_out_bits_cmd_status_uxl,
  output        io_out_bits_cmd_status_sd_rv32,
  output [7:0]  io_out_bits_cmd_status_zero1,
  output        io_out_bits_cmd_status_tsr,
                io_out_bits_cmd_status_tw,
                io_out_bits_cmd_status_tvm,
                io_out_bits_cmd_status_mxr,
                io_out_bits_cmd_status_sum,
                io_out_bits_cmd_status_mprv,
  output [1:0]  io_out_bits_cmd_status_xs,
                io_out_bits_cmd_status_fs,
                io_out_bits_cmd_status_mpp,
                io_out_bits_cmd_status_vs,
  output        io_out_bits_cmd_status_spp,
                io_out_bits_cmd_status_mpie,
                io_out_bits_cmd_status_ube,
                io_out_bits_cmd_status_spie,
                io_out_bits_cmd_status_upie,
                io_out_bits_cmd_status_mie,
                io_out_bits_cmd_status_hie,
                io_out_bits_cmd_status_sie,
                io_out_bits_cmd_status_uie,
                io_out_bits_from_matmul_fsm,
                io_out_bits_from_conv_fsm,
                io_busy
);

  wire        _arb_io_in_0_ready;	// @[LoopMatmul.scala:830:19]
  wire        _arb_io_in_1_ready;	// @[LoopMatmul.scala:830:19]
  wire        _arb_io_in_2_ready;	// @[LoopMatmul.scala:830:19]
  wire        _arb_io_in_3_ready;	// @[LoopMatmul.scala:830:19]
  wire        _arb_io_out_valid;	// @[LoopMatmul.scala:830:19]
  wire [6:0]  _arb_io_out_bits_inst_funct;	// @[LoopMatmul.scala:830:19]
  wire [63:0] _arb_io_out_bits_rs1;	// @[LoopMatmul.scala:830:19]
  wire [63:0] _arb_io_out_bits_rs2;	// @[LoopMatmul.scala:830:19]
  wire        _ldab_arb_io_inA_ready;	// @[LoopMatmul.scala:813:24]
  wire        _ldab_arb_io_inB_ready;	// @[LoopMatmul.scala:813:24]
  wire        _ldab_arb_io_out_valid;	// @[LoopMatmul.scala:813:24]
  wire [6:0]  _ldab_arb_io_out_bits_inst_funct;	// @[LoopMatmul.scala:813:24]
  wire [63:0] _ldab_arb_io_out_bits_rs1;	// @[LoopMatmul.scala:813:24]
  wire [63:0] _ldab_arb_io_out_bits_rs2;	// @[LoopMatmul.scala:813:24]
  wire        _cmd_io_deq_valid;	// @[Decoupled.scala:375:21]
  wire [6:0]  _cmd_io_deq_bits_cmd_inst_funct;	// @[Decoupled.scala:375:21]
  wire [4:0]  _cmd_io_deq_bits_cmd_inst_rs2;	// @[Decoupled.scala:375:21]
  wire [4:0]  _cmd_io_deq_bits_cmd_inst_rs1;	// @[Decoupled.scala:375:21]
  wire        _cmd_io_deq_bits_cmd_inst_xd;	// @[Decoupled.scala:375:21]
  wire        _cmd_io_deq_bits_cmd_inst_xs1;	// @[Decoupled.scala:375:21]
  wire        _cmd_io_deq_bits_cmd_inst_xs2;	// @[Decoupled.scala:375:21]
  wire [4:0]  _cmd_io_deq_bits_cmd_inst_rd;	// @[Decoupled.scala:375:21]
  wire [6:0]  _cmd_io_deq_bits_cmd_inst_opcode;	// @[Decoupled.scala:375:21]
  wire [63:0] _cmd_io_deq_bits_cmd_rs1;	// @[Decoupled.scala:375:21]
  wire [63:0] _cmd_io_deq_bits_cmd_rs2;	// @[Decoupled.scala:375:21]
  wire        _cmd_io_deq_bits_rob_id_valid;	// @[Decoupled.scala:375:21]
  wire [5:0]  _cmd_io_deq_bits_rob_id_bits;	// @[Decoupled.scala:375:21]
  wire        _cmd_io_deq_bits_from_matmul_fsm;	// @[Decoupled.scala:375:21]
  wire        _cmd_io_deq_bits_from_conv_fsm;	// @[Decoupled.scala:375:21]
  wire        _stC_io_req_ready;	// @[LoopMatmul.scala:805:19]
  wire        _stC_io_cmd_valid;	// @[LoopMatmul.scala:805:19]
  wire [6:0]  _stC_io_cmd_bits_inst_funct;	// @[LoopMatmul.scala:805:19]
  wire [63:0] _stC_io_cmd_bits_rs1;	// @[LoopMatmul.scala:805:19]
  wire [63:0] _stC_io_cmd_bits_rs2;	// @[LoopMatmul.scala:805:19]
  wire        _stC_io_idle;	// @[LoopMatmul.scala:805:19]
  wire        _stC_io_loop_id;	// @[LoopMatmul.scala:805:19]
  wire        _ex_io_req_ready;	// @[LoopMatmul.scala:804:18]
  wire        _ex_io_cmd_valid;	// @[LoopMatmul.scala:804:18]
  wire [6:0]  _ex_io_cmd_bits_inst_funct;	// @[LoopMatmul.scala:804:18]
  wire [63:0] _ex_io_cmd_bits_rs1;	// @[LoopMatmul.scala:804:18]
  wire [63:0] _ex_io_cmd_bits_rs2;	// @[LoopMatmul.scala:804:18]
  wire [15:0] _ex_io_k;	// @[LoopMatmul.scala:804:18]
  wire [15:0] _ex_io_j;	// @[LoopMatmul.scala:804:18]
  wire [15:0] _ex_io_i;	// @[LoopMatmul.scala:804:18]
  wire        _ex_io_idle;	// @[LoopMatmul.scala:804:18]
  wire        _ex_io_loop_id;	// @[LoopMatmul.scala:804:18]
  wire        _ldD_io_req_ready;	// @[LoopMatmul.scala:803:19]
  wire        _ldD_io_cmd_valid;	// @[LoopMatmul.scala:803:19]
  wire [63:0] _ldD_io_cmd_bits_rs1;	// @[LoopMatmul.scala:803:19]
  wire [63:0] _ldD_io_cmd_bits_rs2;	// @[LoopMatmul.scala:803:19]
  wire        _ldD_io_idle;	// @[LoopMatmul.scala:803:19]
  wire        _ldD_io_loop_id;	// @[LoopMatmul.scala:803:19]
  wire        _ldB_io_req_ready;	// @[LoopMatmul.scala:802:19]
  wire        _ldB_io_cmd_valid;	// @[LoopMatmul.scala:802:19]
  wire [63:0] _ldB_io_cmd_bits_rs1;	// @[LoopMatmul.scala:802:19]
  wire [63:0] _ldB_io_cmd_bits_rs2;	// @[LoopMatmul.scala:802:19]
  wire [15:0] _ldB_io_k;	// @[LoopMatmul.scala:802:19]
  wire [15:0] _ldB_io_j;	// @[LoopMatmul.scala:802:19]
  wire        _ldB_io_idle;	// @[LoopMatmul.scala:802:19]
  wire        _ldB_io_loop_id;	// @[LoopMatmul.scala:802:19]
  wire        _ldA_io_req_ready;	// @[LoopMatmul.scala:801:19]
  wire        _ldA_io_cmd_valid;	// @[LoopMatmul.scala:801:19]
  wire [63:0] _ldA_io_cmd_bits_rs1;	// @[LoopMatmul.scala:801:19]
  wire [63:0] _ldA_io_cmd_bits_rs2;	// @[LoopMatmul.scala:801:19]
  wire [15:0] _ldA_io_i;	// @[LoopMatmul.scala:801:19]
  wire [15:0] _ldA_io_k;	// @[LoopMatmul.scala:801:19]
  wire        _ldA_io_idle;	// @[LoopMatmul.scala:801:19]
  wire        _ldA_io_loop_id;	// @[LoopMatmul.scala:801:19]
  reg  [15:0] loops_0_max_k;	// @[LoopMatmul.scala:786:18]
  reg  [15:0] loops_0_max_j;	// @[LoopMatmul.scala:786:18]
  reg  [15:0] loops_0_max_i;	// @[LoopMatmul.scala:786:18]
  reg  [15:0] loops_0_pad_k;	// @[LoopMatmul.scala:786:18]
  reg  [15:0] loops_0_pad_j;	// @[LoopMatmul.scala:786:18]
  reg  [15:0] loops_0_pad_i;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_0_a_dram_addr;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_0_b_dram_addr;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_0_d_dram_addr;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_0_c_dram_addr;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_0_a_dram_stride;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_0_b_dram_stride;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_0_d_dram_stride;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_0_c_dram_stride;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_a_transpose;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_b_transpose;	// @[LoopMatmul.scala:786:18]
  reg  [2:0]  loops_0_act;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_low_d;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_full_c;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_ex_accumulate;	// @[LoopMatmul.scala:786:18]
  reg  [1:0]  loops_0_a_ex_spad_id;	// @[LoopMatmul.scala:786:18]
  reg  [1:0]  loops_0_b_ex_spad_id;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_configured;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_running;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_lda_started;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_ldb_started;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_ex_started;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_ldd_started;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_st_started;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_lda_completed;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_ldb_completed;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_ex_completed;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_ldd_completed;	// @[LoopMatmul.scala:786:18]
  reg         loops_0_st_completed;	// @[LoopMatmul.scala:786:18]
  reg  [15:0] loops_1_max_k;	// @[LoopMatmul.scala:786:18]
  reg  [15:0] loops_1_max_j;	// @[LoopMatmul.scala:786:18]
  reg  [15:0] loops_1_max_i;	// @[LoopMatmul.scala:786:18]
  reg  [15:0] loops_1_pad_k;	// @[LoopMatmul.scala:786:18]
  reg  [15:0] loops_1_pad_j;	// @[LoopMatmul.scala:786:18]
  reg  [15:0] loops_1_pad_i;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_1_a_dram_addr;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_1_b_dram_addr;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_1_d_dram_addr;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_1_c_dram_addr;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_1_a_dram_stride;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_1_b_dram_stride;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_1_d_dram_stride;	// @[LoopMatmul.scala:786:18]
  reg  [33:0] loops_1_c_dram_stride;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_a_transpose;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_b_transpose;	// @[LoopMatmul.scala:786:18]
  reg  [2:0]  loops_1_act;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_low_d;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_full_c;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_ex_accumulate;	// @[LoopMatmul.scala:786:18]
  reg  [1:0]  loops_1_a_ex_spad_id;	// @[LoopMatmul.scala:786:18]
  reg  [1:0]  loops_1_b_ex_spad_id;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_configured;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_running;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_lda_started;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_ldb_started;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_ex_started;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_ldd_started;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_st_started;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_lda_completed;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_ldb_completed;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_ex_completed;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_ldd_completed;	// @[LoopMatmul.scala:786:18]
  reg         loops_1_st_completed;	// @[LoopMatmul.scala:786:18]
  reg         head_loop_id;	// @[LoopMatmul.scala:787:25]
  wire        loop_configured = loops_0_configured | loops_1_configured;	// @[LoopMatmul.scala:786:18, :792:58]
  wire        loop_being_configured_id = (head_loop_id ? loops_1_configured : loops_0_configured) ^ head_loop_id;	// @[LoopMatmul.scala:786:18, :787:25, :794:37]
  reg         is_resadd;	// @[LoopMatmul.scala:797:26]
  wire        ab_loads_on_same_loop = _ldA_io_loop_id == _ldB_io_loop_id;	// @[LoopMatmul.scala:801:19, :802:19, :816:46]
  reg  [3:0]  ld_utilization;	// @[LoopMatmul.scala:838:31]
  reg  [2:0]  st_utilization;	// @[LoopMatmul.scala:839:31]
  reg  [4:0]  ex_utilization;	// @[LoopMatmul.scala:840:31]
  wire        is_loop_run_cmd = _cmd_io_deq_bits_cmd_inst_funct == 7'h8;	// @[Decoupled.scala:375:21, LoopMatmul.scala:851:49]
  wire        is_loop_config_cmd = _cmd_io_deq_bits_cmd_inst_funct > 7'h8 & _cmd_io_deq_bits_cmd_inst_funct < 7'hE;	// @[Decoupled.scala:375:21, LoopMatmul.scala:851:49, :852:{52,77,104}]
  wire        is_loop_cmd = is_loop_run_cmd | is_loop_config_cmd;	// @[LoopMatmul.scala:851:49, :852:77, :853:37]
  wire        _GEN = loop_being_configured_id ? loops_1_configured : loops_0_configured;	// @[LoopMatmul.scala:786:18, :794:37, :862:33]
  reg  [15:0] loops_configured;	// @[LoopMatmul.scala:897:33]
  reg  [8:0]  ld_d_addr_start;	// @[LoopMatmul.scala:954:32]
  reg  [8:0]  ex_c_addr_start;	// @[LoopMatmul.scala:955:32]
  reg  [8:0]  st_c_addr_start;	// @[LoopMatmul.scala:956:32]
  wire        loop_requesting_ldA_id = (head_loop_id ? loops_1_lda_started : loops_0_lda_started) ^ head_loop_id;	// @[LoopMatmul.scala:786:18, :787:25, :794:37, :958:35]
  wire [1:0]  _GEN_0 = loop_requesting_ldA_id ? loops_1_a_ex_spad_id : loops_0_a_ex_spad_id;	// @[LoopMatmul.scala:786:18, :958:35, :960:31]
  wire        _ldA_io_req_valid_T_1 = ~(loop_requesting_ldA_id ? loops_1_lda_started : loops_0_lda_started) & (loop_requesting_ldA_id ? loops_1_configured : loops_0_configured);	// @[LoopMatmul.scala:786:18, :958:35, :960:31, :971:{23,56}]
  wire        loop_requesting_ldB_id = (head_loop_id ? loops_1_ldb_started : loops_0_ldb_started) ^ head_loop_id;	// @[LoopMatmul.scala:786:18, :787:25, :794:37, :978:35]
  wire [1:0]  _GEN_1 = loop_requesting_ldB_id ? loops_1_b_ex_spad_id : loops_0_b_ex_spad_id;	// @[LoopMatmul.scala:786:18, :978:35, :980:25]
  wire        _ldB_io_req_valid_T_1 = ~(loop_requesting_ldB_id ? loops_1_ldb_started : loops_0_ldb_started) & (loop_requesting_ldB_id ? loops_1_configured : loops_0_configured);	// @[LoopMatmul.scala:786:18, :978:35, :980:25, :991:{23,56}]
  wire        loop_requesting_ex_id = (head_loop_id ? loops_1_ex_started : loops_0_ex_started) ^ head_loop_id;	// @[LoopMatmul.scala:786:18, :787:25, :794:37, :998:34]
  wire [1:0]  _GEN_2 = loop_requesting_ex_id ? loops_1_a_ex_spad_id : loops_0_a_ex_spad_id;	// @[LoopMatmul.scala:786:18, :998:34, :1000:24]
  wire [1:0]  _GEN_3 = loop_requesting_ex_id ? loops_1_b_ex_spad_id : loops_0_b_ex_spad_id;	// @[LoopMatmul.scala:786:18, :998:34, :1000:24]
  wire        _ex_io_req_valid_T_4 = ~(loop_requesting_ex_id ? loops_1_ex_started : loops_0_ex_started) & (loop_requesting_ex_id ? loops_1_lda_started : loops_0_lda_started) & (loop_requesting_ex_id ? loops_1_ldb_started : loops_0_ldb_started) & (loop_requesting_ex_id ? loops_1_ldd_started : loops_0_ldd_started) & (loop_requesting_ex_id ? loops_1_configured : loops_0_configured);	// @[LoopMatmul.scala:786:18, :998:34, :1000:24, :1015:22, :1016:70]
  wire        loop_requesting_ldD_id = (head_loop_id ? loops_1_ldd_started : loops_0_ldd_started) ^ head_loop_id;	// @[LoopMatmul.scala:786:18, :787:25, :794:37, :1027:35]
  wire        _ldD_io_req_valid_T_1 = ~(loop_requesting_ldD_id ? loops_1_ldd_started : loops_0_ldd_started) & (loop_requesting_ldD_id ? loops_1_configured : loops_0_configured);	// @[LoopMatmul.scala:786:18, :1027:35, :1029:25, :1039:{23,56}]
  wire        loop_requesting_st_id = (head_loop_id ? loops_1_st_started : loops_0_st_started) ^ head_loop_id;	// @[LoopMatmul.scala:786:18, :787:25, :794:37, :1050:34]
  wire [33:0] _GEN_4 = loop_requesting_st_id ? loops_1_c_dram_addr : loops_0_c_dram_addr;	// @[LoopMatmul.scala:786:18, :1050:34, :1052:31]
  wire        _GEN_5 = loop_requesting_st_id ? loops_1_configured : loops_0_configured;	// @[LoopMatmul.scala:786:18, :1050:34, :1052:31]
  wire        _GEN_6 = loop_requesting_st_id ? loops_1_st_started : loops_0_st_started;	// @[LoopMatmul.scala:786:18, :1050:34, :1052:31]
  wire        _GEN_7 = is_resadd ? ~_GEN_6 & _GEN_5 : ~_GEN_6 & (loop_requesting_st_id ? loops_1_ex_started : loops_0_ex_started) & _GEN_5;	// @[LoopMatmul.scala:786:18, :797:26, :1050:34, :1052:31, :1066:{20,23,87}, :1077:18, :1081:{22,56}]
  wire [9:0]  _ld_d_addr_start_T_3 = {1'h0, ld_d_addr_start} + 10'h100;	// @[LoopMatmul.scala:954:32, Util.scala:41:15]
  wire [9:0]  _ex_c_addr_start_T_3 = {1'h0, ex_c_addr_start} + 10'h100;	// @[LoopMatmul.scala:955:32, Util.scala:41:15]
  wire [9:0]  _st_c_addr_start_T_3 = {1'h0, st_c_addr_start} + 10'h100;	// @[LoopMatmul.scala:956:32, Util.scala:41:15]
  wire        _T_14 = _cmd_io_deq_valid & is_loop_cmd & ~_GEN;	// @[Decoupled.scala:375:21, LoopMatmul.scala:853:37, :862:33, :901:33]
  wire        _T_15 = _cmd_io_deq_bits_cmd_inst_funct == 7'h9;	// @[Decoupled.scala:375:21, LoopMatmul.scala:852:52, :903:38]
  wire        _T_16 = _cmd_io_deq_bits_cmd_inst_funct == 7'hA;	// @[Decoupled.scala:375:21, LoopMatmul.scala:903:38]
  wire        _T_17 = _cmd_io_deq_bits_cmd_inst_funct == 7'hB;	// @[Decoupled.scala:375:21, LoopMatmul.scala:903:38]
  wire        _GEN_8 = _T_15 | _T_16;	// @[LoopMatmul.scala:786:18, :903:38]
  wire        _T_18 = _cmd_io_deq_bits_cmd_inst_funct == 7'hC;	// @[Decoupled.scala:375:21, LoopMatmul.scala:903:38]
  wire        _GEN_9 = _T_15 | _T_16 | _T_17;	// @[LoopMatmul.scala:786:18, :903:38]
  wire        _T_19 = _cmd_io_deq_bits_cmd_inst_funct == 7'hD;	// @[Decoupled.scala:375:21, LoopMatmul.scala:852:104, :903:38]
  wire        _GEN_10 = _T_15 | _T_16 | _T_17 | _T_18;	// @[LoopMatmul.scala:786:18, :903:38]
  wire        _GEN_11 = is_loop_run_cmd & ~loop_being_configured_id;	// @[LoopMatmul.scala:786:18, :794:37, :851:49, :903:38, :905:37, :935:45]
  wire        _GEN_12 = _T_15 | _T_16 | _T_17 | _T_18 | _T_19;	// @[LoopMatmul.scala:786:18, :903:38]
  wire        _GEN_13 = is_loop_run_cmd & loop_being_configured_id;	// @[LoopMatmul.scala:786:18, :794:37, :851:49, :903:38, :935:45]
  wire        _T_21 = _ldA_io_req_ready & _ldA_io_req_valid_T_1;	// @[Decoupled.scala:51:35, LoopMatmul.scala:801:19, :971:56]
  wire        _GEN_14 = _T_21 & ~loop_requesting_ldA_id;	// @[Decoupled.scala:51:35, LoopMatmul.scala:786:18, :958:35, :973:26, :974:33]
  wire        _GEN_15 = _T_21 & loop_requesting_ldA_id;	// @[Decoupled.scala:51:35, LoopMatmul.scala:786:18, :958:35, :973:26, :974:33]
  wire        _T_22 = _ldB_io_req_ready & _ldB_io_req_valid_T_1;	// @[Decoupled.scala:51:35, LoopMatmul.scala:802:19, :991:56]
  wire        _GEN_16 = _T_22 ? ~loop_requesting_ldB_id | _GEN_14 | loops_0_running : _GEN_14 | loops_0_running;	// @[Decoupled.scala:51:35, LoopMatmul.scala:786:18, :973:26, :974:33, :978:35, :993:26, :994:33]
  wire        _GEN_17 = _T_22 ? loop_requesting_ldB_id | _GEN_15 | loops_1_running : _GEN_15 | loops_1_running;	// @[Decoupled.scala:51:35, LoopMatmul.scala:786:18, :973:26, :974:33, :978:35, :993:26, :994:33]
  wire        _T_23 = _ex_io_req_ready & _ex_io_req_valid_T_4;	// @[Decoupled.scala:51:35, LoopMatmul.scala:804:18, :1016:70]
  wire        _GEN_18 = _T_23 & ~loop_requesting_ex_id;	// @[Decoupled.scala:51:35, LoopMatmul.scala:993:26, :998:34, :1018:25, :1019:32]
  wire        _GEN_19 = _T_23 & loop_requesting_ex_id;	// @[Decoupled.scala:51:35, LoopMatmul.scala:993:26, :998:34, :1018:25, :1019:32]
  wire        _T_25 = _ldD_io_req_ready & _ldD_io_req_valid_T_1;	// @[Decoupled.scala:51:35, LoopMatmul.scala:803:19, :1039:56]
  wire        _T_27 = _stC_io_req_ready & _GEN_7;	// @[Decoupled.scala:51:35, LoopMatmul.scala:805:19, :1066:20, :1077:18, :1081:22]
  wire        _GEN_20 = _T_27 & ~loop_requesting_st_id;	// @[Decoupled.scala:51:35, LoopMatmul.scala:1041:26, :1050:34, :1068:26, :1069:32]
  wire        _GEN_21 = _T_27 & loop_requesting_st_id;	// @[Decoupled.scala:51:35, LoopMatmul.scala:1041:26, :1050:34, :1068:26, :1069:32]
  wire        _T_30 = _ldA_io_idle & (_ldA_io_loop_id ? loops_1_running : loops_0_running) & (_ldA_io_loop_id ? loops_1_lda_started : loops_0_lda_started);	// @[LoopMatmul.scala:786:18, :801:19, :1084:{21,54}]
  wire        _T_32 = _ldB_io_idle & (_ldB_io_loop_id ? loops_1_running : loops_0_running) & (_ldB_io_loop_id ? loops_1_ldb_started : loops_0_ldb_started);	// @[LoopMatmul.scala:786:18, :802:19, :1088:{21,54}]
  wire        _T_34 = _ex_io_idle & (_ex_io_loop_id ? loops_1_running : loops_0_running) & (_ex_io_loop_id ? loops_1_ex_started : loops_0_ex_started);	// @[LoopMatmul.scala:786:18, :804:18, :1092:{20,52}]
  wire        _T_36 = _ldD_io_idle & (_ldD_io_loop_id ? loops_1_running : loops_0_running) & (_ldD_io_loop_id ? loops_1_ldd_started : loops_0_ldd_started);	// @[LoopMatmul.scala:786:18, :803:19, :1096:{21,54}]
  wire        _T_38 = _stC_io_idle & (_stC_io_loop_id ? loops_1_running : loops_0_running) & (_stC_io_loop_id ? loops_1_st_started : loops_0_st_started);	// @[LoopMatmul.scala:786:18, :805:19, :1100:{21,54}]
  wire        _T_43 = (head_loop_id ? loops_1_running : loops_0_running) & (head_loop_id ? loops_1_lda_completed : loops_0_lda_completed) & (head_loop_id ? loops_1_ldb_completed : loops_0_ldb_completed) & (head_loop_id ? loops_1_ldd_completed : loops_0_ldd_completed) & (head_loop_id ? loops_1_ex_completed : loops_0_ex_completed) & (head_loop_id ? loops_1_st_completed : loops_0_st_completed);	// @[LoopMatmul.scala:786:18, :787:25, :794:37, :1104:27]
  wire        _GEN_22 = reset | _T_43 & ~head_loop_id;	// @[LoopMatmul.scala:746:16, :787:25, :901:71, :1104:{27,57}, :1110:23]
  wire        _GEN_23 = reset | _T_43 & head_loop_id;	// @[LoopMatmul.scala:746:16, :787:25, :901:71, :1104:{27,57}, :1110:23]
  always @(posedge clock) begin
    if (_T_14 & _T_15 & ~loop_being_configured_id) begin	// @[LoopMatmul.scala:786:18, :794:37, :901:{33,71}, :903:38, :905:37]
      loops_0_max_k <= _cmd_io_deq_bits_cmd_rs2[47:32];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :905:56]
      loops_0_max_j <= _cmd_io_deq_bits_cmd_rs2[31:16];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :906:56]
      loops_0_max_i <= _cmd_io_deq_bits_cmd_rs2[15:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :907:56]
      loops_0_pad_k <= _cmd_io_deq_bits_cmd_rs1[47:32];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :909:56]
      loops_0_pad_j <= _cmd_io_deq_bits_cmd_rs1[31:16];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :910:56]
      loops_0_pad_i <= _cmd_io_deq_bits_cmd_rs1[15:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :911:56]
    end
    if (~_T_14 | _T_15 | ~(_T_16 & ~loop_being_configured_id)) begin	// @[LoopMatmul.scala:786:18, :794:37, :901:{33,71}, :903:38, :905:37, :915:43]
    end
    else begin	// @[LoopMatmul.scala:786:18, :901:71, :903:38]
      loops_0_a_dram_addr <= _cmd_io_deq_bits_cmd_rs1[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :915:43]
      loops_0_b_dram_addr <= _cmd_io_deq_bits_cmd_rs2[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :916:43]
    end
    if (~_T_14 | _GEN_8 | ~(_T_17 & ~loop_being_configured_id)) begin	// @[LoopMatmul.scala:786:18, :794:37, :901:{33,71}, :903:38, :905:37, :920:43]
    end
    else begin	// @[LoopMatmul.scala:786:18, :901:71, :903:38]
      loops_0_d_dram_addr <= _cmd_io_deq_bits_cmd_rs1[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :915:43]
      loops_0_c_dram_addr <= _cmd_io_deq_bits_cmd_rs2[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :916:43]
    end
    if (~_T_14 | _GEN_9 | ~(_T_18 & ~loop_being_configured_id)) begin	// @[LoopMatmul.scala:786:18, :794:37, :901:{33,71}, :903:38, :905:37, :925:45]
    end
    else begin	// @[LoopMatmul.scala:786:18, :901:71, :903:38]
      loops_0_a_dram_stride <= _cmd_io_deq_bits_cmd_rs1[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :915:43]
      loops_0_b_dram_stride <= _cmd_io_deq_bits_cmd_rs2[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :916:43]
    end
    if (~_T_14 | _GEN_10 | ~(_T_19 & ~loop_being_configured_id)) begin	// @[LoopMatmul.scala:786:18, :794:37, :901:{33,71}, :903:38, :905:37, :930:45]
    end
    else begin	// @[LoopMatmul.scala:786:18, :901:71, :903:38]
      loops_0_d_dram_stride <= _cmd_io_deq_bits_cmd_rs1[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :915:43]
      loops_0_c_dram_stride <= _cmd_io_deq_bits_cmd_rs2[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :916:43]
    end
    if (~_T_14 | _GEN_12 | ~_GEN_11) begin	// @[LoopMatmul.scala:786:18, :901:{33,71}, :903:38, :935:45]
    end
    else begin	// @[LoopMatmul.scala:786:18, :901:71, :903:38]
      loops_0_a_transpose <= _cmd_io_deq_bits_cmd_rs2[0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :942:62]
      loops_0_b_transpose <= _cmd_io_deq_bits_cmd_rs2[1];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :943:62]
      loops_0_act <= _cmd_io_deq_bits_cmd_rs1[10:8];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :938:54]
      loops_0_low_d <= _cmd_io_deq_bits_cmd_rs1[2];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :937:56]
      loops_0_full_c <= _cmd_io_deq_bits_cmd_rs1[1];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :936:57]
      loops_0_ex_accumulate <= _cmd_io_deq_bits_cmd_rs1[0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :935:64]
      loops_0_a_ex_spad_id <= _cmd_io_deq_bits_cmd_rs1[19:18];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :940:63]
      loops_0_b_ex_spad_id <= _cmd_io_deq_bits_cmd_rs1[17:16];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :941:63]
    end
    loops_0_configured <= ~_GEN_22 & (_T_14 & ~_GEN_12 & _GEN_11 | loops_0_configured);	// @[LoopMatmul.scala:746:16, :786:18, :901:{33,71}, :903:38, :935:45, :1104:57, :1110:23]
    loops_0_running <= ~_GEN_22 & (_GEN_20 | (_T_25 ? ~loop_requesting_ldD_id | _GEN_18 | _GEN_16 : _GEN_18 | _GEN_16));	// @[Decoupled.scala:51:35, LoopMatmul.scala:746:16, :748:13, :786:18, :901:71, :973:26, :993:26, :994:33, :1018:25, :1019:32, :1027:35, :1041:26, :1042:33, :1068:26, :1069:32, :1104:57, :1110:23]
    loops_0_lda_started <= ~_GEN_22 & (_GEN_14 | loops_0_lda_started);	// @[LoopMatmul.scala:746:16, :750:17, :786:18, :901:71, :973:26, :974:33, :975:37, :1104:57, :1110:23]
    loops_0_ldb_started <= ~_GEN_22 & (_T_22 & ~loop_requesting_ldB_id | loops_0_ldb_started);	// @[Decoupled.scala:51:35, LoopMatmul.scala:746:16, :751:17, :786:18, :901:71, :978:35, :993:26, :994:33, :995:37, :1104:57, :1110:23]
    loops_0_ex_started <= ~_GEN_22 & (_GEN_18 | loops_0_ex_started);	// @[LoopMatmul.scala:746:16, :752:16, :786:18, :901:71, :993:26, :1018:25, :1019:32, :1020:35, :1104:57, :1110:23]
    loops_0_ldd_started <= ~_GEN_22 & (_T_25 & ~loop_requesting_ldD_id | loops_0_ldd_started);	// @[Decoupled.scala:51:35, LoopMatmul.scala:746:16, :753:17, :786:18, :901:71, :1027:35, :1041:26, :1042:33, :1043:37, :1104:57, :1110:23]
    loops_0_st_started <= ~_GEN_22 & (_GEN_20 | loops_0_st_started);	// @[LoopMatmul.scala:746:16, :754:16, :786:18, :901:71, :1041:26, :1068:26, :1069:32, :1070:35, :1104:57, :1110:23]
    loops_0_lda_completed <= ~_GEN_22 & (_T_30 & ~_ldA_io_loop_id | loops_0_lda_completed);	// @[LoopMatmul.scala:746:16, :756:19, :786:18, :801:19, :901:71, :1084:{54,92}, :1085:41, :1104:57, :1110:23]
    loops_0_ldb_completed <= ~_GEN_22 & (_T_32 & ~_ldB_io_loop_id | loops_0_ldb_completed);	// @[LoopMatmul.scala:746:16, :757:19, :786:18, :802:19, :901:71, :1088:{54,92}, :1089:41, :1104:57, :1110:23]
    loops_0_ex_completed <= ~_GEN_22 & (_T_34 & ~_ex_io_loop_id | loops_0_ex_completed);	// @[LoopMatmul.scala:746:16, :758:18, :786:18, :804:18, :901:71, :1092:{52,88}, :1093:39, :1104:57, :1110:23]
    loops_0_ldd_completed <= ~_GEN_22 & (_T_36 & ~_ldD_io_loop_id | loops_0_ldd_completed);	// @[LoopMatmul.scala:746:16, :759:19, :786:18, :803:19, :901:71, :1096:{54,92}, :1097:41, :1104:57, :1110:23]
    loops_0_st_completed <= ~_GEN_22 & (_T_38 & ~_stC_io_loop_id | loops_0_st_completed);	// @[LoopMatmul.scala:746:16, :760:18, :786:18, :805:19, :901:71, :1100:{54,91}, :1101:40, :1104:57, :1110:23]
    if (_T_14 & _T_15 & loop_being_configured_id) begin	// @[LoopMatmul.scala:786:18, :794:37, :901:{33,71}, :903:38, :905:37]
      loops_1_max_k <= _cmd_io_deq_bits_cmd_rs2[47:32];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :905:56]
      loops_1_max_j <= _cmd_io_deq_bits_cmd_rs2[31:16];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :906:56]
      loops_1_max_i <= _cmd_io_deq_bits_cmd_rs2[15:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :907:56]
      loops_1_pad_k <= _cmd_io_deq_bits_cmd_rs1[47:32];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :909:56]
      loops_1_pad_j <= _cmd_io_deq_bits_cmd_rs1[31:16];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :910:56]
      loops_1_pad_i <= _cmd_io_deq_bits_cmd_rs1[15:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :911:56]
    end
    if (~_T_14 | _T_15 | ~(_T_16 & loop_being_configured_id)) begin	// @[LoopMatmul.scala:786:18, :794:37, :901:{33,71}, :903:38, :915:43]
    end
    else begin	// @[LoopMatmul.scala:786:18, :901:71, :903:38]
      loops_1_a_dram_addr <= _cmd_io_deq_bits_cmd_rs1[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :915:43]
      loops_1_b_dram_addr <= _cmd_io_deq_bits_cmd_rs2[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :916:43]
    end
    if (~_T_14 | _GEN_8 | ~(_T_17 & loop_being_configured_id)) begin	// @[LoopMatmul.scala:786:18, :794:37, :901:{33,71}, :903:38, :920:43]
    end
    else begin	// @[LoopMatmul.scala:786:18, :901:71, :903:38]
      loops_1_d_dram_addr <= _cmd_io_deq_bits_cmd_rs1[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :915:43]
      loops_1_c_dram_addr <= _cmd_io_deq_bits_cmd_rs2[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :916:43]
    end
    if (~_T_14 | _GEN_9 | ~(_T_18 & loop_being_configured_id)) begin	// @[LoopMatmul.scala:786:18, :794:37, :901:{33,71}, :903:38, :925:45]
    end
    else begin	// @[LoopMatmul.scala:786:18, :901:71, :903:38]
      loops_1_a_dram_stride <= _cmd_io_deq_bits_cmd_rs1[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :915:43]
      loops_1_b_dram_stride <= _cmd_io_deq_bits_cmd_rs2[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :916:43]
    end
    if (~_T_14 | _GEN_10 | ~(_T_19 & loop_being_configured_id)) begin	// @[LoopMatmul.scala:786:18, :794:37, :901:{33,71}, :903:38, :930:45]
    end
    else begin	// @[LoopMatmul.scala:786:18, :901:71, :903:38]
      loops_1_d_dram_stride <= _cmd_io_deq_bits_cmd_rs1[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :915:43]
      loops_1_c_dram_stride <= _cmd_io_deq_bits_cmd_rs2[33:0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :916:43]
    end
    if (~_T_14 | _GEN_12 | ~_GEN_13) begin	// @[LoopMatmul.scala:786:18, :901:{33,71}, :903:38, :935:45]
    end
    else begin	// @[LoopMatmul.scala:786:18, :901:71, :903:38]
      loops_1_a_transpose <= _cmd_io_deq_bits_cmd_rs2[0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :942:62]
      loops_1_b_transpose <= _cmd_io_deq_bits_cmd_rs2[1];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :943:62]
      loops_1_act <= _cmd_io_deq_bits_cmd_rs1[10:8];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :938:54]
      loops_1_low_d <= _cmd_io_deq_bits_cmd_rs1[2];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :937:56]
      loops_1_full_c <= _cmd_io_deq_bits_cmd_rs1[1];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :936:57]
      loops_1_ex_accumulate <= _cmd_io_deq_bits_cmd_rs1[0];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :935:64]
      loops_1_a_ex_spad_id <= _cmd_io_deq_bits_cmd_rs1[19:18];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :940:63]
      loops_1_b_ex_spad_id <= _cmd_io_deq_bits_cmd_rs1[17:16];	// @[Decoupled.scala:375:21, LoopMatmul.scala:786:18, :941:63]
    end
    loops_1_configured <= ~_GEN_23 & (_T_14 & ~_GEN_12 & _GEN_13 | loops_1_configured);	// @[LoopMatmul.scala:746:16, :786:18, :901:{33,71}, :903:38, :935:45, :1104:57, :1110:23]
    loops_1_running <= ~_GEN_23 & (_GEN_21 | (_T_25 ? loop_requesting_ldD_id | _GEN_19 | _GEN_17 : _GEN_19 | _GEN_17));	// @[Decoupled.scala:51:35, LoopMatmul.scala:746:16, :748:13, :786:18, :901:71, :973:26, :993:26, :994:33, :1018:25, :1019:32, :1027:35, :1041:26, :1042:33, :1068:26, :1069:32, :1104:57, :1110:23]
    loops_1_lda_started <= ~_GEN_23 & (_GEN_15 | loops_1_lda_started);	// @[LoopMatmul.scala:746:16, :750:17, :786:18, :901:71, :973:26, :974:33, :975:37, :1104:57, :1110:23]
    loops_1_ldb_started <= ~_GEN_23 & (_T_22 & loop_requesting_ldB_id | loops_1_ldb_started);	// @[Decoupled.scala:51:35, LoopMatmul.scala:746:16, :751:17, :786:18, :901:71, :978:35, :993:26, :995:37, :1104:57, :1110:23]
    loops_1_ex_started <= ~_GEN_23 & (_GEN_19 | loops_1_ex_started);	// @[LoopMatmul.scala:746:16, :752:16, :786:18, :901:71, :993:26, :1018:25, :1019:32, :1020:35, :1104:57, :1110:23]
    loops_1_ldd_started <= ~_GEN_23 & (_T_25 & loop_requesting_ldD_id | loops_1_ldd_started);	// @[Decoupled.scala:51:35, LoopMatmul.scala:746:16, :753:17, :786:18, :901:71, :1027:35, :1041:26, :1043:37, :1104:57, :1110:23]
    loops_1_st_started <= ~_GEN_23 & (_GEN_21 | loops_1_st_started);	// @[LoopMatmul.scala:746:16, :754:16, :786:18, :901:71, :1041:26, :1068:26, :1069:32, :1070:35, :1104:57, :1110:23]
    loops_1_lda_completed <= ~_GEN_23 & (_T_30 & _ldA_io_loop_id | loops_1_lda_completed);	// @[LoopMatmul.scala:746:16, :756:19, :786:18, :801:19, :901:71, :1084:{54,92}, :1085:41, :1104:57, :1110:23]
    loops_1_ldb_completed <= ~_GEN_23 & (_T_32 & _ldB_io_loop_id | loops_1_ldb_completed);	// @[LoopMatmul.scala:746:16, :757:19, :786:18, :802:19, :901:71, :1088:{54,92}, :1089:41, :1104:57, :1110:23]
    loops_1_ex_completed <= ~_GEN_23 & (_T_34 & _ex_io_loop_id | loops_1_ex_completed);	// @[LoopMatmul.scala:746:16, :758:18, :786:18, :804:18, :901:71, :1092:{52,88}, :1093:39, :1104:57, :1110:23]
    loops_1_ldd_completed <= ~_GEN_23 & (_T_36 & _ldD_io_loop_id | loops_1_ldd_completed);	// @[LoopMatmul.scala:746:16, :759:19, :786:18, :803:19, :901:71, :1096:{54,92}, :1097:41, :1104:57, :1110:23]
    loops_1_st_completed <= ~_GEN_23 & (_T_38 & _stC_io_loop_id | loops_1_st_completed);	// @[LoopMatmul.scala:746:16, :760:18, :786:18, :805:19, :901:71, :1100:{54,91}, :1101:40, :1104:57, :1110:23]
    head_loop_id <= _T_43 ^ head_loop_id;	// @[LoopMatmul.scala:787:25, :1104:{27,57}, :1106:18]
    if (reset) begin
      is_resadd <= 1'h0;	// @[LoopMatmul.scala:797:26]
      ld_utilization <= 4'h0;	// @[LoopMatmul.scala:838:31]
      st_utilization <= 3'h0;	// @[LoopMatmul.scala:839:31]
      ex_utilization <= 5'h0;	// @[LoopMatmul.scala:830:19, :840:31]
      loops_configured <= 16'h0;	// @[LoopMatmul.scala:897:33]
      ld_d_addr_start <= 9'h0;	// @[LoopMatmul.scala:954:32]
      ex_c_addr_start <= 9'h0;	// @[LoopMatmul.scala:954:32, :955:32]
      st_c_addr_start <= 9'h0;	// @[LoopMatmul.scala:954:32, :956:32]
    end
    else begin
      if (~_T_14 | _GEN_12 | ~is_loop_run_cmd) begin	// @[LoopMatmul.scala:786:18, :797:26, :851:49, :901:{33,71}, :903:38]
      end
      else begin	// @[LoopMatmul.scala:797:26, :901:71, :903:38]
        is_resadd <= _cmd_io_deq_bits_cmd_rs2[2];	// @[Decoupled.scala:375:21, LoopMatmul.scala:797:26, :944:38]
        loops_configured <= loops_configured + 16'h1;	// @[LoopMatmul.scala:897:33, :948:46, :1052:31]
      end
      ld_utilization <= ld_utilization + {3'h0, _ldab_arb_io_inA_ready & _ldA_io_cmd_valid | _ldab_arb_io_inB_ready & _ldB_io_cmd_valid | _arb_io_in_2_ready & _ldD_io_cmd_valid} - io_ld_completed[3:0];	// @[Decoupled.scala:51:35, LoopMatmul.scala:801:19, :802:19, :803:19, :813:24, :830:19, :838:31, :839:31, :842:{36,75,95}]
      st_utilization <= st_utilization + {2'h0, _arb_io_in_0_ready & _stC_io_cmd_valid} - io_st_completed[2:0];	// @[Decoupled.scala:51:35, LoopMatmul.scala:805:19, :830:19, :839:31, :842:95, :843:{36,55}]
      ex_utilization <= ex_utilization + {4'h0, _arb_io_in_1_ready & _ex_io_cmd_valid} - io_ex_completed[4:0];	// @[Decoupled.scala:51:35, LoopMatmul.scala:804:18, :830:19, :838:31, :840:31, :844:{36,54}]
      if (_T_25 & (|(loop_requesting_ldD_id ? loops_1_c_dram_addr : loops_0_c_dram_addr))) begin	// @[Decoupled.scala:51:35, LoopMatmul.scala:786:18, :954:32, :1027:35, :1029:25, :1041:26, :1045:{43,52}, :1046:23]
        if (_ld_d_addr_start_T_3[9])	// @[Util.scala:41:15, :43:17]
          ld_d_addr_start <= 9'h0;	// @[LoopMatmul.scala:954:32]
        else	// @[Util.scala:43:17]
          ld_d_addr_start <= _ld_d_addr_start_T_3[8:0];	// @[LoopMatmul.scala:954:32, Util.scala:41:15]
      end
      if (_T_23 & (|(loop_requesting_ex_id ? loops_1_c_dram_addr : loops_0_c_dram_addr))) begin	// @[Decoupled.scala:51:35, LoopMatmul.scala:786:18, :955:32, :998:34, :1000:24, :1018:25, :1022:{42,51}, :1023:23]
        if (_ex_c_addr_start_T_3[9])	// @[Util.scala:41:15, :43:17]
          ex_c_addr_start <= 9'h0;	// @[LoopMatmul.scala:954:32, :955:32]
        else	// @[Util.scala:43:17]
          ex_c_addr_start <= _ex_c_addr_start_T_3[8:0];	// @[LoopMatmul.scala:955:32, Util.scala:41:15]
      end
      if (_T_27 & (|_GEN_4)) begin	// @[Decoupled.scala:51:35, LoopMatmul.scala:956:32, :1052:31, :1068:26, :1072:{42,51}, :1073:23]
        if (_st_c_addr_start_T_3[9])	// @[Util.scala:41:15, :43:17]
          st_c_addr_start <= 9'h0;	// @[LoopMatmul.scala:954:32, :956:32]
        else	// @[Util.scala:43:17]
          st_c_addr_start <= _st_c_addr_start_T_3[8:0];	// @[LoopMatmul.scala:956:32, Util.scala:41:15]
      end
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin	// @[LoopMatmul.scala:846:9]
      if (~reset & {2'h0, ld_utilization} < io_ld_completed) begin	// @[LoopMatmul.scala:838:31, :842:95, :846:{9,25}]
        if (`ASSERT_VERBOSE_COND_)	// @[LoopMatmul.scala:846:9]
          $error("Assertion failed: ld utilization underflow\n    at LoopMatmul.scala:846 assert(ld_utilization >= io.ld_completed, \"ld utilization underflow\")\n");	// @[LoopMatmul.scala:846:9]
        if (`STOP_COND_)	// @[LoopMatmul.scala:846:9]
          $fatal;	// @[LoopMatmul.scala:846:9]
      end
      if (~reset & {3'h0, st_utilization} < io_st_completed) begin	// @[LoopMatmul.scala:839:31, :847:{9,25}]
        if (`ASSERT_VERBOSE_COND_)	// @[LoopMatmul.scala:847:9]
          $error("Assertion failed: st utilization underflow\n    at LoopMatmul.scala:847 assert(st_utilization >= io.st_completed, \"st utilization underflow\")\n");	// @[LoopMatmul.scala:847:9]
        if (`STOP_COND_)	// @[LoopMatmul.scala:847:9]
          $fatal;	// @[LoopMatmul.scala:847:9]
      end
      if (~reset & {1'h0, ex_utilization} < io_ex_completed) begin	// @[LoopMatmul.scala:840:31, :844:36, :848:{9,25}]
        if (`ASSERT_VERBOSE_COND_)	// @[LoopMatmul.scala:848:9]
          $error("Assertion failed: ex utilization underflow\n    at LoopMatmul.scala:848 assert(ex_utilization >= io.ex_completed, \"ex utilization underflow\")\n");	// @[LoopMatmul.scala:848:9]
        if (`STOP_COND_)	// @[LoopMatmul.scala:848:9]
          $fatal;	// @[LoopMatmul.scala:848:9]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    logic [31:0] _RANDOM_7;
    logic [31:0] _RANDOM_8;
    logic [31:0] _RANDOM_9;
    logic [31:0] _RANDOM_10;
    logic [31:0] _RANDOM_11;
    logic [31:0] _RANDOM_12;
    logic [31:0] _RANDOM_13;
    logic [31:0] _RANDOM_14;
    logic [31:0] _RANDOM_15;
    logic [31:0] _RANDOM_16;
    logic [31:0] _RANDOM_17;
    logic [31:0] _RANDOM_18;
    logic [31:0] _RANDOM_19;
    logic [31:0] _RANDOM_20;
    logic [31:0] _RANDOM_21;
    logic [31:0] _RANDOM_22;
    logic [31:0] _RANDOM_23;
    logic [31:0] _RANDOM_24;
    logic [31:0] _RANDOM_25;
    logic [31:0] _RANDOM_26;
    logic [31:0] _RANDOM_27;
    logic [31:0] _RANDOM_28;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        _RANDOM_13 = `RANDOM;
        _RANDOM_14 = `RANDOM;
        _RANDOM_15 = `RANDOM;
        _RANDOM_16 = `RANDOM;
        _RANDOM_17 = `RANDOM;
        _RANDOM_18 = `RANDOM;
        _RANDOM_19 = `RANDOM;
        _RANDOM_20 = `RANDOM;
        _RANDOM_21 = `RANDOM;
        _RANDOM_22 = `RANDOM;
        _RANDOM_23 = `RANDOM;
        _RANDOM_24 = `RANDOM;
        _RANDOM_25 = `RANDOM;
        _RANDOM_26 = `RANDOM;
        _RANDOM_27 = `RANDOM;
        _RANDOM_28 = `RANDOM;
        loops_0_max_k = _RANDOM_0[15:0];	// @[LoopMatmul.scala:786:18]
        loops_0_max_j = _RANDOM_0[31:16];	// @[LoopMatmul.scala:786:18]
        loops_0_max_i = _RANDOM_1[15:0];	// @[LoopMatmul.scala:786:18]
        loops_0_pad_k = _RANDOM_1[31:16];	// @[LoopMatmul.scala:786:18]
        loops_0_pad_j = _RANDOM_2[15:0];	// @[LoopMatmul.scala:786:18]
        loops_0_pad_i = _RANDOM_2[31:16];	// @[LoopMatmul.scala:786:18]
        loops_0_a_dram_addr = {_RANDOM_3, _RANDOM_4[1:0]};	// @[LoopMatmul.scala:786:18]
        loops_0_b_dram_addr = {_RANDOM_4[31:2], _RANDOM_5[3:0]};	// @[LoopMatmul.scala:786:18]
        loops_0_d_dram_addr = {_RANDOM_5[31:4], _RANDOM_6[5:0]};	// @[LoopMatmul.scala:786:18]
        loops_0_c_dram_addr = {_RANDOM_6[31:6], _RANDOM_7[7:0]};	// @[LoopMatmul.scala:786:18]
        loops_0_a_dram_stride = {_RANDOM_7[31:8], _RANDOM_8[9:0]};	// @[LoopMatmul.scala:786:18]
        loops_0_b_dram_stride = {_RANDOM_8[31:10], _RANDOM_9[11:0]};	// @[LoopMatmul.scala:786:18]
        loops_0_d_dram_stride = {_RANDOM_9[31:12], _RANDOM_10[13:0]};	// @[LoopMatmul.scala:786:18]
        loops_0_c_dram_stride = {_RANDOM_10[31:14], _RANDOM_11[15:0]};	// @[LoopMatmul.scala:786:18]
        loops_0_a_transpose = _RANDOM_11[16];	// @[LoopMatmul.scala:786:18]
        loops_0_b_transpose = _RANDOM_11[17];	// @[LoopMatmul.scala:786:18]
        loops_0_act = _RANDOM_11[20:18];	// @[LoopMatmul.scala:786:18]
        loops_0_low_d = _RANDOM_11[21];	// @[LoopMatmul.scala:786:18]
        loops_0_full_c = _RANDOM_11[22];	// @[LoopMatmul.scala:786:18]
        loops_0_ex_accumulate = _RANDOM_11[23];	// @[LoopMatmul.scala:786:18]
        loops_0_a_ex_spad_id = _RANDOM_11[25:24];	// @[LoopMatmul.scala:786:18]
        loops_0_b_ex_spad_id = _RANDOM_11[27:26];	// @[LoopMatmul.scala:786:18]
        loops_0_configured = _RANDOM_11[28];	// @[LoopMatmul.scala:786:18]
        loops_0_running = _RANDOM_11[29];	// @[LoopMatmul.scala:786:18]
        loops_0_lda_started = _RANDOM_11[30];	// @[LoopMatmul.scala:786:18]
        loops_0_ldb_started = _RANDOM_11[31];	// @[LoopMatmul.scala:786:18]
        loops_0_ex_started = _RANDOM_12[0];	// @[LoopMatmul.scala:786:18]
        loops_0_ldd_started = _RANDOM_12[1];	// @[LoopMatmul.scala:786:18]
        loops_0_st_started = _RANDOM_12[2];	// @[LoopMatmul.scala:786:18]
        loops_0_lda_completed = _RANDOM_12[3];	// @[LoopMatmul.scala:786:18]
        loops_0_ldb_completed = _RANDOM_12[4];	// @[LoopMatmul.scala:786:18]
        loops_0_ex_completed = _RANDOM_12[5];	// @[LoopMatmul.scala:786:18]
        loops_0_ldd_completed = _RANDOM_12[6];	// @[LoopMatmul.scala:786:18]
        loops_0_st_completed = _RANDOM_12[7];	// @[LoopMatmul.scala:786:18]
        loops_1_max_k = _RANDOM_13[25:10];	// @[LoopMatmul.scala:786:18]
        loops_1_max_j = {_RANDOM_13[31:26], _RANDOM_14[9:0]};	// @[LoopMatmul.scala:786:18]
        loops_1_max_i = _RANDOM_14[25:10];	// @[LoopMatmul.scala:786:18]
        loops_1_pad_k = {_RANDOM_14[31:26], _RANDOM_15[9:0]};	// @[LoopMatmul.scala:786:18]
        loops_1_pad_j = _RANDOM_15[25:10];	// @[LoopMatmul.scala:786:18]
        loops_1_pad_i = {_RANDOM_15[31:26], _RANDOM_16[9:0]};	// @[LoopMatmul.scala:786:18]
        loops_1_a_dram_addr = {_RANDOM_16[31:10], _RANDOM_17[11:0]};	// @[LoopMatmul.scala:786:18]
        loops_1_b_dram_addr = {_RANDOM_17[31:12], _RANDOM_18[13:0]};	// @[LoopMatmul.scala:786:18]
        loops_1_d_dram_addr = {_RANDOM_18[31:14], _RANDOM_19[15:0]};	// @[LoopMatmul.scala:786:18]
        loops_1_c_dram_addr = {_RANDOM_19[31:16], _RANDOM_20[17:0]};	// @[LoopMatmul.scala:786:18]
        loops_1_a_dram_stride = {_RANDOM_20[31:18], _RANDOM_21[19:0]};	// @[LoopMatmul.scala:786:18]
        loops_1_b_dram_stride = {_RANDOM_21[31:20], _RANDOM_22[21:0]};	// @[LoopMatmul.scala:786:18]
        loops_1_d_dram_stride = {_RANDOM_22[31:22], _RANDOM_23[23:0]};	// @[LoopMatmul.scala:786:18]
        loops_1_c_dram_stride = {_RANDOM_23[31:24], _RANDOM_24[25:0]};	// @[LoopMatmul.scala:786:18]
        loops_1_a_transpose = _RANDOM_24[26];	// @[LoopMatmul.scala:786:18]
        loops_1_b_transpose = _RANDOM_24[27];	// @[LoopMatmul.scala:786:18]
        loops_1_act = _RANDOM_24[30:28];	// @[LoopMatmul.scala:786:18]
        loops_1_low_d = _RANDOM_24[31];	// @[LoopMatmul.scala:786:18]
        loops_1_full_c = _RANDOM_25[0];	// @[LoopMatmul.scala:786:18]
        loops_1_ex_accumulate = _RANDOM_25[1];	// @[LoopMatmul.scala:786:18]
        loops_1_a_ex_spad_id = _RANDOM_25[3:2];	// @[LoopMatmul.scala:786:18]
        loops_1_b_ex_spad_id = _RANDOM_25[5:4];	// @[LoopMatmul.scala:786:18]
        loops_1_configured = _RANDOM_25[6];	// @[LoopMatmul.scala:786:18]
        loops_1_running = _RANDOM_25[7];	// @[LoopMatmul.scala:786:18]
        loops_1_lda_started = _RANDOM_25[8];	// @[LoopMatmul.scala:786:18]
        loops_1_ldb_started = _RANDOM_25[9];	// @[LoopMatmul.scala:786:18]
        loops_1_ex_started = _RANDOM_25[10];	// @[LoopMatmul.scala:786:18]
        loops_1_ldd_started = _RANDOM_25[11];	// @[LoopMatmul.scala:786:18]
        loops_1_st_started = _RANDOM_25[12];	// @[LoopMatmul.scala:786:18]
        loops_1_lda_completed = _RANDOM_25[13];	// @[LoopMatmul.scala:786:18]
        loops_1_ldb_completed = _RANDOM_25[14];	// @[LoopMatmul.scala:786:18]
        loops_1_ex_completed = _RANDOM_25[15];	// @[LoopMatmul.scala:786:18]
        loops_1_ldd_completed = _RANDOM_25[16];	// @[LoopMatmul.scala:786:18]
        loops_1_st_completed = _RANDOM_25[17];	// @[LoopMatmul.scala:786:18]
        head_loop_id = _RANDOM_26[20];	// @[LoopMatmul.scala:787:25]
        is_resadd = _RANDOM_26[21];	// @[LoopMatmul.scala:787:25, :797:26]
        ld_utilization = _RANDOM_26[25:22];	// @[LoopMatmul.scala:787:25, :838:31]
        st_utilization = _RANDOM_26[28:26];	// @[LoopMatmul.scala:787:25, :839:31]
        ex_utilization = {_RANDOM_26[31:29], _RANDOM_27[1:0]};	// @[LoopMatmul.scala:787:25, :840:31]
        loops_configured = _RANDOM_27[17:2];	// @[LoopMatmul.scala:840:31, :897:33]
        ld_d_addr_start = _RANDOM_27[26:18];	// @[LoopMatmul.scala:840:31, :954:32]
        ex_c_addr_start = {_RANDOM_27[31:27], _RANDOM_28[3:0]};	// @[LoopMatmul.scala:840:31, :955:32]
        st_c_addr_start = _RANDOM_28[12:4];	// @[LoopMatmul.scala:955:32, :956:32]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  LoopMatmulLdA ldA (	// @[LoopMatmul.scala:801:19]
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (_ldA_io_req_valid_T_1),	// @[LoopMatmul.scala:971:56]
    .io_req_bits_max_i       (loop_requesting_ldA_id ? loops_1_max_i : loops_0_max_i),	// @[LoopMatmul.scala:786:18, :958:35, :960:31]
    .io_req_bits_max_k       (is_resadd ? (loop_requesting_ldA_id ? loops_1_max_j : loops_0_max_j) : loop_requesting_ldA_id ? loops_1_max_k : loops_0_max_k),	// @[LoopMatmul.scala:786:18, :797:26, :958:35, :960:31]
    .io_req_bits_pad_i       (loop_requesting_ldA_id ? loops_1_pad_i[3:0] : loops_0_pad_i[3:0]),	// @[LoopMatmul.scala:786:18, :958:35, :960:31]
    .io_req_bits_pad_k       (is_resadd ? (loop_requesting_ldA_id ? loops_1_pad_j[3:0] : loops_0_pad_j[3:0]) : loop_requesting_ldA_id ? loops_1_pad_k[3:0] : loops_0_pad_k[3:0]),	// @[LoopMatmul.scala:786:18, :797:26, :958:35, :960:31, :962:31]
    .io_req_bits_dram_addr   (loop_requesting_ldA_id ? loops_1_a_dram_addr : loops_0_a_dram_addr),	// @[LoopMatmul.scala:786:18, :958:35, :960:31]
    .io_req_bits_dram_stride (loop_requesting_ldA_id ? loops_1_a_dram_stride : loops_0_a_dram_stride),	// @[LoopMatmul.scala:786:18, :958:35, :960:31]
    .io_req_bits_transpose   (loop_requesting_ldA_id ? loops_1_a_transpose : loops_0_a_transpose),	// @[LoopMatmul.scala:786:18, :958:35, :960:31]
    .io_req_bits_addr_start  (is_resadd ? {3'h0, loop_requesting_ldA_id, 8'h0} : {_GEN_0 == 2'h0 ? loop_requesting_ldA_id : _GEN_0[0] - 1'h1, 11'h0}),	// @[LoopMatmul.scala:797:26, :839:31, :842:95, :958:35, :960:31, :967:{30,36,70,147}, :1077:18, :1078:32]
    .io_req_bits_loop_id     (loop_requesting_ldA_id),	// @[LoopMatmul.scala:958:35]
    .io_req_bits_is_resadd   (is_resadd),	// @[LoopMatmul.scala:797:26]
    .io_cmd_ready            (_ldab_arb_io_inA_ready),	// @[LoopMatmul.scala:813:24]
    .io_rob_overloaded       (ld_utilization[3]),	// @[LoopMatmul.scala:838:31, :866:43]
    .io_req_ready            (_ldA_io_req_ready),
    .io_cmd_valid            (_ldA_io_cmd_valid),
    .io_cmd_bits_rs1         (_ldA_io_cmd_bits_rs1),
    .io_cmd_bits_rs2         (_ldA_io_cmd_bits_rs2),
    .io_i                    (_ldA_io_i),
    .io_k                    (_ldA_io_k),
    .io_idle                 (_ldA_io_idle),
    .io_loop_id              (_ldA_io_loop_id)
  );
  LoopMatmulLdB ldB (	// @[LoopMatmul.scala:802:19]
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (_ldB_io_req_valid_T_1),	// @[LoopMatmul.scala:991:56]
    .io_req_bits_max_k       (is_resadd ? (loop_requesting_ldB_id ? loops_1_max_i : loops_0_max_i) : loop_requesting_ldB_id ? loops_1_max_k : loops_0_max_k),	// @[LoopMatmul.scala:786:18, :797:26, :978:35, :980:25, :981:31]
    .io_req_bits_max_j       (loop_requesting_ldB_id ? loops_1_max_j : loops_0_max_j),	// @[LoopMatmul.scala:786:18, :978:35, :980:25]
    .io_req_bits_pad_k       (is_resadd ? (loop_requesting_ldB_id ? loops_1_pad_i[3:0] : loops_0_pad_i[3:0]) : loop_requesting_ldB_id ? loops_1_pad_k[3:0] : loops_0_pad_k[3:0]),	// @[LoopMatmul.scala:786:18, :797:26, :978:35, :980:25, :983:31]
    .io_req_bits_pad_j       (loop_requesting_ldB_id ? loops_1_pad_j[3:0] : loops_0_pad_j[3:0]),	// @[LoopMatmul.scala:786:18, :978:35, :980:25]
    .io_req_bits_dram_addr   (loop_requesting_ldB_id ? loops_1_b_dram_addr : loops_0_b_dram_addr),	// @[LoopMatmul.scala:786:18, :978:35, :980:25]
    .io_req_bits_dram_stride (loop_requesting_ldB_id ? loops_1_b_dram_stride : loops_0_b_dram_stride),	// @[LoopMatmul.scala:786:18, :978:35, :980:25]
    .io_req_bits_transpose   (loop_requesting_ldB_id ? loops_1_b_transpose : loops_0_b_transpose),	// @[LoopMatmul.scala:786:18, :978:35, :980:25]
    .io_req_bits_addr_end    (is_resadd ? {4'h0, loop_requesting_ldB_id, 8'h0} : _GEN_1 == 2'h0 ? (loop_requesting_ldB_id ? 13'h1000 : 13'h800) : {_GEN_1, 11'h0}),	// @[LoopMatmul.scala:797:26, :838:31, :842:95, :960:31, :978:35, :980:25, :987:{28,34,68,144}, :1077:18, :1079:30, :1114:20]
    .io_req_bits_loop_id     (loop_requesting_ldB_id),	// @[LoopMatmul.scala:978:35]
    .io_req_bits_is_resadd   (is_resadd),	// @[LoopMatmul.scala:797:26]
    .io_cmd_ready            (_ldab_arb_io_inB_ready),	// @[LoopMatmul.scala:813:24]
    .io_rob_overloaded       (ld_utilization[3]),	// @[LoopMatmul.scala:838:31, :866:43]
    .io_req_ready            (_ldB_io_req_ready),
    .io_cmd_valid            (_ldB_io_cmd_valid),
    .io_cmd_bits_rs1         (_ldB_io_cmd_bits_rs1),
    .io_cmd_bits_rs2         (_ldB_io_cmd_bits_rs2),
    .io_k                    (_ldB_io_k),
    .io_j                    (_ldB_io_j),
    .io_idle                 (_ldB_io_idle),
    .io_loop_id              (_ldB_io_loop_id)
  );
  LoopMatmulLdD ldD (	// @[LoopMatmul.scala:803:19]
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (_ldD_io_req_valid_T_1),	// @[LoopMatmul.scala:1039:56]
    .io_req_bits_max_j       (loop_requesting_ldD_id ? loops_1_max_j : loops_0_max_j),	// @[LoopMatmul.scala:786:18, :1027:35, :1029:25]
    .io_req_bits_max_i       (loop_requesting_ldD_id ? loops_1_max_i : loops_0_max_i),	// @[LoopMatmul.scala:786:18, :1027:35, :1029:25]
    .io_req_bits_pad_j       (loop_requesting_ldD_id ? loops_1_pad_j[3:0] : loops_0_pad_j[3:0]),	// @[LoopMatmul.scala:786:18, :1027:35, :1029:25]
    .io_req_bits_pad_i       (loop_requesting_ldD_id ? loops_1_pad_i[3:0] : loops_0_pad_i[3:0]),	// @[LoopMatmul.scala:786:18, :1027:35, :1029:25]
    .io_req_bits_dram_addr   (loop_requesting_ldD_id ? loops_1_d_dram_addr : loops_0_d_dram_addr),	// @[LoopMatmul.scala:786:18, :1027:35, :1029:25]
    .io_req_bits_dram_stride (loop_requesting_ldD_id ? loops_1_d_dram_stride : loops_0_d_dram_stride),	// @[LoopMatmul.scala:786:18, :1027:35, :1029:25]
    .io_req_bits_low_d       (loop_requesting_ldD_id ? loops_1_low_d : loops_0_low_d),	// @[LoopMatmul.scala:786:18, :1027:35, :1029:25]
    .io_req_bits_addr_start  (ld_d_addr_start),	// @[LoopMatmul.scala:954:32]
    .io_req_bits_loop_id     (loop_requesting_ldD_id),	// @[LoopMatmul.scala:1027:35]
    .io_cmd_ready            (_arb_io_in_2_ready),	// @[LoopMatmul.scala:830:19]
    .io_rob_overloaded       (ld_utilization[3]),	// @[LoopMatmul.scala:838:31, :866:43]
    .io_req_ready            (_ldD_io_req_ready),
    .io_cmd_valid            (_ldD_io_cmd_valid),
    .io_cmd_bits_rs1         (_ldD_io_cmd_bits_rs1),
    .io_cmd_bits_rs2         (_ldD_io_cmd_bits_rs2),
    .io_idle                 (_ldD_io_idle),
    .io_loop_id              (_ldD_io_loop_id)
  );
  LoopMatmulExecute ex (	// @[LoopMatmul.scala:804:18]
    .clock                    (clock),
    .reset                    (reset),
    .io_req_valid             (_ex_io_req_valid_T_4),	// @[LoopMatmul.scala:1016:70]
    .io_req_bits_max_j        (loop_requesting_ex_id ? loops_1_max_j : loops_0_max_j),	// @[LoopMatmul.scala:786:18, :998:34, :1000:24]
    .io_req_bits_max_k        (loop_requesting_ex_id ? loops_1_max_k : loops_0_max_k),	// @[LoopMatmul.scala:786:18, :998:34, :1000:24]
    .io_req_bits_max_i        (loop_requesting_ex_id ? loops_1_max_i : loops_0_max_i),	// @[LoopMatmul.scala:786:18, :998:34, :1000:24]
    .io_req_bits_pad_j        (loop_requesting_ex_id ? loops_1_pad_j[3:0] : loops_0_pad_j[3:0]),	// @[LoopMatmul.scala:786:18, :998:34, :1000:24]
    .io_req_bits_pad_k        (loop_requesting_ex_id ? loops_1_pad_k[3:0] : loops_0_pad_k[3:0]),	// @[LoopMatmul.scala:786:18, :998:34, :1000:24]
    .io_req_bits_pad_i        (loop_requesting_ex_id ? loops_1_pad_i[3:0] : loops_0_pad_i[3:0]),	// @[LoopMatmul.scala:786:18, :998:34, :1000:24]
    .io_req_bits_a_tranpose   (loop_requesting_ex_id ? loops_1_a_transpose : loops_0_a_transpose),	// @[LoopMatmul.scala:786:18, :998:34, :1000:24]
    .io_req_bits_b_tranpose   (loop_requesting_ex_id ? loops_1_b_transpose : loops_0_b_transpose),	// @[LoopMatmul.scala:786:18, :998:34, :1000:24]
    .io_req_bits_accumulate   (loop_requesting_ex_id ? loops_1_ex_accumulate : loops_0_ex_accumulate),	// @[LoopMatmul.scala:786:18, :998:34, :1000:24]
    .io_req_bits_a_addr_start ({_GEN_2 == 2'h0 ? loop_requesting_ex_id : _GEN_2[0] - 1'h1, 11'h0}),	// @[LoopMatmul.scala:842:95, :960:31, :998:34, :1000:24, :1007:{31,37,70,145}]
    .io_req_bits_b_addr_end   (_GEN_3 == 2'h0 ? (loop_requesting_ex_id ? 13'h1000 : 13'h800) : {_GEN_3, 11'h0}),	// @[LoopMatmul.scala:842:95, :960:31, :998:34, :1000:24, :1008:{35,68,142}, :1114:20]
    .io_req_bits_c_addr_start (ex_c_addr_start),	// @[LoopMatmul.scala:955:32]
    .io_req_bits_loop_id      (loop_requesting_ex_id),	// @[LoopMatmul.scala:998:34]
    .io_req_bits_skip         (is_resadd),	// @[LoopMatmul.scala:797:26]
    .io_cmd_ready             (_arb_io_in_1_ready),	// @[LoopMatmul.scala:830:19]
    .io_ld_ka                 (_ldA_io_k),	// @[LoopMatmul.scala:801:19]
    .io_ld_kb                 (_ldB_io_k),	// @[LoopMatmul.scala:802:19]
    .io_ld_j                  (_ldB_io_j),	// @[LoopMatmul.scala:802:19]
    .io_ld_i                  (_ldA_io_i),	// @[LoopMatmul.scala:801:19]
    .io_lda_completed         (_ldA_io_loop_id != _ex_io_loop_id | _ldA_io_idle),	// @[LoopMatmul.scala:801:19, :804:18, :873:{42,61}]
    .io_ldb_completed         (_ldB_io_loop_id != _ex_io_loop_id | _ldB_io_idle),	// @[LoopMatmul.scala:802:19, :804:18, :874:{42,61}]
    .io_ldd_completed         (_ldD_io_loop_id != _ex_io_loop_id | _ldD_io_idle),	// @[LoopMatmul.scala:803:19, :804:18, :875:{42,61}]
    .io_rob_overloaded        (ex_utilization[4]),	// @[LoopMatmul.scala:840:31, :868:42]
    .io_req_ready             (_ex_io_req_ready),
    .io_cmd_valid             (_ex_io_cmd_valid),
    .io_cmd_bits_inst_funct   (_ex_io_cmd_bits_inst_funct),
    .io_cmd_bits_rs1          (_ex_io_cmd_bits_rs1),
    .io_cmd_bits_rs2          (_ex_io_cmd_bits_rs2),
    .io_k                     (_ex_io_k),
    .io_j                     (_ex_io_j),
    .io_i                     (_ex_io_i),
    .io_idle                  (_ex_io_idle),
    .io_loop_id               (_ex_io_loop_id)
  );
  LoopMatmulStC stC (	// @[LoopMatmul.scala:805:19]
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (_GEN_7),	// @[LoopMatmul.scala:1066:20, :1077:18, :1081:22]
    .io_req_bits_max_k       (is_resadd ? 16'h1 : loop_requesting_st_id ? loops_1_max_k : loops_0_max_k),	// @[LoopMatmul.scala:786:18, :797:26, :1050:34, :1052:31]
    .io_req_bits_max_j       (loop_requesting_st_id ? loops_1_max_j : loops_0_max_j),	// @[LoopMatmul.scala:786:18, :1050:34, :1052:31]
    .io_req_bits_max_i       (loop_requesting_st_id ? loops_1_max_i : loops_0_max_i),	// @[LoopMatmul.scala:786:18, :1050:34, :1052:31]
    .io_req_bits_pad_j       (loop_requesting_st_id ? loops_1_pad_j[3:0] : loops_0_pad_j[3:0]),	// @[LoopMatmul.scala:786:18, :1050:34, :1052:31]
    .io_req_bits_pad_i       (loop_requesting_st_id ? loops_1_pad_i[3:0] : loops_0_pad_i[3:0]),	// @[LoopMatmul.scala:786:18, :1050:34, :1052:31]
    .io_req_bits_dram_addr   (_GEN_4),	// @[LoopMatmul.scala:1052:31]
    .io_req_bits_dram_stride (loop_requesting_st_id ? loops_1_c_dram_stride : loops_0_c_dram_stride),	// @[LoopMatmul.scala:786:18, :1050:34, :1052:31]
    .io_req_bits_full_c      (loop_requesting_st_id ? loops_1_full_c : loops_0_full_c),	// @[LoopMatmul.scala:786:18, :1050:34, :1052:31]
    .io_req_bits_act         (loop_requesting_st_id ? loops_1_act : loops_0_act),	// @[LoopMatmul.scala:786:18, :1050:34, :1052:31]
    .io_req_bits_addr_start  (is_resadd ? {loop_requesting_st_id, 8'h0} : st_c_addr_start),	// @[LoopMatmul.scala:797:26, :956:32, :960:31, :1050:34, :1052:31, :1061:30, :1077:18, :1080:32]
    .io_req_bits_loop_id     (loop_requesting_st_id),	// @[LoopMatmul.scala:1050:34]
    .io_req_bits_is_resadd   (is_resadd),	// @[LoopMatmul.scala:797:26]
    .io_cmd_ready            (_arb_io_in_0_ready),	// @[LoopMatmul.scala:830:19]
    .io_ex_k                 (is_resadd ? 16'h0 : _ex_io_k),	// @[LoopMatmul.scala:797:26, :804:18, :882:15, :889:18, :891:17, :897:33]
    .io_ex_j                 (is_resadd ? _ldB_io_j : _ex_io_j),	// @[LoopMatmul.scala:797:26, :802:19, :804:18, :883:15, :889:18, :892:17]
    .io_ex_i                 (is_resadd ? _ldB_io_k : _ex_io_i),	// @[LoopMatmul.scala:797:26, :802:19, :804:18, :884:15, :889:18, :893:17]
    .io_ex_completed         (is_resadd ? (_ldA_io_loop_id != _stC_io_loop_id | _ldA_io_idle) & (_ldB_io_loop_id != _stC_io_loop_id | _ldB_io_idle) : _ex_io_loop_id != _stC_io_loop_id | _ex_io_idle),	// @[LoopMatmul.scala:797:26, :801:19, :802:19, :804:18, :805:19, :881:{23,41,61}, :889:18, :890:{25,44,63,79,98,117}]
    .io_rob_overloaded       (st_utilization[2]),	// @[LoopMatmul.scala:839:31, :870:43]
    .io_req_ready            (_stC_io_req_ready),
    .io_cmd_valid            (_stC_io_cmd_valid),
    .io_cmd_bits_inst_funct  (_stC_io_cmd_bits_inst_funct),
    .io_cmd_bits_rs1         (_stC_io_cmd_bits_rs1),
    .io_cmd_bits_rs2         (_stC_io_cmd_bits_rs2),
    .io_idle                 (_stC_io_idle),
    .io_loop_id              (_stC_io_loop_id)
  );
  Queue_89 cmd (	// @[Decoupled.scala:375:21]
    .clock                          (clock),
    .reset                          (reset),
    .io_enq_valid                   (io_in_valid),
    .io_enq_bits_cmd_inst_funct     (io_in_bits_cmd_inst_funct),
    .io_enq_bits_cmd_inst_rs2       (io_in_bits_cmd_inst_rs2),
    .io_enq_bits_cmd_inst_rs1       (io_in_bits_cmd_inst_rs1),
    .io_enq_bits_cmd_inst_xd        (io_in_bits_cmd_inst_xd),
    .io_enq_bits_cmd_inst_xs1       (io_in_bits_cmd_inst_xs1),
    .io_enq_bits_cmd_inst_xs2       (io_in_bits_cmd_inst_xs2),
    .io_enq_bits_cmd_inst_rd        (io_in_bits_cmd_inst_rd),
    .io_enq_bits_cmd_inst_opcode    (io_in_bits_cmd_inst_opcode),
    .io_enq_bits_cmd_rs1            (io_in_bits_cmd_rs1),
    .io_enq_bits_cmd_rs2            (io_in_bits_cmd_rs2),
    .io_enq_bits_cmd_status_debug   (io_in_bits_cmd_status_debug),
    .io_enq_bits_cmd_status_cease   (io_in_bits_cmd_status_cease),
    .io_enq_bits_cmd_status_wfi     (io_in_bits_cmd_status_wfi),
    .io_enq_bits_cmd_status_isa     (io_in_bits_cmd_status_isa),
    .io_enq_bits_cmd_status_dprv    (io_in_bits_cmd_status_dprv),
    .io_enq_bits_cmd_status_dv      (io_in_bits_cmd_status_dv),
    .io_enq_bits_cmd_status_prv     (io_in_bits_cmd_status_prv),
    .io_enq_bits_cmd_status_v       (io_in_bits_cmd_status_v),
    .io_enq_bits_cmd_status_sd      (io_in_bits_cmd_status_sd),
    .io_enq_bits_cmd_status_zero2   (io_in_bits_cmd_status_zero2),
    .io_enq_bits_cmd_status_mpv     (io_in_bits_cmd_status_mpv),
    .io_enq_bits_cmd_status_gva     (io_in_bits_cmd_status_gva),
    .io_enq_bits_cmd_status_mbe     (io_in_bits_cmd_status_mbe),
    .io_enq_bits_cmd_status_sbe     (io_in_bits_cmd_status_sbe),
    .io_enq_bits_cmd_status_sxl     (io_in_bits_cmd_status_sxl),
    .io_enq_bits_cmd_status_uxl     (io_in_bits_cmd_status_uxl),
    .io_enq_bits_cmd_status_sd_rv32 (io_in_bits_cmd_status_sd_rv32),
    .io_enq_bits_cmd_status_zero1   (io_in_bits_cmd_status_zero1),
    .io_enq_bits_cmd_status_tsr     (io_in_bits_cmd_status_tsr),
    .io_enq_bits_cmd_status_tw      (io_in_bits_cmd_status_tw),
    .io_enq_bits_cmd_status_tvm     (io_in_bits_cmd_status_tvm),
    .io_enq_bits_cmd_status_mxr     (io_in_bits_cmd_status_mxr),
    .io_enq_bits_cmd_status_sum     (io_in_bits_cmd_status_sum),
    .io_enq_bits_cmd_status_mprv    (io_in_bits_cmd_status_mprv),
    .io_enq_bits_cmd_status_xs      (io_in_bits_cmd_status_xs),
    .io_enq_bits_cmd_status_fs      (io_in_bits_cmd_status_fs),
    .io_enq_bits_cmd_status_mpp     (io_in_bits_cmd_status_mpp),
    .io_enq_bits_cmd_status_vs      (io_in_bits_cmd_status_vs),
    .io_enq_bits_cmd_status_spp     (io_in_bits_cmd_status_spp),
    .io_enq_bits_cmd_status_mpie    (io_in_bits_cmd_status_mpie),
    .io_enq_bits_cmd_status_ube     (io_in_bits_cmd_status_ube),
    .io_enq_bits_cmd_status_spie    (io_in_bits_cmd_status_spie),
    .io_enq_bits_cmd_status_upie    (io_in_bits_cmd_status_upie),
    .io_enq_bits_cmd_status_mie     (io_in_bits_cmd_status_mie),
    .io_enq_bits_cmd_status_hie     (io_in_bits_cmd_status_hie),
    .io_enq_bits_cmd_status_sie     (io_in_bits_cmd_status_sie),
    .io_enq_bits_cmd_status_uie     (io_in_bits_cmd_status_uie),
    .io_enq_bits_rob_id_valid       (1'h0),
    .io_enq_bits_rob_id_bits        (6'h0),
    .io_enq_bits_from_matmul_fsm    (io_in_bits_from_matmul_fsm),
    .io_enq_bits_from_conv_fsm      (io_in_bits_from_conv_fsm),
    .io_deq_ready                   (is_loop_cmd ? ~_GEN : ~loop_configured & io_out_ready),	// @[LoopMatmul.scala:792:58, :853:37, :862:{19,33,68,85}]
    .io_enq_ready                   (io_in_ready),
    .io_deq_valid                   (_cmd_io_deq_valid),
    .io_deq_bits_cmd_inst_funct     (_cmd_io_deq_bits_cmd_inst_funct),
    .io_deq_bits_cmd_inst_rs2       (_cmd_io_deq_bits_cmd_inst_rs2),
    .io_deq_bits_cmd_inst_rs1       (_cmd_io_deq_bits_cmd_inst_rs1),
    .io_deq_bits_cmd_inst_xd        (_cmd_io_deq_bits_cmd_inst_xd),
    .io_deq_bits_cmd_inst_xs1       (_cmd_io_deq_bits_cmd_inst_xs1),
    .io_deq_bits_cmd_inst_xs2       (_cmd_io_deq_bits_cmd_inst_xs2),
    .io_deq_bits_cmd_inst_rd        (_cmd_io_deq_bits_cmd_inst_rd),
    .io_deq_bits_cmd_inst_opcode    (_cmd_io_deq_bits_cmd_inst_opcode),
    .io_deq_bits_cmd_rs1            (_cmd_io_deq_bits_cmd_rs1),
    .io_deq_bits_cmd_rs2            (_cmd_io_deq_bits_cmd_rs2),
    .io_deq_bits_cmd_status_debug   (io_out_bits_cmd_status_debug),
    .io_deq_bits_cmd_status_cease   (io_out_bits_cmd_status_cease),
    .io_deq_bits_cmd_status_wfi     (io_out_bits_cmd_status_wfi),
    .io_deq_bits_cmd_status_isa     (io_out_bits_cmd_status_isa),
    .io_deq_bits_cmd_status_dprv    (io_out_bits_cmd_status_dprv),
    .io_deq_bits_cmd_status_dv      (io_out_bits_cmd_status_dv),
    .io_deq_bits_cmd_status_prv     (io_out_bits_cmd_status_prv),
    .io_deq_bits_cmd_status_v       (io_out_bits_cmd_status_v),
    .io_deq_bits_cmd_status_sd      (io_out_bits_cmd_status_sd),
    .io_deq_bits_cmd_status_zero2   (io_out_bits_cmd_status_zero2),
    .io_deq_bits_cmd_status_mpv     (io_out_bits_cmd_status_mpv),
    .io_deq_bits_cmd_status_gva     (io_out_bits_cmd_status_gva),
    .io_deq_bits_cmd_status_mbe     (io_out_bits_cmd_status_mbe),
    .io_deq_bits_cmd_status_sbe     (io_out_bits_cmd_status_sbe),
    .io_deq_bits_cmd_status_sxl     (io_out_bits_cmd_status_sxl),
    .io_deq_bits_cmd_status_uxl     (io_out_bits_cmd_status_uxl),
    .io_deq_bits_cmd_status_sd_rv32 (io_out_bits_cmd_status_sd_rv32),
    .io_deq_bits_cmd_status_zero1   (io_out_bits_cmd_status_zero1),
    .io_deq_bits_cmd_status_tsr     (io_out_bits_cmd_status_tsr),
    .io_deq_bits_cmd_status_tw      (io_out_bits_cmd_status_tw),
    .io_deq_bits_cmd_status_tvm     (io_out_bits_cmd_status_tvm),
    .io_deq_bits_cmd_status_mxr     (io_out_bits_cmd_status_mxr),
    .io_deq_bits_cmd_status_sum     (io_out_bits_cmd_status_sum),
    .io_deq_bits_cmd_status_mprv    (io_out_bits_cmd_status_mprv),
    .io_deq_bits_cmd_status_xs      (io_out_bits_cmd_status_xs),
    .io_deq_bits_cmd_status_fs      (io_out_bits_cmd_status_fs),
    .io_deq_bits_cmd_status_mpp     (io_out_bits_cmd_status_mpp),
    .io_deq_bits_cmd_status_vs      (io_out_bits_cmd_status_vs),
    .io_deq_bits_cmd_status_spp     (io_out_bits_cmd_status_spp),
    .io_deq_bits_cmd_status_mpie    (io_out_bits_cmd_status_mpie),
    .io_deq_bits_cmd_status_ube     (io_out_bits_cmd_status_ube),
    .io_deq_bits_cmd_status_spie    (io_out_bits_cmd_status_spie),
    .io_deq_bits_cmd_status_upie    (io_out_bits_cmd_status_upie),
    .io_deq_bits_cmd_status_mie     (io_out_bits_cmd_status_mie),
    .io_deq_bits_cmd_status_hie     (io_out_bits_cmd_status_hie),
    .io_deq_bits_cmd_status_sie     (io_out_bits_cmd_status_sie),
    .io_deq_bits_cmd_status_uie     (io_out_bits_cmd_status_uie),
    .io_deq_bits_rob_id_valid       (_cmd_io_deq_bits_rob_id_valid),
    .io_deq_bits_rob_id_bits        (_cmd_io_deq_bits_rob_id_bits),
    .io_deq_bits_from_matmul_fsm    (_cmd_io_deq_bits_from_matmul_fsm),
    .io_deq_bits_from_conv_fsm      (_cmd_io_deq_bits_from_conv_fsm)
  );
  WeightedArbiter ldab_arb (	// @[LoopMatmul.scala:813:24]
    .clock                  (clock),
    .reset                  (reset),
    .io_inA_valid           (_ldA_io_cmd_valid),	// @[LoopMatmul.scala:801:19]
    .io_inA_bits_rs1        (_ldA_io_cmd_bits_rs1),	// @[LoopMatmul.scala:801:19]
    .io_inA_bits_rs2        (_ldA_io_cmd_bits_rs2),	// @[LoopMatmul.scala:801:19]
    .io_inB_valid           (_ldB_io_cmd_valid),	// @[LoopMatmul.scala:802:19]
    .io_inB_bits_rs1        (_ldB_io_cmd_bits_rs1),	// @[LoopMatmul.scala:802:19]
    .io_inB_bits_rs2        (_ldB_io_cmd_bits_rs2),	// @[LoopMatmul.scala:802:19]
    .io_forceA              (is_resadd ? ab_loads_on_same_loop & ~_ldA_io_idle : ~ab_loads_on_same_loop & _ldA_io_loop_id == head_loop_id),	// @[LoopMatmul.scala:787:25, :797:26, :801:19, :816:46, :817:{16,39,57}, :819:{28,62,65}]
    .io_forceB              (is_resadd & _ldA_io_idle | ~ab_loads_on_same_loop & _ldB_io_loop_id == head_loop_id),	// @[LoopMatmul.scala:787:25, :797:26, :801:19, :802:19, :816:46, :817:16, :818:{39,57}, :820:28]
    .io_out_ready           (_arb_io_in_3_ready),	// @[LoopMatmul.scala:830:19]
    .io_inA_idle            (_ldA_io_idle),	// @[LoopMatmul.scala:801:19]
    .io_inB_idle            (_ldB_io_idle),	// @[LoopMatmul.scala:802:19]
    .io_inA_k               (_ldA_io_k),	// @[LoopMatmul.scala:801:19]
    .io_inB_k               (_ldB_io_k),	// @[LoopMatmul.scala:802:19]
    .io_inB_j               (_ldB_io_j),	// @[LoopMatmul.scala:802:19]
    .io_inA_ready           (_ldab_arb_io_inA_ready),
    .io_inB_ready           (_ldab_arb_io_inB_ready),
    .io_out_valid           (_ldab_arb_io_out_valid),
    .io_out_bits_inst_funct (_ldab_arb_io_out_bits_inst_funct),
    .io_out_bits_rs1        (_ldab_arb_io_out_bits_rs1),
    .io_out_bits_rs2        (_ldab_arb_io_out_bits_rs2)
  );
  Arbiter_3 arb (	// @[LoopMatmul.scala:830:19]
    .io_in_0_valid           (_stC_io_cmd_valid),	// @[LoopMatmul.scala:805:19]
    .io_in_0_bits_inst_funct (_stC_io_cmd_bits_inst_funct),	// @[LoopMatmul.scala:805:19]
    .io_in_0_bits_rs1        (_stC_io_cmd_bits_rs1),	// @[LoopMatmul.scala:805:19]
    .io_in_0_bits_rs2        (_stC_io_cmd_bits_rs2),	// @[LoopMatmul.scala:805:19]
    .io_in_1_valid           (_ex_io_cmd_valid),	// @[LoopMatmul.scala:804:18]
    .io_in_1_bits_inst_funct (_ex_io_cmd_bits_inst_funct),	// @[LoopMatmul.scala:804:18]
    .io_in_1_bits_rs1        (_ex_io_cmd_bits_rs1),	// @[LoopMatmul.scala:804:18]
    .io_in_1_bits_rs2        (_ex_io_cmd_bits_rs2),	// @[LoopMatmul.scala:804:18]
    .io_in_2_valid           (_ldD_io_cmd_valid),	// @[LoopMatmul.scala:803:19]
    .io_in_2_bits_rs1        (_ldD_io_cmd_bits_rs1),	// @[LoopMatmul.scala:803:19]
    .io_in_2_bits_rs2        (_ldD_io_cmd_bits_rs2),	// @[LoopMatmul.scala:803:19]
    .io_in_3_valid           (_ldab_arb_io_out_valid),	// @[LoopMatmul.scala:813:24]
    .io_in_3_bits_inst_funct (_ldab_arb_io_out_bits_inst_funct),	// @[LoopMatmul.scala:813:24]
    .io_in_3_bits_rs1        (_ldab_arb_io_out_bits_rs1),	// @[LoopMatmul.scala:813:24]
    .io_in_3_bits_rs2        (_ldab_arb_io_out_bits_rs2),	// @[LoopMatmul.scala:813:24]
    .io_out_ready            (io_out_ready),
    .io_in_0_ready           (_arb_io_in_0_ready),
    .io_in_1_ready           (_arb_io_in_1_ready),
    .io_in_2_ready           (_arb_io_in_2_ready),
    .io_in_3_ready           (_arb_io_in_3_ready),
    .io_out_valid            (_arb_io_out_valid),
    .io_out_bits_inst_funct  (_arb_io_out_bits_inst_funct),
    .io_out_bits_rs1         (_arb_io_out_bits_rs1),
    .io_out_bits_rs2         (_arb_io_out_bits_rs2)
  );
  assign io_out_valid = loop_configured ? _arb_io_out_valid : _cmd_io_deq_valid & ~is_loop_config_cmd & ~is_loop_run_cmd;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :830:19, :851:49, :852:77, :860:{22,73,93,96}]
  assign io_out_bits_cmd_inst_funct = loop_configured ? _arb_io_out_bits_inst_funct : _cmd_io_deq_bits_cmd_inst_funct;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :830:19, :855:25]
  assign io_out_bits_cmd_inst_rs2 = loop_configured ? 5'h0 : _cmd_io_deq_bits_cmd_inst_rs2;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :830:19, :855:25]
  assign io_out_bits_cmd_inst_rs1 = loop_configured ? 5'h0 : _cmd_io_deq_bits_cmd_inst_rs1;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :830:19, :855:25]
  assign io_out_bits_cmd_inst_xd = ~loop_configured & _cmd_io_deq_bits_cmd_inst_xd;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :855:25]
  assign io_out_bits_cmd_inst_xs1 = ~loop_configured & _cmd_io_deq_bits_cmd_inst_xs1;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :855:25]
  assign io_out_bits_cmd_inst_xs2 = ~loop_configured & _cmd_io_deq_bits_cmd_inst_xs2;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :855:25]
  assign io_out_bits_cmd_inst_rd = loop_configured ? 5'h0 : _cmd_io_deq_bits_cmd_inst_rd;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :830:19, :855:25]
  assign io_out_bits_cmd_inst_opcode = loop_configured ? 7'h0 : _cmd_io_deq_bits_cmd_inst_opcode;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :830:19, :855:25]
  assign io_out_bits_cmd_rs1 = loop_configured ? _arb_io_out_bits_rs1 : _cmd_io_deq_bits_cmd_rs1;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :830:19, :855:25]
  assign io_out_bits_cmd_rs2 = loop_configured ? _arb_io_out_bits_rs2 : _cmd_io_deq_bits_cmd_rs2;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :830:19, :855:25]
  assign io_out_bits_from_matmul_fsm = loop_configured | _cmd_io_deq_bits_from_matmul_fsm;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :858:37]
  assign io_out_bits_from_conv_fsm = ~loop_configured & _cmd_io_deq_bits_from_conv_fsm;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :855:25, :859:35]
  assign io_busy = _cmd_io_deq_valid | loop_configured;	// @[Decoupled.scala:375:21, LoopMatmul.scala:792:58, :810:24]
endmodule

