// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module MulAddRecFNToRaw_preMul(
  input  [32:0] io_a,
                io_b,
  output [23:0] io_mulAddA,
                io_mulAddB,
  output [47:0] io_mulAddC,
  output        io_toPostMul_isSigNaNAny,
                io_toPostMul_isNaNAOrB,
                io_toPostMul_isInfA,
                io_toPostMul_isZeroA,
                io_toPostMul_isInfB,
                io_toPostMul_isZeroB,
                io_toPostMul_signProd,
  output [9:0]  io_toPostMul_sExpSum,
  output        io_toPostMul_doSubMags,
  output [25:0] io_toPostMul_highAlignedSigC,
  output        io_toPostMul_bit0AlignedSigC
);

  wire        rawA_isNaN = (&(io_a[31:30])) & io_a[29];	// @[rawFloatFromRecFN.scala:50:21, :52:{29,54}, :55:{33,41}]
  wire        rawB_isNaN = (&(io_b[31:30])) & io_b[29];	// @[rawFloatFromRecFN.scala:50:21, :52:{29,54}, :55:{33,41}]
  wire        _signProd_T = io_a[32] ^ io_b[32];	// @[MulAddRecFN.scala:95:30, rawFloatFromRecFN.scala:58:25]
  wire [10:0] _sExpAlignedProd_T_2 = {2'h0, io_a[31:23]} + {2'h0, io_b[31:23]} - 11'hE5;	// @[MulAddRecFN.scala:98:{19,32}, rawFloatFromRecFN.scala:50:21]
  wire [77:0] mainAlignedSigC = $signed($signed({78{_signProd_T}}) >>> (~(|(io_a[31:29])) | ~(|(io_b[31:29])) | $signed(_sExpAlignedProd_T_2) < 11'sh0 ? 7'h0 : _sExpAlignedProd_T_2[9:0] < 10'h4A ? _sExpAlignedProd_T_2[6:0] : 7'h4A));	// @[Cat.scala:33:92, MulAddRecFN.scala:95:30, :98:32, :105:42, :106:{50,69}, :110:12, :112:{16,34}, :113:33, :120:17, rawFloatFromRecFN.scala:50:21, :51:{29,54}]
  assign io_mulAddA = {|(io_a[31:29]), io_a[22:0]};	// @[MulAddRecFN.scala:141:16, rawFloatFromRecFN.scala:50:21, :51:{29,54}, :60:51]
  assign io_mulAddB = {|(io_b[31:29]), io_b[22:0]};	// @[MulAddRecFN.scala:142:16, rawFloatFromRecFN.scala:50:21, :51:{29,54}, :60:51]
  assign io_mulAddC = mainAlignedSigC[50:3];	// @[MulAddRecFN.scala:120:17, :143:30]
  assign io_toPostMul_isSigNaNAny = rawA_isNaN & ~(io_a[22]) | rawB_isNaN & ~(io_b[22]);	// @[MulAddRecFN.scala:146:32, common.scala:82:{46,49,56}, rawFloatFromRecFN.scala:55:33]
  assign io_toPostMul_isNaNAOrB = rawA_isNaN | rawB_isNaN;	// @[MulAddRecFN.scala:148:42, rawFloatFromRecFN.scala:55:33]
  assign io_toPostMul_isInfA = (&(io_a[31:30])) & ~(io_a[29]);	// @[rawFloatFromRecFN.scala:50:21, :52:{29,54}, :55:41, :56:{33,36}]
  assign io_toPostMul_isZeroA = ~(|(io_a[31:29]));	// @[rawFloatFromRecFN.scala:50:21, :51:{29,54}]
  assign io_toPostMul_isInfB = (&(io_b[31:30])) & ~(io_b[29]);	// @[rawFloatFromRecFN.scala:50:21, :52:{29,54}, :55:41, :56:{33,36}]
  assign io_toPostMul_isZeroB = ~(|(io_b[31:29]));	// @[rawFloatFromRecFN.scala:50:21, :51:{29,54}]
  assign io_toPostMul_signProd = _signProd_T;	// @[MulAddRecFN.scala:95:30]
  assign io_toPostMul_sExpSum = _sExpAlignedProd_T_2[9:0] - 10'h18;	// @[MulAddRecFN.scala:98:32, :158:53]
  assign io_toPostMul_doSubMags = _signProd_T;	// @[MulAddRecFN.scala:95:30]
  assign io_toPostMul_highAlignedSigC = mainAlignedSigC[76:51];	// @[MulAddRecFN.scala:120:17, :163:20]
  assign io_toPostMul_bit0AlignedSigC = _signProd_T ? (&(mainAlignedSigC[2:0])) : (|(mainAlignedSigC[2:0]));	// @[MulAddRecFN.scala:95:30, :120:17, :133:16, :134:{32,39}, :135:39]
endmodule

