// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module PTW(
  input         clock,
  input  [20:0] io_requestor_2_req_bits_bits_addr,
  input         io_dpath_status_debug,
                io_dpath_pmp_0_cfg_l,
  input  [1:0]  io_dpath_pmp_0_cfg_a,
  input         io_dpath_pmp_0_cfg_x,
                io_dpath_pmp_0_cfg_w,
                io_dpath_pmp_0_cfg_r,
  input  [29:0] io_dpath_pmp_0_addr,
  input  [31:0] io_dpath_pmp_0_mask,
  input         io_dpath_pmp_1_cfg_l,
  input  [1:0]  io_dpath_pmp_1_cfg_a,
  input         io_dpath_pmp_1_cfg_x,
                io_dpath_pmp_1_cfg_w,
                io_dpath_pmp_1_cfg_r,
  input  [29:0] io_dpath_pmp_1_addr,
  input  [31:0] io_dpath_pmp_1_mask,
  input         io_dpath_pmp_2_cfg_l,
  input  [1:0]  io_dpath_pmp_2_cfg_a,
  input         io_dpath_pmp_2_cfg_x,
                io_dpath_pmp_2_cfg_w,
                io_dpath_pmp_2_cfg_r,
  input  [29:0] io_dpath_pmp_2_addr,
  input  [31:0] io_dpath_pmp_2_mask,
  input         io_dpath_pmp_3_cfg_l,
  input  [1:0]  io_dpath_pmp_3_cfg_a,
  input         io_dpath_pmp_3_cfg_x,
                io_dpath_pmp_3_cfg_w,
                io_dpath_pmp_3_cfg_r,
  input  [29:0] io_dpath_pmp_3_addr,
  input  [31:0] io_dpath_pmp_3_mask,
  input         io_dpath_pmp_4_cfg_l,
  input  [1:0]  io_dpath_pmp_4_cfg_a,
  input         io_dpath_pmp_4_cfg_x,
                io_dpath_pmp_4_cfg_w,
                io_dpath_pmp_4_cfg_r,
  input  [29:0] io_dpath_pmp_4_addr,
  input  [31:0] io_dpath_pmp_4_mask,
  input         io_dpath_pmp_5_cfg_l,
  input  [1:0]  io_dpath_pmp_5_cfg_a,
  input         io_dpath_pmp_5_cfg_x,
                io_dpath_pmp_5_cfg_w,
                io_dpath_pmp_5_cfg_r,
  input  [29:0] io_dpath_pmp_5_addr,
  input  [31:0] io_dpath_pmp_5_mask,
  input         io_dpath_pmp_6_cfg_l,
  input  [1:0]  io_dpath_pmp_6_cfg_a,
  input         io_dpath_pmp_6_cfg_x,
                io_dpath_pmp_6_cfg_w,
                io_dpath_pmp_6_cfg_r,
  input  [29:0] io_dpath_pmp_6_addr,
  input  [31:0] io_dpath_pmp_6_mask,
  input         io_dpath_pmp_7_cfg_l,
  input  [1:0]  io_dpath_pmp_7_cfg_a,
  input         io_dpath_pmp_7_cfg_x,
                io_dpath_pmp_7_cfg_w,
                io_dpath_pmp_7_cfg_r,
  input  [29:0] io_dpath_pmp_7_addr,
  input  [31:0] io_dpath_pmp_7_mask,
  input  [63:0] io_dpath_customCSRs_csrs_0_value,
  output        io_requestor_0_pmp_0_cfg_l,
  output [1:0]  io_requestor_0_pmp_0_cfg_a,
  output        io_requestor_0_pmp_0_cfg_w,
                io_requestor_0_pmp_0_cfg_r,
  output [29:0] io_requestor_0_pmp_0_addr,
  output [31:0] io_requestor_0_pmp_0_mask,
  output        io_requestor_0_pmp_1_cfg_l,
  output [1:0]  io_requestor_0_pmp_1_cfg_a,
  output        io_requestor_0_pmp_1_cfg_w,
                io_requestor_0_pmp_1_cfg_r,
  output [29:0] io_requestor_0_pmp_1_addr,
  output [31:0] io_requestor_0_pmp_1_mask,
  output        io_requestor_0_pmp_2_cfg_l,
  output [1:0]  io_requestor_0_pmp_2_cfg_a,
  output        io_requestor_0_pmp_2_cfg_w,
                io_requestor_0_pmp_2_cfg_r,
  output [29:0] io_requestor_0_pmp_2_addr,
  output [31:0] io_requestor_0_pmp_2_mask,
  output        io_requestor_0_pmp_3_cfg_l,
  output [1:0]  io_requestor_0_pmp_3_cfg_a,
  output        io_requestor_0_pmp_3_cfg_w,
                io_requestor_0_pmp_3_cfg_r,
  output [29:0] io_requestor_0_pmp_3_addr,
  output [31:0] io_requestor_0_pmp_3_mask,
  output        io_requestor_0_pmp_4_cfg_l,
  output [1:0]  io_requestor_0_pmp_4_cfg_a,
  output        io_requestor_0_pmp_4_cfg_w,
                io_requestor_0_pmp_4_cfg_r,
  output [29:0] io_requestor_0_pmp_4_addr,
  output [31:0] io_requestor_0_pmp_4_mask,
  output        io_requestor_0_pmp_5_cfg_l,
  output [1:0]  io_requestor_0_pmp_5_cfg_a,
  output        io_requestor_0_pmp_5_cfg_w,
                io_requestor_0_pmp_5_cfg_r,
  output [29:0] io_requestor_0_pmp_5_addr,
  output [31:0] io_requestor_0_pmp_5_mask,
  output        io_requestor_0_pmp_6_cfg_l,
  output [1:0]  io_requestor_0_pmp_6_cfg_a,
  output        io_requestor_0_pmp_6_cfg_w,
                io_requestor_0_pmp_6_cfg_r,
  output [29:0] io_requestor_0_pmp_6_addr,
  output [31:0] io_requestor_0_pmp_6_mask,
  output        io_requestor_0_pmp_7_cfg_l,
  output [1:0]  io_requestor_0_pmp_7_cfg_a,
  output        io_requestor_0_pmp_7_cfg_w,
                io_requestor_0_pmp_7_cfg_r,
  output [29:0] io_requestor_0_pmp_7_addr,
  output [31:0] io_requestor_0_pmp_7_mask,
  output        io_requestor_1_status_debug,
                io_requestor_1_pmp_0_cfg_l,
  output [1:0]  io_requestor_1_pmp_0_cfg_a,
  output        io_requestor_1_pmp_0_cfg_w,
                io_requestor_1_pmp_0_cfg_r,
  output [29:0] io_requestor_1_pmp_0_addr,
  output [31:0] io_requestor_1_pmp_0_mask,
  output        io_requestor_1_pmp_1_cfg_l,
  output [1:0]  io_requestor_1_pmp_1_cfg_a,
  output        io_requestor_1_pmp_1_cfg_w,
                io_requestor_1_pmp_1_cfg_r,
  output [29:0] io_requestor_1_pmp_1_addr,
  output [31:0] io_requestor_1_pmp_1_mask,
  output        io_requestor_1_pmp_2_cfg_l,
  output [1:0]  io_requestor_1_pmp_2_cfg_a,
  output        io_requestor_1_pmp_2_cfg_w,
                io_requestor_1_pmp_2_cfg_r,
  output [29:0] io_requestor_1_pmp_2_addr,
  output [31:0] io_requestor_1_pmp_2_mask,
  output        io_requestor_1_pmp_3_cfg_l,
  output [1:0]  io_requestor_1_pmp_3_cfg_a,
  output        io_requestor_1_pmp_3_cfg_w,
                io_requestor_1_pmp_3_cfg_r,
  output [29:0] io_requestor_1_pmp_3_addr,
  output [31:0] io_requestor_1_pmp_3_mask,
  output        io_requestor_1_pmp_4_cfg_l,
  output [1:0]  io_requestor_1_pmp_4_cfg_a,
  output        io_requestor_1_pmp_4_cfg_w,
                io_requestor_1_pmp_4_cfg_r,
  output [29:0] io_requestor_1_pmp_4_addr,
  output [31:0] io_requestor_1_pmp_4_mask,
  output        io_requestor_1_pmp_5_cfg_l,
  output [1:0]  io_requestor_1_pmp_5_cfg_a,
  output        io_requestor_1_pmp_5_cfg_w,
                io_requestor_1_pmp_5_cfg_r,
  output [29:0] io_requestor_1_pmp_5_addr,
  output [31:0] io_requestor_1_pmp_5_mask,
  output        io_requestor_1_pmp_6_cfg_l,
  output [1:0]  io_requestor_1_pmp_6_cfg_a,
  output        io_requestor_1_pmp_6_cfg_w,
                io_requestor_1_pmp_6_cfg_r,
  output [29:0] io_requestor_1_pmp_6_addr,
  output [31:0] io_requestor_1_pmp_6_mask,
  output        io_requestor_1_pmp_7_cfg_l,
  output [1:0]  io_requestor_1_pmp_7_cfg_a,
  output        io_requestor_1_pmp_7_cfg_w,
                io_requestor_1_pmp_7_cfg_r,
  output [29:0] io_requestor_1_pmp_7_addr,
  output [31:0] io_requestor_1_pmp_7_mask,
  output        io_requestor_2_status_debug,
                io_requestor_2_pmp_0_cfg_l,
  output [1:0]  io_requestor_2_pmp_0_cfg_a,
  output        io_requestor_2_pmp_0_cfg_x,
  output [29:0] io_requestor_2_pmp_0_addr,
  output [31:0] io_requestor_2_pmp_0_mask,
  output        io_requestor_2_pmp_1_cfg_l,
  output [1:0]  io_requestor_2_pmp_1_cfg_a,
  output        io_requestor_2_pmp_1_cfg_x,
  output [29:0] io_requestor_2_pmp_1_addr,
  output [31:0] io_requestor_2_pmp_1_mask,
  output        io_requestor_2_pmp_2_cfg_l,
  output [1:0]  io_requestor_2_pmp_2_cfg_a,
  output        io_requestor_2_pmp_2_cfg_x,
  output [29:0] io_requestor_2_pmp_2_addr,
  output [31:0] io_requestor_2_pmp_2_mask,
  output        io_requestor_2_pmp_3_cfg_l,
  output [1:0]  io_requestor_2_pmp_3_cfg_a,
  output        io_requestor_2_pmp_3_cfg_x,
  output [29:0] io_requestor_2_pmp_3_addr,
  output [31:0] io_requestor_2_pmp_3_mask,
  output        io_requestor_2_pmp_4_cfg_l,
  output [1:0]  io_requestor_2_pmp_4_cfg_a,
  output        io_requestor_2_pmp_4_cfg_x,
  output [29:0] io_requestor_2_pmp_4_addr,
  output [31:0] io_requestor_2_pmp_4_mask,
  output        io_requestor_2_pmp_5_cfg_l,
  output [1:0]  io_requestor_2_pmp_5_cfg_a,
  output        io_requestor_2_pmp_5_cfg_x,
  output [29:0] io_requestor_2_pmp_5_addr,
  output [31:0] io_requestor_2_pmp_5_mask,
  output        io_requestor_2_pmp_6_cfg_l,
  output [1:0]  io_requestor_2_pmp_6_cfg_a,
  output        io_requestor_2_pmp_6_cfg_x,
  output [29:0] io_requestor_2_pmp_6_addr,
  output [31:0] io_requestor_2_pmp_6_mask,
  output        io_requestor_2_pmp_7_cfg_l,
  output [1:0]  io_requestor_2_pmp_7_cfg_a,
  output        io_requestor_2_pmp_7_cfg_x,
  output [29:0] io_requestor_2_pmp_7_addr,
  output [31:0] io_requestor_2_pmp_7_mask,
  output [63:0] io_requestor_2_customCSRs_csrs_0_value
);

  wire [43:0] _r_pte_barrier_io_y_ppn;	// @[package.scala:259:25]
  wire        _r_pte_barrier_io_y_d;	// @[package.scala:259:25]
  wire        _r_pte_barrier_io_y_a;	// @[package.scala:259:25]
  wire        _r_pte_barrier_io_y_u;	// @[package.scala:259:25]
  wire        _r_pte_barrier_io_y_x;	// @[package.scala:259:25]
  wire        _r_pte_barrier_io_y_w;	// @[package.scala:259:25]
  wire        _r_pte_barrier_io_y_r;	// @[package.scala:259:25]
  wire [20:0] _arb_io_out_bits_bits_addr;	// @[PTW.scala:236:19]
  reg  [43:0] r_pte_ppn;	// @[PTW.scala:275:18]
  reg         r_pte_d;	// @[PTW.scala:275:18]
  reg         r_pte_a;	// @[PTW.scala:275:18]
  reg         r_pte_u;	// @[PTW.scala:275:18]
  reg         r_pte_x;	// @[PTW.scala:275:18]
  reg         r_pte_w;	// @[PTW.scala:275:18]
  reg         r_pte_r;	// @[PTW.scala:275:18]
  always @(posedge clock) begin
    r_pte_ppn <= _r_pte_barrier_io_y_ppn;	// @[PTW.scala:275:18, package.scala:259:25]
    r_pte_d <= _r_pte_barrier_io_y_d;	// @[PTW.scala:275:18, package.scala:259:25]
    r_pte_a <= _r_pte_barrier_io_y_a;	// @[PTW.scala:275:18, package.scala:259:25]
    r_pte_u <= _r_pte_barrier_io_y_u;	// @[PTW.scala:275:18, package.scala:259:25]
    r_pte_x <= _r_pte_barrier_io_y_x;	// @[PTW.scala:275:18, package.scala:259:25]
    r_pte_w <= _r_pte_barrier_io_y_w;	// @[PTW.scala:275:18, package.scala:259:25]
    r_pte_r <= _r_pte_barrier_io_y_r;	// @[PTW.scala:275:18, package.scala:259:25]
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        r_pte_ppn = {_RANDOM_1[31:21], _RANDOM_2, _RANDOM_3[0]};	// @[PTW.scala:275:18]
        r_pte_d = _RANDOM_3[3];	// @[PTW.scala:275:18]
        r_pte_a = _RANDOM_3[4];	// @[PTW.scala:275:18]
        r_pte_u = _RANDOM_3[6];	// @[PTW.scala:275:18]
        r_pte_x = _RANDOM_3[7];	// @[PTW.scala:275:18]
        r_pte_w = _RANDOM_3[8];	// @[PTW.scala:275:18]
        r_pte_r = _RANDOM_3[9];	// @[PTW.scala:275:18]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  Arbiter_9 arb (	// @[PTW.scala:236:19]
    .io_in_2_bits_bits_addr (io_requestor_2_req_bits_bits_addr),
    .io_out_bits_bits_addr  (_arb_io_out_bits_bits_addr)
  );
  l2_tlb_ram_0 l2_tlb_ram_0 (	// @[DescribedSRAM.scala:17:26]
    .RW0_addr  (_arb_io_out_bits_bits_addr[8:0]),	// @[PTW.scala:236:19, :484:54]
    .RW0_en    (1'h0),
    .RW0_clk   (clock),
    .RW0_wmode (1'h0),
    .RW0_wdata ({^{18'h0, r_pte_ppn[19:0], r_pte_d, r_pte_a, r_pte_u, r_pte_x, r_pte_w, r_pte_r}, 18'h0, r_pte_ppn[19:0], r_pte_d, r_pte_a, r_pte_u, r_pte_x, r_pte_w, r_pte_r})	// @[Cat.scala:33:92, ECC.scala:72:55, PTW.scala:275:18, :447:17, :454:17, :458:82]
  );
  OptimizationBarrier_29 r_pte_barrier (	// @[package.scala:259:25]
    .io_x_ppn (r_pte_ppn),	// @[PTW.scala:275:18]
    .io_x_d   (r_pte_d),	// @[PTW.scala:275:18]
    .io_x_a   (r_pte_a),	// @[PTW.scala:275:18]
    .io_x_u   (r_pte_u),	// @[PTW.scala:275:18]
    .io_x_x   (r_pte_x),	// @[PTW.scala:275:18]
    .io_x_w   (r_pte_w),	// @[PTW.scala:275:18]
    .io_x_r   (r_pte_r),	// @[PTW.scala:275:18]
    .io_y_ppn (_r_pte_barrier_io_y_ppn),
    .io_y_d   (_r_pte_barrier_io_y_d),
    .io_y_a   (_r_pte_barrier_io_y_a),
    .io_y_u   (_r_pte_barrier_io_y_u),
    .io_y_x   (_r_pte_barrier_io_y_x),
    .io_y_w   (_r_pte_barrier_io_y_w),
    .io_y_r   (_r_pte_barrier_io_y_r)
  );
  assign io_requestor_0_pmp_0_cfg_l = io_dpath_pmp_0_cfg_l;
  assign io_requestor_0_pmp_0_cfg_a = io_dpath_pmp_0_cfg_a;
  assign io_requestor_0_pmp_0_cfg_w = io_dpath_pmp_0_cfg_w;
  assign io_requestor_0_pmp_0_cfg_r = io_dpath_pmp_0_cfg_r;
  assign io_requestor_0_pmp_0_addr = io_dpath_pmp_0_addr;
  assign io_requestor_0_pmp_0_mask = io_dpath_pmp_0_mask;
  assign io_requestor_0_pmp_1_cfg_l = io_dpath_pmp_1_cfg_l;
  assign io_requestor_0_pmp_1_cfg_a = io_dpath_pmp_1_cfg_a;
  assign io_requestor_0_pmp_1_cfg_w = io_dpath_pmp_1_cfg_w;
  assign io_requestor_0_pmp_1_cfg_r = io_dpath_pmp_1_cfg_r;
  assign io_requestor_0_pmp_1_addr = io_dpath_pmp_1_addr;
  assign io_requestor_0_pmp_1_mask = io_dpath_pmp_1_mask;
  assign io_requestor_0_pmp_2_cfg_l = io_dpath_pmp_2_cfg_l;
  assign io_requestor_0_pmp_2_cfg_a = io_dpath_pmp_2_cfg_a;
  assign io_requestor_0_pmp_2_cfg_w = io_dpath_pmp_2_cfg_w;
  assign io_requestor_0_pmp_2_cfg_r = io_dpath_pmp_2_cfg_r;
  assign io_requestor_0_pmp_2_addr = io_dpath_pmp_2_addr;
  assign io_requestor_0_pmp_2_mask = io_dpath_pmp_2_mask;
  assign io_requestor_0_pmp_3_cfg_l = io_dpath_pmp_3_cfg_l;
  assign io_requestor_0_pmp_3_cfg_a = io_dpath_pmp_3_cfg_a;
  assign io_requestor_0_pmp_3_cfg_w = io_dpath_pmp_3_cfg_w;
  assign io_requestor_0_pmp_3_cfg_r = io_dpath_pmp_3_cfg_r;
  assign io_requestor_0_pmp_3_addr = io_dpath_pmp_3_addr;
  assign io_requestor_0_pmp_3_mask = io_dpath_pmp_3_mask;
  assign io_requestor_0_pmp_4_cfg_l = io_dpath_pmp_4_cfg_l;
  assign io_requestor_0_pmp_4_cfg_a = io_dpath_pmp_4_cfg_a;
  assign io_requestor_0_pmp_4_cfg_w = io_dpath_pmp_4_cfg_w;
  assign io_requestor_0_pmp_4_cfg_r = io_dpath_pmp_4_cfg_r;
  assign io_requestor_0_pmp_4_addr = io_dpath_pmp_4_addr;
  assign io_requestor_0_pmp_4_mask = io_dpath_pmp_4_mask;
  assign io_requestor_0_pmp_5_cfg_l = io_dpath_pmp_5_cfg_l;
  assign io_requestor_0_pmp_5_cfg_a = io_dpath_pmp_5_cfg_a;
  assign io_requestor_0_pmp_5_cfg_w = io_dpath_pmp_5_cfg_w;
  assign io_requestor_0_pmp_5_cfg_r = io_dpath_pmp_5_cfg_r;
  assign io_requestor_0_pmp_5_addr = io_dpath_pmp_5_addr;
  assign io_requestor_0_pmp_5_mask = io_dpath_pmp_5_mask;
  assign io_requestor_0_pmp_6_cfg_l = io_dpath_pmp_6_cfg_l;
  assign io_requestor_0_pmp_6_cfg_a = io_dpath_pmp_6_cfg_a;
  assign io_requestor_0_pmp_6_cfg_w = io_dpath_pmp_6_cfg_w;
  assign io_requestor_0_pmp_6_cfg_r = io_dpath_pmp_6_cfg_r;
  assign io_requestor_0_pmp_6_addr = io_dpath_pmp_6_addr;
  assign io_requestor_0_pmp_6_mask = io_dpath_pmp_6_mask;
  assign io_requestor_0_pmp_7_cfg_l = io_dpath_pmp_7_cfg_l;
  assign io_requestor_0_pmp_7_cfg_a = io_dpath_pmp_7_cfg_a;
  assign io_requestor_0_pmp_7_cfg_w = io_dpath_pmp_7_cfg_w;
  assign io_requestor_0_pmp_7_cfg_r = io_dpath_pmp_7_cfg_r;
  assign io_requestor_0_pmp_7_addr = io_dpath_pmp_7_addr;
  assign io_requestor_0_pmp_7_mask = io_dpath_pmp_7_mask;
  assign io_requestor_1_status_debug = io_dpath_status_debug;
  assign io_requestor_1_pmp_0_cfg_l = io_dpath_pmp_0_cfg_l;
  assign io_requestor_1_pmp_0_cfg_a = io_dpath_pmp_0_cfg_a;
  assign io_requestor_1_pmp_0_cfg_w = io_dpath_pmp_0_cfg_w;
  assign io_requestor_1_pmp_0_cfg_r = io_dpath_pmp_0_cfg_r;
  assign io_requestor_1_pmp_0_addr = io_dpath_pmp_0_addr;
  assign io_requestor_1_pmp_0_mask = io_dpath_pmp_0_mask;
  assign io_requestor_1_pmp_1_cfg_l = io_dpath_pmp_1_cfg_l;
  assign io_requestor_1_pmp_1_cfg_a = io_dpath_pmp_1_cfg_a;
  assign io_requestor_1_pmp_1_cfg_w = io_dpath_pmp_1_cfg_w;
  assign io_requestor_1_pmp_1_cfg_r = io_dpath_pmp_1_cfg_r;
  assign io_requestor_1_pmp_1_addr = io_dpath_pmp_1_addr;
  assign io_requestor_1_pmp_1_mask = io_dpath_pmp_1_mask;
  assign io_requestor_1_pmp_2_cfg_l = io_dpath_pmp_2_cfg_l;
  assign io_requestor_1_pmp_2_cfg_a = io_dpath_pmp_2_cfg_a;
  assign io_requestor_1_pmp_2_cfg_w = io_dpath_pmp_2_cfg_w;
  assign io_requestor_1_pmp_2_cfg_r = io_dpath_pmp_2_cfg_r;
  assign io_requestor_1_pmp_2_addr = io_dpath_pmp_2_addr;
  assign io_requestor_1_pmp_2_mask = io_dpath_pmp_2_mask;
  assign io_requestor_1_pmp_3_cfg_l = io_dpath_pmp_3_cfg_l;
  assign io_requestor_1_pmp_3_cfg_a = io_dpath_pmp_3_cfg_a;
  assign io_requestor_1_pmp_3_cfg_w = io_dpath_pmp_3_cfg_w;
  assign io_requestor_1_pmp_3_cfg_r = io_dpath_pmp_3_cfg_r;
  assign io_requestor_1_pmp_3_addr = io_dpath_pmp_3_addr;
  assign io_requestor_1_pmp_3_mask = io_dpath_pmp_3_mask;
  assign io_requestor_1_pmp_4_cfg_l = io_dpath_pmp_4_cfg_l;
  assign io_requestor_1_pmp_4_cfg_a = io_dpath_pmp_4_cfg_a;
  assign io_requestor_1_pmp_4_cfg_w = io_dpath_pmp_4_cfg_w;
  assign io_requestor_1_pmp_4_cfg_r = io_dpath_pmp_4_cfg_r;
  assign io_requestor_1_pmp_4_addr = io_dpath_pmp_4_addr;
  assign io_requestor_1_pmp_4_mask = io_dpath_pmp_4_mask;
  assign io_requestor_1_pmp_5_cfg_l = io_dpath_pmp_5_cfg_l;
  assign io_requestor_1_pmp_5_cfg_a = io_dpath_pmp_5_cfg_a;
  assign io_requestor_1_pmp_5_cfg_w = io_dpath_pmp_5_cfg_w;
  assign io_requestor_1_pmp_5_cfg_r = io_dpath_pmp_5_cfg_r;
  assign io_requestor_1_pmp_5_addr = io_dpath_pmp_5_addr;
  assign io_requestor_1_pmp_5_mask = io_dpath_pmp_5_mask;
  assign io_requestor_1_pmp_6_cfg_l = io_dpath_pmp_6_cfg_l;
  assign io_requestor_1_pmp_6_cfg_a = io_dpath_pmp_6_cfg_a;
  assign io_requestor_1_pmp_6_cfg_w = io_dpath_pmp_6_cfg_w;
  assign io_requestor_1_pmp_6_cfg_r = io_dpath_pmp_6_cfg_r;
  assign io_requestor_1_pmp_6_addr = io_dpath_pmp_6_addr;
  assign io_requestor_1_pmp_6_mask = io_dpath_pmp_6_mask;
  assign io_requestor_1_pmp_7_cfg_l = io_dpath_pmp_7_cfg_l;
  assign io_requestor_1_pmp_7_cfg_a = io_dpath_pmp_7_cfg_a;
  assign io_requestor_1_pmp_7_cfg_w = io_dpath_pmp_7_cfg_w;
  assign io_requestor_1_pmp_7_cfg_r = io_dpath_pmp_7_cfg_r;
  assign io_requestor_1_pmp_7_addr = io_dpath_pmp_7_addr;
  assign io_requestor_1_pmp_7_mask = io_dpath_pmp_7_mask;
  assign io_requestor_2_status_debug = io_dpath_status_debug;
  assign io_requestor_2_pmp_0_cfg_l = io_dpath_pmp_0_cfg_l;
  assign io_requestor_2_pmp_0_cfg_a = io_dpath_pmp_0_cfg_a;
  assign io_requestor_2_pmp_0_cfg_x = io_dpath_pmp_0_cfg_x;
  assign io_requestor_2_pmp_0_addr = io_dpath_pmp_0_addr;
  assign io_requestor_2_pmp_0_mask = io_dpath_pmp_0_mask;
  assign io_requestor_2_pmp_1_cfg_l = io_dpath_pmp_1_cfg_l;
  assign io_requestor_2_pmp_1_cfg_a = io_dpath_pmp_1_cfg_a;
  assign io_requestor_2_pmp_1_cfg_x = io_dpath_pmp_1_cfg_x;
  assign io_requestor_2_pmp_1_addr = io_dpath_pmp_1_addr;
  assign io_requestor_2_pmp_1_mask = io_dpath_pmp_1_mask;
  assign io_requestor_2_pmp_2_cfg_l = io_dpath_pmp_2_cfg_l;
  assign io_requestor_2_pmp_2_cfg_a = io_dpath_pmp_2_cfg_a;
  assign io_requestor_2_pmp_2_cfg_x = io_dpath_pmp_2_cfg_x;
  assign io_requestor_2_pmp_2_addr = io_dpath_pmp_2_addr;
  assign io_requestor_2_pmp_2_mask = io_dpath_pmp_2_mask;
  assign io_requestor_2_pmp_3_cfg_l = io_dpath_pmp_3_cfg_l;
  assign io_requestor_2_pmp_3_cfg_a = io_dpath_pmp_3_cfg_a;
  assign io_requestor_2_pmp_3_cfg_x = io_dpath_pmp_3_cfg_x;
  assign io_requestor_2_pmp_3_addr = io_dpath_pmp_3_addr;
  assign io_requestor_2_pmp_3_mask = io_dpath_pmp_3_mask;
  assign io_requestor_2_pmp_4_cfg_l = io_dpath_pmp_4_cfg_l;
  assign io_requestor_2_pmp_4_cfg_a = io_dpath_pmp_4_cfg_a;
  assign io_requestor_2_pmp_4_cfg_x = io_dpath_pmp_4_cfg_x;
  assign io_requestor_2_pmp_4_addr = io_dpath_pmp_4_addr;
  assign io_requestor_2_pmp_4_mask = io_dpath_pmp_4_mask;
  assign io_requestor_2_pmp_5_cfg_l = io_dpath_pmp_5_cfg_l;
  assign io_requestor_2_pmp_5_cfg_a = io_dpath_pmp_5_cfg_a;
  assign io_requestor_2_pmp_5_cfg_x = io_dpath_pmp_5_cfg_x;
  assign io_requestor_2_pmp_5_addr = io_dpath_pmp_5_addr;
  assign io_requestor_2_pmp_5_mask = io_dpath_pmp_5_mask;
  assign io_requestor_2_pmp_6_cfg_l = io_dpath_pmp_6_cfg_l;
  assign io_requestor_2_pmp_6_cfg_a = io_dpath_pmp_6_cfg_a;
  assign io_requestor_2_pmp_6_cfg_x = io_dpath_pmp_6_cfg_x;
  assign io_requestor_2_pmp_6_addr = io_dpath_pmp_6_addr;
  assign io_requestor_2_pmp_6_mask = io_dpath_pmp_6_mask;
  assign io_requestor_2_pmp_7_cfg_l = io_dpath_pmp_7_cfg_l;
  assign io_requestor_2_pmp_7_cfg_a = io_dpath_pmp_7_cfg_a;
  assign io_requestor_2_pmp_7_cfg_x = io_dpath_pmp_7_cfg_x;
  assign io_requestor_2_pmp_7_addr = io_dpath_pmp_7_addr;
  assign io_requestor_2_pmp_7_mask = io_dpath_pmp_7_mask;
  assign io_requestor_2_customCSRs_csrs_0_value = io_dpath_customCSRs_csrs_0_value;
endmodule

