// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module XactTracker(
  input         clock,
                reset,
                io_alloc_valid,
  input  [5:0]  io_alloc_entry_shift,
  input  [11:0] io_alloc_entry_addr,
  input         io_alloc_entry_is_acc,
                io_alloc_entry_accumulate,
                io_alloc_entry_has_acc_bitwidth,
  input  [31:0] io_alloc_entry_scale,
  input  [15:0] io_alloc_entry_repeats,
  input  [7:0]  io_alloc_entry_pixel_repeats,
  input  [15:0] io_alloc_entry_len,
                io_alloc_entry_block_stride,
  input  [8:0]  io_alloc_entry_spad_row_offset,
  input  [6:0]  io_alloc_entry_bytes_to_read,
  input         io_alloc_entry_cmd_id,
  input  [3:0]  io_peek_xactid,
  input         io_peek_pop,
                io_counter_external_reset,
  output        io_alloc_ready,
  output [3:0]  io_alloc_xactid,
  output [5:0]  io_peek_entry_shift,
  output [11:0] io_peek_entry_addr,
  output        io_peek_entry_is_acc,
                io_peek_entry_accumulate,
                io_peek_entry_has_acc_bitwidth,
  output [31:0] io_peek_entry_scale,
  output [15:0] io_peek_entry_repeats,
  output [7:0]  io_peek_entry_pixel_repeats,
  output [15:0] io_peek_entry_len,
                io_peek_entry_block_stride,
  output [8:0]  io_peek_entry_spad_row_offset,
  output [6:0]  io_peek_entry_bytes_to_read,
  output        io_peek_entry_cmd_id,
                io_busy,
  output [31:0] io_counter_external_values_6
);

  reg               entries_0_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_0_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_0_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_0_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_0_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_0_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_0_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_0_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_0_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_0_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_0_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_0_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_0_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_0_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_1_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_1_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_1_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_1_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_1_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_1_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_1_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_1_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_1_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_1_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_1_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_1_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_1_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_1_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_2_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_2_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_2_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_2_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_2_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_2_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_2_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_2_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_2_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_2_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_2_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_2_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_2_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_2_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_3_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_3_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_3_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_3_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_3_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_3_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_3_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_3_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_3_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_3_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_3_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_3_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_3_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_3_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_4_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_4_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_4_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_4_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_4_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_4_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_4_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_4_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_4_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_4_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_4_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_4_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_4_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_4_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_5_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_5_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_5_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_5_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_5_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_5_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_5_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_5_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_5_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_5_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_5_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_5_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_5_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_5_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_6_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_6_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_6_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_6_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_6_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_6_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_6_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_6_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_6_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_6_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_6_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_6_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_6_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_6_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_7_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_7_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_7_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_7_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_7_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_7_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_7_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_7_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_7_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_7_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_7_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_7_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_7_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_7_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_8_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_8_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_8_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_8_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_8_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_8_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_8_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_8_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_8_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_8_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_8_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_8_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_8_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_8_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_9_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_9_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_9_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_9_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_9_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_9_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_9_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_9_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_9_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_9_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_9_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_9_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_9_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_9_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_10_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_10_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_10_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_10_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_10_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_10_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_10_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_10_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_10_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_10_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_10_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_10_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_10_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_10_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_11_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_11_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_11_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_11_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_11_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_11_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_11_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_11_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_11_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_11_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_11_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_11_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_11_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_11_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_12_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_12_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_12_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_12_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_12_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_12_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_12_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_12_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_12_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_12_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_12_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_12_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_12_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_12_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_13_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_13_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_13_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_13_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_13_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_13_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_13_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_13_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_13_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_13_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_13_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_13_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_13_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_13_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_14_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_14_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_14_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_14_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_14_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_14_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_14_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_14_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_14_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_14_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_14_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_14_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_14_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_14_bits_cmd_id;	// @[XactTracker.scala:67:20]
  reg               entries_15_valid;	// @[XactTracker.scala:67:20]
  reg  [5:0]        entries_15_bits_shift;	// @[XactTracker.scala:67:20]
  reg  [11:0]       entries_15_bits_addr;	// @[XactTracker.scala:67:20]
  reg               entries_15_bits_is_acc;	// @[XactTracker.scala:67:20]
  reg               entries_15_bits_accumulate;	// @[XactTracker.scala:67:20]
  reg               entries_15_bits_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
  reg  [31:0]       entries_15_bits_scale;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_15_bits_repeats;	// @[XactTracker.scala:67:20]
  reg  [7:0]        entries_15_bits_pixel_repeats;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_15_bits_len;	// @[XactTracker.scala:67:20]
  reg  [15:0]       entries_15_bits_block_stride;	// @[XactTracker.scala:67:20]
  reg  [8:0]        entries_15_bits_spad_row_offset;	// @[XactTracker.scala:67:20]
  reg  [6:0]        entries_15_bits_bytes_to_read;	// @[XactTracker.scala:67:20]
  reg               entries_15_bits_cmd_id;	// @[XactTracker.scala:67:20]
  wire [3:0]        free_entry = entries_0_valid ? (entries_1_valid ? (entries_2_valid ? (entries_3_valid ? (entries_4_valid ? (entries_5_valid ? (entries_6_valid ? (entries_7_valid ? (entries_8_valid ? (entries_9_valid ? (entries_10_valid ? (entries_11_valid ? (entries_12_valid ? (entries_13_valid ? {3'h7, entries_14_valid} : 4'hD) : 4'hC) : 4'hB) : 4'hA) : 4'h9) : 4'h8) : 4'h7) : 4'h6) : 4'h5) : 4'h4) : 4'h3) : 4'h2) : 4'h1) : 4'h0;	// @[Mux.scala:101:16, XactTracker.scala:67:20, :78:31]
  wire              _io_alloc_ready_T_14 = entries_0_valid & entries_1_valid & entries_2_valid & entries_3_valid & entries_4_valid & entries_5_valid & entries_6_valid & entries_7_valid & entries_8_valid & entries_9_valid & entries_10_valid & entries_11_valid & entries_12_valid & entries_13_valid & entries_14_valid & entries_15_valid;	// @[XactTracker.scala:67:20, :70:52]
  wire [15:0]       _GEN = {{entries_15_valid}, {entries_14_valid}, {entries_13_valid}, {entries_12_valid}, {entries_11_valid}, {entries_10_valid}, {entries_9_valid}, {entries_8_valid}, {entries_7_valid}, {entries_6_valid}, {entries_5_valid}, {entries_4_valid}, {entries_3_valid}, {entries_2_valid}, {entries_1_valid}, {entries_0_valid}};	// @[XactTracker.scala:67:20, :73:17]
  wire              _GEN_0 = _GEN[io_peek_xactid];	// @[XactTracker.scala:73:17]
  wire [15:0][5:0]  _GEN_1 = {{entries_15_bits_shift}, {entries_14_bits_shift}, {entries_13_bits_shift}, {entries_12_bits_shift}, {entries_11_bits_shift}, {entries_10_bits_shift}, {entries_9_bits_shift}, {entries_8_bits_shift}, {entries_7_bits_shift}, {entries_6_bits_shift}, {entries_5_bits_shift}, {entries_4_bits_shift}, {entries_3_bits_shift}, {entries_2_bits_shift}, {entries_1_bits_shift}, {entries_0_bits_shift}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0][11:0] _GEN_2 = {{entries_15_bits_addr}, {entries_14_bits_addr}, {entries_13_bits_addr}, {entries_12_bits_addr}, {entries_11_bits_addr}, {entries_10_bits_addr}, {entries_9_bits_addr}, {entries_8_bits_addr}, {entries_7_bits_addr}, {entries_6_bits_addr}, {entries_5_bits_addr}, {entries_4_bits_addr}, {entries_3_bits_addr}, {entries_2_bits_addr}, {entries_1_bits_addr}, {entries_0_bits_addr}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0]       _GEN_3 = {{entries_15_bits_is_acc}, {entries_14_bits_is_acc}, {entries_13_bits_is_acc}, {entries_12_bits_is_acc}, {entries_11_bits_is_acc}, {entries_10_bits_is_acc}, {entries_9_bits_is_acc}, {entries_8_bits_is_acc}, {entries_7_bits_is_acc}, {entries_6_bits_is_acc}, {entries_5_bits_is_acc}, {entries_4_bits_is_acc}, {entries_3_bits_is_acc}, {entries_2_bits_is_acc}, {entries_1_bits_is_acc}, {entries_0_bits_is_acc}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0]       _GEN_4 = {{entries_15_bits_accumulate}, {entries_14_bits_accumulate}, {entries_13_bits_accumulate}, {entries_12_bits_accumulate}, {entries_11_bits_accumulate}, {entries_10_bits_accumulate}, {entries_9_bits_accumulate}, {entries_8_bits_accumulate}, {entries_7_bits_accumulate}, {entries_6_bits_accumulate}, {entries_5_bits_accumulate}, {entries_4_bits_accumulate}, {entries_3_bits_accumulate}, {entries_2_bits_accumulate}, {entries_1_bits_accumulate}, {entries_0_bits_accumulate}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0]       _GEN_5 = {{entries_15_bits_has_acc_bitwidth}, {entries_14_bits_has_acc_bitwidth}, {entries_13_bits_has_acc_bitwidth}, {entries_12_bits_has_acc_bitwidth}, {entries_11_bits_has_acc_bitwidth}, {entries_10_bits_has_acc_bitwidth}, {entries_9_bits_has_acc_bitwidth}, {entries_8_bits_has_acc_bitwidth}, {entries_7_bits_has_acc_bitwidth}, {entries_6_bits_has_acc_bitwidth}, {entries_5_bits_has_acc_bitwidth}, {entries_4_bits_has_acc_bitwidth}, {entries_3_bits_has_acc_bitwidth}, {entries_2_bits_has_acc_bitwidth}, {entries_1_bits_has_acc_bitwidth}, {entries_0_bits_has_acc_bitwidth}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0][31:0] _GEN_6 = {{entries_15_bits_scale}, {entries_14_bits_scale}, {entries_13_bits_scale}, {entries_12_bits_scale}, {entries_11_bits_scale}, {entries_10_bits_scale}, {entries_9_bits_scale}, {entries_8_bits_scale}, {entries_7_bits_scale}, {entries_6_bits_scale}, {entries_5_bits_scale}, {entries_4_bits_scale}, {entries_3_bits_scale}, {entries_2_bits_scale}, {entries_1_bits_scale}, {entries_0_bits_scale}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0][15:0] _GEN_7 = {{entries_15_bits_repeats}, {entries_14_bits_repeats}, {entries_13_bits_repeats}, {entries_12_bits_repeats}, {entries_11_bits_repeats}, {entries_10_bits_repeats}, {entries_9_bits_repeats}, {entries_8_bits_repeats}, {entries_7_bits_repeats}, {entries_6_bits_repeats}, {entries_5_bits_repeats}, {entries_4_bits_repeats}, {entries_3_bits_repeats}, {entries_2_bits_repeats}, {entries_1_bits_repeats}, {entries_0_bits_repeats}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0][7:0]  _GEN_8 = {{entries_15_bits_pixel_repeats}, {entries_14_bits_pixel_repeats}, {entries_13_bits_pixel_repeats}, {entries_12_bits_pixel_repeats}, {entries_11_bits_pixel_repeats}, {entries_10_bits_pixel_repeats}, {entries_9_bits_pixel_repeats}, {entries_8_bits_pixel_repeats}, {entries_7_bits_pixel_repeats}, {entries_6_bits_pixel_repeats}, {entries_5_bits_pixel_repeats}, {entries_4_bits_pixel_repeats}, {entries_3_bits_pixel_repeats}, {entries_2_bits_pixel_repeats}, {entries_1_bits_pixel_repeats}, {entries_0_bits_pixel_repeats}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0][15:0] _GEN_9 = {{entries_15_bits_len}, {entries_14_bits_len}, {entries_13_bits_len}, {entries_12_bits_len}, {entries_11_bits_len}, {entries_10_bits_len}, {entries_9_bits_len}, {entries_8_bits_len}, {entries_7_bits_len}, {entries_6_bits_len}, {entries_5_bits_len}, {entries_4_bits_len}, {entries_3_bits_len}, {entries_2_bits_len}, {entries_1_bits_len}, {entries_0_bits_len}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0][15:0] _GEN_10 = {{entries_15_bits_block_stride}, {entries_14_bits_block_stride}, {entries_13_bits_block_stride}, {entries_12_bits_block_stride}, {entries_11_bits_block_stride}, {entries_10_bits_block_stride}, {entries_9_bits_block_stride}, {entries_8_bits_block_stride}, {entries_7_bits_block_stride}, {entries_6_bits_block_stride}, {entries_5_bits_block_stride}, {entries_4_bits_block_stride}, {entries_3_bits_block_stride}, {entries_2_bits_block_stride}, {entries_1_bits_block_stride}, {entries_0_bits_block_stride}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0][8:0]  _GEN_11 = {{entries_15_bits_spad_row_offset}, {entries_14_bits_spad_row_offset}, {entries_13_bits_spad_row_offset}, {entries_12_bits_spad_row_offset}, {entries_11_bits_spad_row_offset}, {entries_10_bits_spad_row_offset}, {entries_9_bits_spad_row_offset}, {entries_8_bits_spad_row_offset}, {entries_7_bits_spad_row_offset}, {entries_6_bits_spad_row_offset}, {entries_5_bits_spad_row_offset}, {entries_4_bits_spad_row_offset}, {entries_3_bits_spad_row_offset}, {entries_2_bits_spad_row_offset}, {entries_1_bits_spad_row_offset}, {entries_0_bits_spad_row_offset}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0][6:0]  _GEN_12 = {{entries_15_bits_bytes_to_read}, {entries_14_bits_bytes_to_read}, {entries_13_bits_bytes_to_read}, {entries_12_bits_bytes_to_read}, {entries_11_bits_bytes_to_read}, {entries_10_bits_bytes_to_read}, {entries_9_bits_bytes_to_read}, {entries_8_bits_bytes_to_read}, {entries_7_bits_bytes_to_read}, {entries_6_bits_bytes_to_read}, {entries_5_bits_bytes_to_read}, {entries_4_bits_bytes_to_read}, {entries_3_bits_bytes_to_read}, {entries_2_bits_bytes_to_read}, {entries_1_bits_bytes_to_read}, {entries_0_bits_bytes_to_read}};	// @[XactTracker.scala:67:20, :73:17]
  wire [15:0]       _GEN_13 = {{entries_15_bits_cmd_id}, {entries_14_bits_cmd_id}, {entries_13_bits_cmd_id}, {entries_12_bits_cmd_id}, {entries_11_bits_cmd_id}, {entries_10_bits_cmd_id}, {entries_9_bits_cmd_id}, {entries_8_bits_cmd_id}, {entries_7_bits_cmd_id}, {entries_6_bits_cmd_id}, {entries_5_bits_cmd_id}, {entries_4_bits_cmd_id}, {entries_3_bits_cmd_id}, {entries_2_bits_cmd_id}, {entries_1_bits_cmd_id}, {entries_0_bits_cmd_id}};	// @[XactTracker.scala:67:20, :73:17]
  wire              _GEN_14 = io_peek_pop & ~reset;	// @[XactTracker.scala:84:11]
  reg  [31:0]       total_latency;	// @[XactTracker.scala:94:30]
  wire              _T = io_alloc_valid & ~_io_alloc_ready_T_14;	// @[XactTracker.scala:36:36, :70:{21,52}]
  wire              _GEN_15 = _T & free_entry == 4'h0;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_16 = _T & free_entry == 4'h1;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_17 = _T & free_entry == 4'h2;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_18 = _T & free_entry == 4'h3;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_19 = _T & free_entry == 4'h4;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_20 = _T & free_entry == 4'h5;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_21 = _T & free_entry == 4'h6;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_22 = _T & free_entry == 4'h7;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_23 = _T & free_entry == 4'h8;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_24 = _T & free_entry == 4'h9;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_25 = _T & free_entry == 4'hA;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_26 = _T & free_entry == 4'hB;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_27 = _T & free_entry == 4'hC;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_28 = _T & free_entry == 4'hD;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_29 = _T & free_entry == 4'hE;	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  wire              _GEN_30 = _T & (&free_entry);	// @[Mux.scala:101:16, XactTracker.scala:36:36, :67:20, :77:26, :78:31]
  always @(posedge clock) begin
    if (_GEN_14)	// @[XactTracker.scala:84:11]
      assert__assert: assert(_GEN_0);	// @[XactTracker.scala:73:17, :84:11]
    entries_0_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'h0) & (_GEN_15 | entries_0_valid);	// @[XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_15) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_0_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_0_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_0_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_0_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_0_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_0_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_0_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_0_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_0_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_0_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_0_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_0_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_0_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_1_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'h1) & (_GEN_16 | entries_1_valid);	// @[XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_16) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_1_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_1_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_1_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_1_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_1_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_1_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_1_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_1_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_1_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_1_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_1_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_1_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_1_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_2_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'h2) & (_GEN_17 | entries_2_valid);	// @[XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_17) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_2_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_2_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_2_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_2_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_2_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_2_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_2_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_2_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_2_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_2_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_2_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_2_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_2_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_3_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'h3) & (_GEN_18 | entries_3_valid);	// @[XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_18) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_3_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_3_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_3_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_3_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_3_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_3_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_3_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_3_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_3_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_3_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_3_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_3_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_3_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_4_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'h4) & (_GEN_19 | entries_4_valid);	// @[XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_19) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_4_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_4_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_4_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_4_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_4_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_4_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_4_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_4_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_4_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_4_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_4_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_4_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_4_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_5_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'h5) & (_GEN_20 | entries_5_valid);	// @[XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_20) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_5_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_5_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_5_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_5_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_5_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_5_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_5_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_5_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_5_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_5_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_5_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_5_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_5_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_6_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'h6) & (_GEN_21 | entries_6_valid);	// @[XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_21) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_6_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_6_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_6_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_6_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_6_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_6_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_6_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_6_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_6_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_6_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_6_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_6_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_6_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_7_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'h7) & (_GEN_22 | entries_7_valid);	// @[XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_22) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_7_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_7_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_7_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_7_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_7_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_7_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_7_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_7_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_7_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_7_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_7_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_7_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_7_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_8_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'h8) & (_GEN_23 | entries_8_valid);	// @[Mux.scala:101:16, XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_23) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_8_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_8_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_8_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_8_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_8_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_8_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_8_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_8_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_8_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_8_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_8_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_8_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_8_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_9_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'h9) & (_GEN_24 | entries_9_valid);	// @[Mux.scala:101:16, XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_24) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_9_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_9_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_9_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_9_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_9_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_9_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_9_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_9_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_9_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_9_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_9_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_9_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_9_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_10_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'hA) & (_GEN_25 | entries_10_valid);	// @[Mux.scala:101:16, XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_25) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_10_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_10_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_10_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_10_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_10_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_10_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_10_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_10_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_10_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_10_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_10_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_10_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_10_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_11_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'hB) & (_GEN_26 | entries_11_valid);	// @[Mux.scala:101:16, XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_26) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_11_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_11_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_11_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_11_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_11_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_11_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_11_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_11_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_11_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_11_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_11_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_11_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_11_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_12_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'hC) & (_GEN_27 | entries_12_valid);	// @[Mux.scala:101:16, XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_27) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_12_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_12_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_12_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_12_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_12_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_12_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_12_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_12_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_12_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_12_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_12_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_12_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_12_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_13_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'hD) & (_GEN_28 | entries_13_valid);	// @[Mux.scala:101:16, XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_28) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_13_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_13_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_13_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_13_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_13_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_13_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_13_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_13_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_13_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_13_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_13_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_13_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_13_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_14_valid <= ~(reset | io_peek_pop & io_peek_xactid == 4'hE) & (_GEN_29 | entries_14_valid);	// @[Mux.scala:101:16, XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_29) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_14_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_14_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_14_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_14_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_14_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_14_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_14_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_14_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_14_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_14_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_14_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_14_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_14_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    entries_15_valid <= ~(reset | io_peek_pop & (&io_peek_xactid)) & (_GEN_30 | entries_15_valid);	// @[XactTracker.scala:67:20, :77:26, :78:31, :82:22, :83:35, :87:23, :88:29]
    if (_GEN_30) begin	// @[XactTracker.scala:67:20, :77:26, :78:31]
      entries_15_bits_shift <= io_alloc_entry_shift;	// @[XactTracker.scala:67:20]
      entries_15_bits_addr <= io_alloc_entry_addr;	// @[XactTracker.scala:67:20]
      entries_15_bits_is_acc <= io_alloc_entry_is_acc;	// @[XactTracker.scala:67:20]
      entries_15_bits_accumulate <= io_alloc_entry_accumulate;	// @[XactTracker.scala:67:20]
      entries_15_bits_has_acc_bitwidth <= io_alloc_entry_has_acc_bitwidth;	// @[XactTracker.scala:67:20]
      entries_15_bits_scale <= io_alloc_entry_scale;	// @[XactTracker.scala:67:20]
      entries_15_bits_repeats <= io_alloc_entry_repeats;	// @[XactTracker.scala:67:20]
      entries_15_bits_pixel_repeats <= io_alloc_entry_pixel_repeats;	// @[XactTracker.scala:67:20]
      entries_15_bits_len <= io_alloc_entry_len;	// @[XactTracker.scala:67:20]
      entries_15_bits_block_stride <= io_alloc_entry_block_stride;	// @[XactTracker.scala:67:20]
      entries_15_bits_spad_row_offset <= io_alloc_entry_spad_row_offset;	// @[XactTracker.scala:67:20]
      entries_15_bits_bytes_to_read <= io_alloc_entry_bytes_to_read;	// @[XactTracker.scala:67:20]
      entries_15_bits_cmd_id <= io_alloc_entry_cmd_id;	// @[XactTracker.scala:67:20]
    end
    if (reset)
      total_latency <= 32'h0;	// @[CounterFile.scala:140:39, XactTracker.scala:94:30]
    else if (io_counter_external_reset)
      total_latency <= 32'h0;	// @[CounterFile.scala:140:39, XactTracker.scala:94:30]
    else
      total_latency <= total_latency + {27'h0, {1'h0, {1'h0, {1'h0, {1'h0, entries_0_valid} + {1'h0, entries_1_valid}} + {1'h0, {1'h0, entries_2_valid} + {1'h0, entries_3_valid}}} + {1'h0, {1'h0, {1'h0, entries_4_valid} + {1'h0, entries_5_valid}} + {1'h0, {1'h0, entries_6_valid} + {1'h0, entries_7_valid}}}} + {1'h0, {1'h0, {1'h0, {1'h0, entries_8_valid} + {1'h0, entries_9_valid}} + {1'h0, {1'h0, entries_10_valid} + {1'h0, entries_11_valid}}} + {1'h0, {1'h0, {1'h0, entries_12_valid} + {1'h0, entries_13_valid}} + {1'h0, {1'h0, entries_14_valid} + {1'h0, entries_15_valid}}}}};	// @[Bitwise.scala:51:90, XactTracker.scala:67:20, :94:30, :98:36]
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin	// @[XactTracker.scala:84:11]
      if (_GEN_14 & ~_GEN_0) begin	// @[XactTracker.scala:73:17, :84:11]
        if (`ASSERT_VERBOSE_COND_)	// @[XactTracker.scala:84:11]
          $error("Assertion failed\n    at XactTracker.scala:84 assert(entries(io.peek.xactid).valid)\n");	// @[XactTracker.scala:84:11]
        if (`STOP_COND_)	// @[XactTracker.scala:84:11]
          $fatal;	// @[XactTracker.scala:84:11]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    logic [31:0] _RANDOM_7;
    logic [31:0] _RANDOM_8;
    logic [31:0] _RANDOM_9;
    logic [31:0] _RANDOM_10;
    logic [31:0] _RANDOM_11;
    logic [31:0] _RANDOM_12;
    logic [31:0] _RANDOM_13;
    logic [31:0] _RANDOM_14;
    logic [31:0] _RANDOM_15;
    logic [31:0] _RANDOM_16;
    logic [31:0] _RANDOM_17;
    logic [31:0] _RANDOM_18;
    logic [31:0] _RANDOM_19;
    logic [31:0] _RANDOM_20;
    logic [31:0] _RANDOM_21;
    logic [31:0] _RANDOM_22;
    logic [31:0] _RANDOM_23;
    logic [31:0] _RANDOM_24;
    logic [31:0] _RANDOM_25;
    logic [31:0] _RANDOM_26;
    logic [31:0] _RANDOM_27;
    logic [31:0] _RANDOM_28;
    logic [31:0] _RANDOM_29;
    logic [31:0] _RANDOM_30;
    logic [31:0] _RANDOM_31;
    logic [31:0] _RANDOM_32;
    logic [31:0] _RANDOM_33;
    logic [31:0] _RANDOM_34;
    logic [31:0] _RANDOM_35;
    logic [31:0] _RANDOM_36;
    logic [31:0] _RANDOM_37;
    logic [31:0] _RANDOM_38;
    logic [31:0] _RANDOM_39;
    logic [31:0] _RANDOM_40;
    logic [31:0] _RANDOM_41;
    logic [31:0] _RANDOM_42;
    logic [31:0] _RANDOM_43;
    logic [31:0] _RANDOM_44;
    logic [31:0] _RANDOM_45;
    logic [31:0] _RANDOM_46;
    logic [31:0] _RANDOM_47;
    logic [31:0] _RANDOM_48;
    logic [31:0] _RANDOM_49;
    logic [31:0] _RANDOM_50;
    logic [31:0] _RANDOM_51;
    logic [31:0] _RANDOM_52;
    logic [31:0] _RANDOM_53;
    logic [31:0] _RANDOM_54;
    logic [31:0] _RANDOM_55;
    logic [31:0] _RANDOM_56;
    logic [31:0] _RANDOM_57;
    logic [31:0] _RANDOM_58;
    logic [31:0] _RANDOM_59;
    logic [31:0] _RANDOM_60;
    logic [31:0] _RANDOM_61;
    logic [31:0] _RANDOM_62;
    logic [31:0] _RANDOM_63;
    logic [31:0] _RANDOM_64;
    logic [31:0] _RANDOM_65;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        _RANDOM_13 = `RANDOM;
        _RANDOM_14 = `RANDOM;
        _RANDOM_15 = `RANDOM;
        _RANDOM_16 = `RANDOM;
        _RANDOM_17 = `RANDOM;
        _RANDOM_18 = `RANDOM;
        _RANDOM_19 = `RANDOM;
        _RANDOM_20 = `RANDOM;
        _RANDOM_21 = `RANDOM;
        _RANDOM_22 = `RANDOM;
        _RANDOM_23 = `RANDOM;
        _RANDOM_24 = `RANDOM;
        _RANDOM_25 = `RANDOM;
        _RANDOM_26 = `RANDOM;
        _RANDOM_27 = `RANDOM;
        _RANDOM_28 = `RANDOM;
        _RANDOM_29 = `RANDOM;
        _RANDOM_30 = `RANDOM;
        _RANDOM_31 = `RANDOM;
        _RANDOM_32 = `RANDOM;
        _RANDOM_33 = `RANDOM;
        _RANDOM_34 = `RANDOM;
        _RANDOM_35 = `RANDOM;
        _RANDOM_36 = `RANDOM;
        _RANDOM_37 = `RANDOM;
        _RANDOM_38 = `RANDOM;
        _RANDOM_39 = `RANDOM;
        _RANDOM_40 = `RANDOM;
        _RANDOM_41 = `RANDOM;
        _RANDOM_42 = `RANDOM;
        _RANDOM_43 = `RANDOM;
        _RANDOM_44 = `RANDOM;
        _RANDOM_45 = `RANDOM;
        _RANDOM_46 = `RANDOM;
        _RANDOM_47 = `RANDOM;
        _RANDOM_48 = `RANDOM;
        _RANDOM_49 = `RANDOM;
        _RANDOM_50 = `RANDOM;
        _RANDOM_51 = `RANDOM;
        _RANDOM_52 = `RANDOM;
        _RANDOM_53 = `RANDOM;
        _RANDOM_54 = `RANDOM;
        _RANDOM_55 = `RANDOM;
        _RANDOM_56 = `RANDOM;
        _RANDOM_57 = `RANDOM;
        _RANDOM_58 = `RANDOM;
        _RANDOM_59 = `RANDOM;
        _RANDOM_60 = `RANDOM;
        _RANDOM_61 = `RANDOM;
        _RANDOM_62 = `RANDOM;
        _RANDOM_63 = `RANDOM;
        _RANDOM_64 = `RANDOM;
        _RANDOM_65 = `RANDOM;
        entries_0_valid = _RANDOM_0[0];	// @[XactTracker.scala:67:20]
        entries_0_bits_shift = _RANDOM_0[6:1];	// @[XactTracker.scala:67:20]
        entries_0_bits_addr = _RANDOM_0[18:7];	// @[XactTracker.scala:67:20]
        entries_0_bits_is_acc = _RANDOM_0[19];	// @[XactTracker.scala:67:20]
        entries_0_bits_accumulate = _RANDOM_0[20];	// @[XactTracker.scala:67:20]
        entries_0_bits_has_acc_bitwidth = _RANDOM_0[21];	// @[XactTracker.scala:67:20]
        entries_0_bits_scale = {_RANDOM_0[31:22], _RANDOM_1[21:0]};	// @[XactTracker.scala:67:20]
        entries_0_bits_repeats = {_RANDOM_1[31:22], _RANDOM_2[5:0]};	// @[XactTracker.scala:67:20]
        entries_0_bits_pixel_repeats = _RANDOM_2[13:6];	// @[XactTracker.scala:67:20]
        entries_0_bits_len = _RANDOM_2[29:14];	// @[XactTracker.scala:67:20]
        entries_0_bits_block_stride = {_RANDOM_2[31:30], _RANDOM_3[13:0]};	// @[XactTracker.scala:67:20]
        entries_0_bits_spad_row_offset = _RANDOM_3[22:14];	// @[XactTracker.scala:67:20]
        entries_0_bits_bytes_to_read = {_RANDOM_3[31:26], _RANDOM_4[0]};	// @[XactTracker.scala:67:20]
        entries_0_bits_cmd_id = _RANDOM_4[1];	// @[XactTracker.scala:67:20]
        entries_1_valid = _RANDOM_4[2];	// @[XactTracker.scala:67:20]
        entries_1_bits_shift = _RANDOM_4[8:3];	// @[XactTracker.scala:67:20]
        entries_1_bits_addr = _RANDOM_4[20:9];	// @[XactTracker.scala:67:20]
        entries_1_bits_is_acc = _RANDOM_4[21];	// @[XactTracker.scala:67:20]
        entries_1_bits_accumulate = _RANDOM_4[22];	// @[XactTracker.scala:67:20]
        entries_1_bits_has_acc_bitwidth = _RANDOM_4[23];	// @[XactTracker.scala:67:20]
        entries_1_bits_scale = {_RANDOM_4[31:24], _RANDOM_5[23:0]};	// @[XactTracker.scala:67:20]
        entries_1_bits_repeats = {_RANDOM_5[31:24], _RANDOM_6[7:0]};	// @[XactTracker.scala:67:20]
        entries_1_bits_pixel_repeats = _RANDOM_6[15:8];	// @[XactTracker.scala:67:20]
        entries_1_bits_len = _RANDOM_6[31:16];	// @[XactTracker.scala:67:20]
        entries_1_bits_block_stride = _RANDOM_7[15:0];	// @[XactTracker.scala:67:20]
        entries_1_bits_spad_row_offset = _RANDOM_7[24:16];	// @[XactTracker.scala:67:20]
        entries_1_bits_bytes_to_read = {_RANDOM_7[31:28], _RANDOM_8[2:0]};	// @[XactTracker.scala:67:20]
        entries_1_bits_cmd_id = _RANDOM_8[3];	// @[XactTracker.scala:67:20]
        entries_2_valid = _RANDOM_8[4];	// @[XactTracker.scala:67:20]
        entries_2_bits_shift = _RANDOM_8[10:5];	// @[XactTracker.scala:67:20]
        entries_2_bits_addr = _RANDOM_8[22:11];	// @[XactTracker.scala:67:20]
        entries_2_bits_is_acc = _RANDOM_8[23];	// @[XactTracker.scala:67:20]
        entries_2_bits_accumulate = _RANDOM_8[24];	// @[XactTracker.scala:67:20]
        entries_2_bits_has_acc_bitwidth = _RANDOM_8[25];	// @[XactTracker.scala:67:20]
        entries_2_bits_scale = {_RANDOM_8[31:26], _RANDOM_9[25:0]};	// @[XactTracker.scala:67:20]
        entries_2_bits_repeats = {_RANDOM_9[31:26], _RANDOM_10[9:0]};	// @[XactTracker.scala:67:20]
        entries_2_bits_pixel_repeats = _RANDOM_10[17:10];	// @[XactTracker.scala:67:20]
        entries_2_bits_len = {_RANDOM_10[31:18], _RANDOM_11[1:0]};	// @[XactTracker.scala:67:20]
        entries_2_bits_block_stride = _RANDOM_11[17:2];	// @[XactTracker.scala:67:20]
        entries_2_bits_spad_row_offset = _RANDOM_11[26:18];	// @[XactTracker.scala:67:20]
        entries_2_bits_bytes_to_read = {_RANDOM_11[31:30], _RANDOM_12[4:0]};	// @[XactTracker.scala:67:20]
        entries_2_bits_cmd_id = _RANDOM_12[5];	// @[XactTracker.scala:67:20]
        entries_3_valid = _RANDOM_12[6];	// @[XactTracker.scala:67:20]
        entries_3_bits_shift = _RANDOM_12[12:7];	// @[XactTracker.scala:67:20]
        entries_3_bits_addr = _RANDOM_12[24:13];	// @[XactTracker.scala:67:20]
        entries_3_bits_is_acc = _RANDOM_12[25];	// @[XactTracker.scala:67:20]
        entries_3_bits_accumulate = _RANDOM_12[26];	// @[XactTracker.scala:67:20]
        entries_3_bits_has_acc_bitwidth = _RANDOM_12[27];	// @[XactTracker.scala:67:20]
        entries_3_bits_scale = {_RANDOM_12[31:28], _RANDOM_13[27:0]};	// @[XactTracker.scala:67:20]
        entries_3_bits_repeats = {_RANDOM_13[31:28], _RANDOM_14[11:0]};	// @[XactTracker.scala:67:20]
        entries_3_bits_pixel_repeats = _RANDOM_14[19:12];	// @[XactTracker.scala:67:20]
        entries_3_bits_len = {_RANDOM_14[31:20], _RANDOM_15[3:0]};	// @[XactTracker.scala:67:20]
        entries_3_bits_block_stride = _RANDOM_15[19:4];	// @[XactTracker.scala:67:20]
        entries_3_bits_spad_row_offset = _RANDOM_15[28:20];	// @[XactTracker.scala:67:20]
        entries_3_bits_bytes_to_read = _RANDOM_16[6:0];	// @[XactTracker.scala:67:20]
        entries_3_bits_cmd_id = _RANDOM_16[7];	// @[XactTracker.scala:67:20]
        entries_4_valid = _RANDOM_16[8];	// @[XactTracker.scala:67:20]
        entries_4_bits_shift = _RANDOM_16[14:9];	// @[XactTracker.scala:67:20]
        entries_4_bits_addr = _RANDOM_16[26:15];	// @[XactTracker.scala:67:20]
        entries_4_bits_is_acc = _RANDOM_16[27];	// @[XactTracker.scala:67:20]
        entries_4_bits_accumulate = _RANDOM_16[28];	// @[XactTracker.scala:67:20]
        entries_4_bits_has_acc_bitwidth = _RANDOM_16[29];	// @[XactTracker.scala:67:20]
        entries_4_bits_scale = {_RANDOM_16[31:30], _RANDOM_17[29:0]};	// @[XactTracker.scala:67:20]
        entries_4_bits_repeats = {_RANDOM_17[31:30], _RANDOM_18[13:0]};	// @[XactTracker.scala:67:20]
        entries_4_bits_pixel_repeats = _RANDOM_18[21:14];	// @[XactTracker.scala:67:20]
        entries_4_bits_len = {_RANDOM_18[31:22], _RANDOM_19[5:0]};	// @[XactTracker.scala:67:20]
        entries_4_bits_block_stride = _RANDOM_19[21:6];	// @[XactTracker.scala:67:20]
        entries_4_bits_spad_row_offset = _RANDOM_19[30:22];	// @[XactTracker.scala:67:20]
        entries_4_bits_bytes_to_read = _RANDOM_20[8:2];	// @[XactTracker.scala:67:20]
        entries_4_bits_cmd_id = _RANDOM_20[9];	// @[XactTracker.scala:67:20]
        entries_5_valid = _RANDOM_20[10];	// @[XactTracker.scala:67:20]
        entries_5_bits_shift = _RANDOM_20[16:11];	// @[XactTracker.scala:67:20]
        entries_5_bits_addr = _RANDOM_20[28:17];	// @[XactTracker.scala:67:20]
        entries_5_bits_is_acc = _RANDOM_20[29];	// @[XactTracker.scala:67:20]
        entries_5_bits_accumulate = _RANDOM_20[30];	// @[XactTracker.scala:67:20]
        entries_5_bits_has_acc_bitwidth = _RANDOM_20[31];	// @[XactTracker.scala:67:20]
        entries_5_bits_scale = _RANDOM_21;	// @[XactTracker.scala:67:20]
        entries_5_bits_repeats = _RANDOM_22[15:0];	// @[XactTracker.scala:67:20]
        entries_5_bits_pixel_repeats = _RANDOM_22[23:16];	// @[XactTracker.scala:67:20]
        entries_5_bits_len = {_RANDOM_22[31:24], _RANDOM_23[7:0]};	// @[XactTracker.scala:67:20]
        entries_5_bits_block_stride = _RANDOM_23[23:8];	// @[XactTracker.scala:67:20]
        entries_5_bits_spad_row_offset = {_RANDOM_23[31:24], _RANDOM_24[0]};	// @[XactTracker.scala:67:20]
        entries_5_bits_bytes_to_read = _RANDOM_24[10:4];	// @[XactTracker.scala:67:20]
        entries_5_bits_cmd_id = _RANDOM_24[11];	// @[XactTracker.scala:67:20]
        entries_6_valid = _RANDOM_24[12];	// @[XactTracker.scala:67:20]
        entries_6_bits_shift = _RANDOM_24[18:13];	// @[XactTracker.scala:67:20]
        entries_6_bits_addr = _RANDOM_24[30:19];	// @[XactTracker.scala:67:20]
        entries_6_bits_is_acc = _RANDOM_24[31];	// @[XactTracker.scala:67:20]
        entries_6_bits_accumulate = _RANDOM_25[0];	// @[XactTracker.scala:67:20]
        entries_6_bits_has_acc_bitwidth = _RANDOM_25[1];	// @[XactTracker.scala:67:20]
        entries_6_bits_scale = {_RANDOM_25[31:2], _RANDOM_26[1:0]};	// @[XactTracker.scala:67:20]
        entries_6_bits_repeats = _RANDOM_26[17:2];	// @[XactTracker.scala:67:20]
        entries_6_bits_pixel_repeats = _RANDOM_26[25:18];	// @[XactTracker.scala:67:20]
        entries_6_bits_len = {_RANDOM_26[31:26], _RANDOM_27[9:0]};	// @[XactTracker.scala:67:20]
        entries_6_bits_block_stride = _RANDOM_27[25:10];	// @[XactTracker.scala:67:20]
        entries_6_bits_spad_row_offset = {_RANDOM_27[31:26], _RANDOM_28[2:0]};	// @[XactTracker.scala:67:20]
        entries_6_bits_bytes_to_read = _RANDOM_28[12:6];	// @[XactTracker.scala:67:20]
        entries_6_bits_cmd_id = _RANDOM_28[13];	// @[XactTracker.scala:67:20]
        entries_7_valid = _RANDOM_28[14];	// @[XactTracker.scala:67:20]
        entries_7_bits_shift = _RANDOM_28[20:15];	// @[XactTracker.scala:67:20]
        entries_7_bits_addr = {_RANDOM_28[31:21], _RANDOM_29[0]};	// @[XactTracker.scala:67:20]
        entries_7_bits_is_acc = _RANDOM_29[1];	// @[XactTracker.scala:67:20]
        entries_7_bits_accumulate = _RANDOM_29[2];	// @[XactTracker.scala:67:20]
        entries_7_bits_has_acc_bitwidth = _RANDOM_29[3];	// @[XactTracker.scala:67:20]
        entries_7_bits_scale = {_RANDOM_29[31:4], _RANDOM_30[3:0]};	// @[XactTracker.scala:67:20]
        entries_7_bits_repeats = _RANDOM_30[19:4];	// @[XactTracker.scala:67:20]
        entries_7_bits_pixel_repeats = _RANDOM_30[27:20];	// @[XactTracker.scala:67:20]
        entries_7_bits_len = {_RANDOM_30[31:28], _RANDOM_31[11:0]};	// @[XactTracker.scala:67:20]
        entries_7_bits_block_stride = _RANDOM_31[27:12];	// @[XactTracker.scala:67:20]
        entries_7_bits_spad_row_offset = {_RANDOM_31[31:28], _RANDOM_32[4:0]};	// @[XactTracker.scala:67:20]
        entries_7_bits_bytes_to_read = _RANDOM_32[14:8];	// @[XactTracker.scala:67:20]
        entries_7_bits_cmd_id = _RANDOM_32[15];	// @[XactTracker.scala:67:20]
        entries_8_valid = _RANDOM_32[16];	// @[XactTracker.scala:67:20]
        entries_8_bits_shift = _RANDOM_32[22:17];	// @[XactTracker.scala:67:20]
        entries_8_bits_addr = {_RANDOM_32[31:23], _RANDOM_33[2:0]};	// @[XactTracker.scala:67:20]
        entries_8_bits_is_acc = _RANDOM_33[3];	// @[XactTracker.scala:67:20]
        entries_8_bits_accumulate = _RANDOM_33[4];	// @[XactTracker.scala:67:20]
        entries_8_bits_has_acc_bitwidth = _RANDOM_33[5];	// @[XactTracker.scala:67:20]
        entries_8_bits_scale = {_RANDOM_33[31:6], _RANDOM_34[5:0]};	// @[XactTracker.scala:67:20]
        entries_8_bits_repeats = _RANDOM_34[21:6];	// @[XactTracker.scala:67:20]
        entries_8_bits_pixel_repeats = _RANDOM_34[29:22];	// @[XactTracker.scala:67:20]
        entries_8_bits_len = {_RANDOM_34[31:30], _RANDOM_35[13:0]};	// @[XactTracker.scala:67:20]
        entries_8_bits_block_stride = _RANDOM_35[29:14];	// @[XactTracker.scala:67:20]
        entries_8_bits_spad_row_offset = {_RANDOM_35[31:30], _RANDOM_36[6:0]};	// @[XactTracker.scala:67:20]
        entries_8_bits_bytes_to_read = _RANDOM_36[16:10];	// @[XactTracker.scala:67:20]
        entries_8_bits_cmd_id = _RANDOM_36[17];	// @[XactTracker.scala:67:20]
        entries_9_valid = _RANDOM_36[18];	// @[XactTracker.scala:67:20]
        entries_9_bits_shift = _RANDOM_36[24:19];	// @[XactTracker.scala:67:20]
        entries_9_bits_addr = {_RANDOM_36[31:25], _RANDOM_37[4:0]};	// @[XactTracker.scala:67:20]
        entries_9_bits_is_acc = _RANDOM_37[5];	// @[XactTracker.scala:67:20]
        entries_9_bits_accumulate = _RANDOM_37[6];	// @[XactTracker.scala:67:20]
        entries_9_bits_has_acc_bitwidth = _RANDOM_37[7];	// @[XactTracker.scala:67:20]
        entries_9_bits_scale = {_RANDOM_37[31:8], _RANDOM_38[7:0]};	// @[XactTracker.scala:67:20]
        entries_9_bits_repeats = _RANDOM_38[23:8];	// @[XactTracker.scala:67:20]
        entries_9_bits_pixel_repeats = _RANDOM_38[31:24];	// @[XactTracker.scala:67:20]
        entries_9_bits_len = _RANDOM_39[15:0];	// @[XactTracker.scala:67:20]
        entries_9_bits_block_stride = _RANDOM_39[31:16];	// @[XactTracker.scala:67:20]
        entries_9_bits_spad_row_offset = _RANDOM_40[8:0];	// @[XactTracker.scala:67:20]
        entries_9_bits_bytes_to_read = _RANDOM_40[18:12];	// @[XactTracker.scala:67:20]
        entries_9_bits_cmd_id = _RANDOM_40[19];	// @[XactTracker.scala:67:20]
        entries_10_valid = _RANDOM_40[20];	// @[XactTracker.scala:67:20]
        entries_10_bits_shift = _RANDOM_40[26:21];	// @[XactTracker.scala:67:20]
        entries_10_bits_addr = {_RANDOM_40[31:27], _RANDOM_41[6:0]};	// @[XactTracker.scala:67:20]
        entries_10_bits_is_acc = _RANDOM_41[7];	// @[XactTracker.scala:67:20]
        entries_10_bits_accumulate = _RANDOM_41[8];	// @[XactTracker.scala:67:20]
        entries_10_bits_has_acc_bitwidth = _RANDOM_41[9];	// @[XactTracker.scala:67:20]
        entries_10_bits_scale = {_RANDOM_41[31:10], _RANDOM_42[9:0]};	// @[XactTracker.scala:67:20]
        entries_10_bits_repeats = _RANDOM_42[25:10];	// @[XactTracker.scala:67:20]
        entries_10_bits_pixel_repeats = {_RANDOM_42[31:26], _RANDOM_43[1:0]};	// @[XactTracker.scala:67:20]
        entries_10_bits_len = _RANDOM_43[17:2];	// @[XactTracker.scala:67:20]
        entries_10_bits_block_stride = {_RANDOM_43[31:18], _RANDOM_44[1:0]};	// @[XactTracker.scala:67:20]
        entries_10_bits_spad_row_offset = _RANDOM_44[10:2];	// @[XactTracker.scala:67:20]
        entries_10_bits_bytes_to_read = _RANDOM_44[20:14];	// @[XactTracker.scala:67:20]
        entries_10_bits_cmd_id = _RANDOM_44[21];	// @[XactTracker.scala:67:20]
        entries_11_valid = _RANDOM_44[22];	// @[XactTracker.scala:67:20]
        entries_11_bits_shift = _RANDOM_44[28:23];	// @[XactTracker.scala:67:20]
        entries_11_bits_addr = {_RANDOM_44[31:29], _RANDOM_45[8:0]};	// @[XactTracker.scala:67:20]
        entries_11_bits_is_acc = _RANDOM_45[9];	// @[XactTracker.scala:67:20]
        entries_11_bits_accumulate = _RANDOM_45[10];	// @[XactTracker.scala:67:20]
        entries_11_bits_has_acc_bitwidth = _RANDOM_45[11];	// @[XactTracker.scala:67:20]
        entries_11_bits_scale = {_RANDOM_45[31:12], _RANDOM_46[11:0]};	// @[XactTracker.scala:67:20]
        entries_11_bits_repeats = _RANDOM_46[27:12];	// @[XactTracker.scala:67:20]
        entries_11_bits_pixel_repeats = {_RANDOM_46[31:28], _RANDOM_47[3:0]};	// @[XactTracker.scala:67:20]
        entries_11_bits_len = _RANDOM_47[19:4];	// @[XactTracker.scala:67:20]
        entries_11_bits_block_stride = {_RANDOM_47[31:20], _RANDOM_48[3:0]};	// @[XactTracker.scala:67:20]
        entries_11_bits_spad_row_offset = _RANDOM_48[12:4];	// @[XactTracker.scala:67:20]
        entries_11_bits_bytes_to_read = _RANDOM_48[22:16];	// @[XactTracker.scala:67:20]
        entries_11_bits_cmd_id = _RANDOM_48[23];	// @[XactTracker.scala:67:20]
        entries_12_valid = _RANDOM_48[24];	// @[XactTracker.scala:67:20]
        entries_12_bits_shift = _RANDOM_48[30:25];	// @[XactTracker.scala:67:20]
        entries_12_bits_addr = {_RANDOM_48[31], _RANDOM_49[10:0]};	// @[XactTracker.scala:67:20]
        entries_12_bits_is_acc = _RANDOM_49[11];	// @[XactTracker.scala:67:20]
        entries_12_bits_accumulate = _RANDOM_49[12];	// @[XactTracker.scala:67:20]
        entries_12_bits_has_acc_bitwidth = _RANDOM_49[13];	// @[XactTracker.scala:67:20]
        entries_12_bits_scale = {_RANDOM_49[31:14], _RANDOM_50[13:0]};	// @[XactTracker.scala:67:20]
        entries_12_bits_repeats = _RANDOM_50[29:14];	// @[XactTracker.scala:67:20]
        entries_12_bits_pixel_repeats = {_RANDOM_50[31:30], _RANDOM_51[5:0]};	// @[XactTracker.scala:67:20]
        entries_12_bits_len = _RANDOM_51[21:6];	// @[XactTracker.scala:67:20]
        entries_12_bits_block_stride = {_RANDOM_51[31:22], _RANDOM_52[5:0]};	// @[XactTracker.scala:67:20]
        entries_12_bits_spad_row_offset = _RANDOM_52[14:6];	// @[XactTracker.scala:67:20]
        entries_12_bits_bytes_to_read = _RANDOM_52[24:18];	// @[XactTracker.scala:67:20]
        entries_12_bits_cmd_id = _RANDOM_52[25];	// @[XactTracker.scala:67:20]
        entries_13_valid = _RANDOM_52[26];	// @[XactTracker.scala:67:20]
        entries_13_bits_shift = {_RANDOM_52[31:27], _RANDOM_53[0]};	// @[XactTracker.scala:67:20]
        entries_13_bits_addr = _RANDOM_53[12:1];	// @[XactTracker.scala:67:20]
        entries_13_bits_is_acc = _RANDOM_53[13];	// @[XactTracker.scala:67:20]
        entries_13_bits_accumulate = _RANDOM_53[14];	// @[XactTracker.scala:67:20]
        entries_13_bits_has_acc_bitwidth = _RANDOM_53[15];	// @[XactTracker.scala:67:20]
        entries_13_bits_scale = {_RANDOM_53[31:16], _RANDOM_54[15:0]};	// @[XactTracker.scala:67:20]
        entries_13_bits_repeats = _RANDOM_54[31:16];	// @[XactTracker.scala:67:20]
        entries_13_bits_pixel_repeats = _RANDOM_55[7:0];	// @[XactTracker.scala:67:20]
        entries_13_bits_len = _RANDOM_55[23:8];	// @[XactTracker.scala:67:20]
        entries_13_bits_block_stride = {_RANDOM_55[31:24], _RANDOM_56[7:0]};	// @[XactTracker.scala:67:20]
        entries_13_bits_spad_row_offset = _RANDOM_56[16:8];	// @[XactTracker.scala:67:20]
        entries_13_bits_bytes_to_read = _RANDOM_56[26:20];	// @[XactTracker.scala:67:20]
        entries_13_bits_cmd_id = _RANDOM_56[27];	// @[XactTracker.scala:67:20]
        entries_14_valid = _RANDOM_56[28];	// @[XactTracker.scala:67:20]
        entries_14_bits_shift = {_RANDOM_56[31:29], _RANDOM_57[2:0]};	// @[XactTracker.scala:67:20]
        entries_14_bits_addr = _RANDOM_57[14:3];	// @[XactTracker.scala:67:20]
        entries_14_bits_is_acc = _RANDOM_57[15];	// @[XactTracker.scala:67:20]
        entries_14_bits_accumulate = _RANDOM_57[16];	// @[XactTracker.scala:67:20]
        entries_14_bits_has_acc_bitwidth = _RANDOM_57[17];	// @[XactTracker.scala:67:20]
        entries_14_bits_scale = {_RANDOM_57[31:18], _RANDOM_58[17:0]};	// @[XactTracker.scala:67:20]
        entries_14_bits_repeats = {_RANDOM_58[31:18], _RANDOM_59[1:0]};	// @[XactTracker.scala:67:20]
        entries_14_bits_pixel_repeats = _RANDOM_59[9:2];	// @[XactTracker.scala:67:20]
        entries_14_bits_len = _RANDOM_59[25:10];	// @[XactTracker.scala:67:20]
        entries_14_bits_block_stride = {_RANDOM_59[31:26], _RANDOM_60[9:0]};	// @[XactTracker.scala:67:20]
        entries_14_bits_spad_row_offset = _RANDOM_60[18:10];	// @[XactTracker.scala:67:20]
        entries_14_bits_bytes_to_read = _RANDOM_60[28:22];	// @[XactTracker.scala:67:20]
        entries_14_bits_cmd_id = _RANDOM_60[29];	// @[XactTracker.scala:67:20]
        entries_15_valid = _RANDOM_60[30];	// @[XactTracker.scala:67:20]
        entries_15_bits_shift = {_RANDOM_60[31], _RANDOM_61[4:0]};	// @[XactTracker.scala:67:20]
        entries_15_bits_addr = _RANDOM_61[16:5];	// @[XactTracker.scala:67:20]
        entries_15_bits_is_acc = _RANDOM_61[17];	// @[XactTracker.scala:67:20]
        entries_15_bits_accumulate = _RANDOM_61[18];	// @[XactTracker.scala:67:20]
        entries_15_bits_has_acc_bitwidth = _RANDOM_61[19];	// @[XactTracker.scala:67:20]
        entries_15_bits_scale = {_RANDOM_61[31:20], _RANDOM_62[19:0]};	// @[XactTracker.scala:67:20]
        entries_15_bits_repeats = {_RANDOM_62[31:20], _RANDOM_63[3:0]};	// @[XactTracker.scala:67:20]
        entries_15_bits_pixel_repeats = _RANDOM_63[11:4];	// @[XactTracker.scala:67:20]
        entries_15_bits_len = _RANDOM_63[27:12];	// @[XactTracker.scala:67:20]
        entries_15_bits_block_stride = {_RANDOM_63[31:28], _RANDOM_64[11:0]};	// @[XactTracker.scala:67:20]
        entries_15_bits_spad_row_offset = _RANDOM_64[20:12];	// @[XactTracker.scala:67:20]
        entries_15_bits_bytes_to_read = _RANDOM_64[30:24];	// @[XactTracker.scala:67:20]
        entries_15_bits_cmd_id = _RANDOM_64[31];	// @[XactTracker.scala:67:20]
        total_latency = _RANDOM_65;	// @[XactTracker.scala:94:30]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  assign io_alloc_ready = ~_io_alloc_ready_T_14;	// @[XactTracker.scala:70:{21,52}]
  assign io_alloc_xactid = free_entry;	// @[Mux.scala:101:16]
  assign io_peek_entry_shift = _GEN_1[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_addr = _GEN_2[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_is_acc = _GEN_3[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_accumulate = _GEN_4[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_has_acc_bitwidth = _GEN_5[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_scale = _GEN_6[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_repeats = _GEN_7[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_pixel_repeats = _GEN_8[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_len = _GEN_9[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_block_stride = _GEN_10[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_spad_row_offset = _GEN_11[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_bytes_to_read = _GEN_12[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_peek_entry_cmd_id = _GEN_13[io_peek_xactid];	// @[XactTracker.scala:73:17]
  assign io_busy = entries_0_valid | entries_1_valid | entries_2_valid | entries_3_valid | entries_4_valid | entries_5_valid | entries_6_valid | entries_7_valid | entries_8_valid | entries_9_valid | entries_10_valid | entries_11_valid | entries_12_valid | entries_13_valid | entries_14_valid | entries_15_valid;	// @[XactTracker.scala:67:20, :75:44]
  assign io_counter_external_values_6 = total_latency;	// @[XactTracker.scala:94:30]
endmodule

